[[fbadmgd-nbackup]]
= Утилита NBACKUP

(((NBACKUP))) `nbackup` -- утилита резервного копирования, включенная в Firebird начиная с версии 2.0. Она предоставляет возможности, отсутствующие у `gbak` (штатной утилиты резервного копирования Firebird), но не заменяет `gbak`. Обе утилиты имеют свои достоинства и недостатки, и их вполне можно использовать совместно.

[[fbadmgd-nbackup-common]]
== Обзор возможностей nbackup

Утилита `nbackup` позволяет выполнять два типа задач:

* Делать полные и инкрементные копии. Инкрементные копии содержат только изменения относительно предыдущей резервной копии.
* Блокировать базу данных для ее онлайн-копирования средствами операционной системы или другими утилитами. В этом режиме `nbackup` ничего не сохраняет и не копирует. Он просто создает условия, при которых копирование файла базы данных является безопасным.

Обе этих задачи могут выполняться над активной базой данных, без необходимости отключения пользователей. Результирующий бэкап (или копия файла базы данных) будет содержать базу данных на момент начала копирования. Только `SYSDBA` и владелец базы данных (или администраторы операционной системы) могут делать бэкап, но при этом любой пользователь может восстановить базу данных из такого бэкапа. В этом плане `nbackup` не отличается от `gbak`.

[[fbadmgd-nbackup-advantage]]
=== Преимущества nbackup

* *В обоих режимах*: высокая скорость (насколько позволяет оборудование и операционная система), поскольку `nbackup` оперирует страницами БД, а не записями, и не проверяет данные на страницах.

* *В режиме копирования/восстановления*: экономия времени и дискового пространства, поскольку нет необходимости делать полную копию каждый раз. Это позволяет сильно упростить задачу резервного копирования много-гигабайтных баз данных.

* *В режиме блокировки*: полная свобода выбора способа копирования файла БД.

[[fbadmgd-nbackup-limitations]]
=== Недостатки nbackup

* Утилита `nbackup` не будет чистить мусор, освобождать место в базе данных, сжимать бэкап, и так далее.
* Вы не можете поменять владельца БД через резервное копирование и восстановление, как это может `gbak`.
* Утилита `nbackup` не делает "`transportable backup`", то есть, полученная копия базы данных может быть несовместима с Firebird на другом аппаратном обеспечении (kdv: имеются в виду платформы с разным порядком байт в integer -- big-endian и little-endian. К разным ОС на одной платформе это не имеет никакого отношения).
* В настоящий момент `nbackup` не работает с много-файловыми базами данных (которые являются атавизмом и практически не используются).
* `nbackup` может оперировать только с локальными файлами баз данных. `nbackup` можно запускать удаленно, но сами базы и их копии все равно должны быть локальными по отношению к серверу Firebird.

[[fbadmgd-nbackup-params]]
== Функции и параметры

В таблице перечислены параметры `nbackup` с общим описанием их назначения.

.Описание параметров nbackup
[cols="<1,<1", options="header",stripes="none"]
|===
^|Опция
^|Описание

|`-B _n_ _database_ [_filename_]`
|Сделать бэкап уровня `_n_` в указанный файл.

|`-R _database_ [_filename_ ...]`
|Восстановить базу данных из указанных файлов.

|`-L _database_`
|Заблокировать базу данных.

|`-N _database_`
|Разблокировать восстановленную базу данных.

|`-F _database_`
|Разблокировать заблокированную базу данных.

|`-S`
|Показать размер базы данных в страницах после блокирования (совместно с `–L`).

|`-T`
|Игнорировать триггеры уровня базы данных (совместно с `–B`, `-L`, `-N`).

|`-D {on | off}`
|Прямой ввод-вывод включить (`on`) или выключить (`off`) (совместно с `-B`).

|`-U _username_`
|Имя пользователя (совместно с `-B`, `-L`, `-N`).

|`-P _password_`
|Пароль пользователя (совместно с `-B`, `-L`, `-N`).

|`-FE _filename_`
|Взять пароль из файла (совместно с `–B`, `-L`, `-N`).

|`-DE <command>`
|Распаковка сжатых бекапов перед их восстановлением. В качестве аргумента принимает командную строку, которая должна распаковать архив и передать в `stdout` распакованный файл бэкапа.

|`-Z`
|Вывести версию (отдельно или совместно с `-B`, `-R`, `-L`, `-N`, `-F`).

|`-?`
|Вывод справки по всем параметрам.

|===

В зависимости от выбранной основной функции (`-B`, `-L`, `-N`, `-R` или `-F`) `nbackup` может требовать определенный уровень доступа к базе данных: соединение с сервером Firebird, прямой доступ к файлам, или и то и другое. Следующая таблица показывает детали:

.Описание параметров nbackup
[cols="<1,<2,<1", options="header",stripes="none"]
|===
^|Параметр
^|Назначение
^|Доступ

|`-B`
|Резервная копия
|Сервер и файл

|`-R`
|Восстановление
|Файл

|`-L`
|Блокирование
|Сервер

|`-N`
|Разблокирование
|Сервер

|`-F`
|Разблокирование после восстановления
|Файл

|===

[NOTE]
====
Регистр параметров не имеет значения, может быть указано `-B` или `-b`, и так далее. Параметры приведены в верхнем регистре как минимум потому, что один из параметров `-L` в нижнем регистре `-l` выглядит как `-1` в большинстве шрифтов.
====

Когда требуется доступ к серверу (с параметрами `-B`, `-L` и `-N`), пользователь должен указать имя пользователя и пароль (параметрами `-U` и `-P|-FE`, или через переменные пользователя `ISC_USER` и `ISC_PASSWORD`), или быть `root` на Unix или доверенным пользователем на Windows.

Когда требуется доступ к файловой системе (с `-B`, `-R` и `-F`), пользователь должен иметь достаточные привилегии к файлу базы данных для чтения и записи.

Когда требуется исключительный доступ к файлу (с `-R` и `-F`), пользователю не нужен логин к Firebird, и сервер Firebird может быть не запущен или отсутствовать.

[NOTE]
====
В приведенных таблицах и тексте имеется в виду доступ к базе данных. Доступ к файлам бэкапов -- всегда на уровне файловой системы.
====

