[[fbadmgd-gbak]]
= Утилита GBAK

(((GBAK))) Утилита `gbak` позволяет выполнять резервное копирование или восстановление базы данных с возможностью изменения указанных характеристик базы данных.

Запуск `gbak`без аргументов (или с неверным переключателем) или с переключателем `-?` приводит к отображению следующего экрана справочной информации:

[listing]
----
gbak:Usage:
     gbak -b <db set> <backup set> [backup options] [general options]
     gbak -c <backup set> <db set> [restore options] [general options]
     <db set> = <database> | <db1 size1>...<dbN> (size in db pages)
     <backup set> = <backup> | <bk1 size1>...<bkN> (size in bytes = n[K|M|G])
     -recreate overwrite and -replace can be used instead of -c
gbak:legal switches are:
    -B(ACKUP_DATABASE)    backup database to file
    -C(REATE_DATABASE)    create database from backup file (restore)
    -R(ECREATE_DATABASE) [O(VERWRITE)] create (or replace if OVERWRITE used)
                                database from backup file (restore)
    -REP(LACE_DATABASE)   replace database from backup file (restore)
gbak:backup options are:
    -CO(NVERT)            backup external files as tables
    -E(XPAND)             no data compression
    -FA(CTOR)             blocking factor
    -G(ARBAGE_COLLECT)    inhibit garbage collection
    -IG(NORE)             ignore bad checksums
    -L(IMBO)              ignore transactions in limbo
    -NOD(BTRIGGERS)       do not run database triggers
    -NT                   Non-Transportable backup file format
    -OL(D_DESCRIPTIONS)   save old style metadata descriptions
    -T(RANSPORTABLE)      transportable backup -- data in XDR format
gbak:restore options are:
    -BU(FFERS)            override page buffers default
    -FIX_FSS_D(ATA)       fix malformed UNICODE_FSS data
    -FIX_FSS_M(ETADATA)   fix malformed UNICODE_FSS metadata
    -I(NACTIVE)           deactivate indexes during restore
    -K(ILL)               restore without creating shadows
    -MO(DE) <access>      "read_only" or "read_write" access
    -N(O_VALIDITY)        do not restore database validity conditions
    -O(NE_AT_A_TIME)      restore one table at a time
    -P(AGE_SIZE)          override default page size
    -USE_(ALL_SPACE)      do not reserve space for record versions
gbak:general options are:
    -FE(TCH_PASSWORD)     fetch password from file
    -M(ETA_DATA)          backup or restore metadata only
    -PAS(SWORD)           Firebird password
    -RO(LE)               Firebird SQL role
    -SE(RVICE)            use services manager
    -SKIP_D(ATA)          skip data for table
    -ST(ATISTICS) TDRW    show statistics:
        T                 time from start
        D                 delta time
        R                 page reads
        W                 page writes
    -TRU(STED)            use trusted authentication
    -USER                 Firebird user name
    -V(ERIFY)             report each action taken
    -VERBI(NT) <n>        verbose information with explicit interval
    -Y  <path>            redirect/suppress status message output
    -Z                    print version number
gbak:switches can be abbreviated to the unparenthesized characters
----

Формат команд и список доступных переключателей отличается при создании резервной копи и восстановлении. Эти режимы работы и их переключатели будут описаны отдельно, а сейчас приведём список переключателей, которые являются общими для обоих режимов работы.

== Общие опции

Следующие параметры применимы как в режиме резервного копирования, так и в режиме восстановления базы данных.

.Команды и опции утилиты GBAK
[cols="<1,<1", options="header",stripes="none"]
|===
^|Опция
^|Описание

|`-FE[TCH_PASSWORD] _filename_`
|Извлекает пароль из файла. Если имя файла указано как `stdin`, то пользователю будет предложено ввести пароль. В системах POSIX имя файла `/dev/tty` также приведет к запросу пароля.

|`-M[ETADATA]`
|Этот переключатель приводит к тому, что ваши данные игнорируются, а не копируются и не восстанавливаются. При резервном копировании копируются только метаданные базы данных. При восстановлении любые данные в файле дампа не будут восстановлены.

|`-PAS[SWORD] _password_`
|Пароль пользователя, подключающегося к базе данных для резервного копирования, или используемый при создании БД в режиме восстановления.

Этот ключ не нужно указывать, если установлена переменная среды `ISC_PASSWORD`, а так же при использовании переключателя `-FE[TCH_PASSWORD]`, или доверительной аутентификации.

|`-RO[LE] _rolename_`
|Позволяет указать роль, которая будет использоваться подключающимся пользователем.

|`-SE[RVICE] <service>`
a|Указывает диспетчер служб.

Для локального соединения используйте просто имя диспетчера служб, которое всегда должно быть `service_mgr`.

Чтобы присоединить к удаленной машине необходимо дописать имя хоста в одном из следующих форматов с зависимости от используемого протокола:

TCP/IP:: `_hostname_[/_port_]:service_mgr`
WNET:: `{backslash}{backslash}__hostname__[@_port_]:service_mgr`
XNET:: `service_mgr`

Кроме того вы можете использовать обобщённый URL-подобный синтаксис

[listing,subs="+quotes,attributes"]
----
<protocol>://[_host_[:{_port_ {vbar} _service_}]/]service_mgr

<protocol> ::= inet {vbar} inet4 {vbar} inet6 {vbar} xnet {vbar} wnet
----

При использовании локального протокола (XNET) имя хоста указывать не нужно.

|`-SKIP_D[ATA] _pattern_`
|Пропускает данные таблиц, имена которых соответствуют указанному здесь регулярному выражению в SQL-синтаксисе (см. оператор `SIMILAR TO`).

|`-ST[ATISTICS] TRWD`
|Выводит статистику в процессе работы (работает вместе с `-V[ERIFY]`).

*T* -- время от начала работы `gbak`; +
*R* -- число страниц прочитанных с последнего вывода на экран; +
*W* -- число страниц записанных с последнего вывода на экран; +
*D* -- время прошедшее с последнего вывода на экран.

|`-TRU[STED]`
|Использовать доверительную аутентификацию.

|`-U[SER] _username_`
|Позволяет указать имя пользователя `SYSDBA` или пользователя владельца базы данных, если необходимо выполнить резервное копирование базы данных.

При восстановлении базы данных позволяет указать любого пользователя у которого есть привилегия `CREATE DATABASE`. Этот пользователь будет владельцем восстановленной базы данных.

Этот ключ не нужно указывать, если установлена переменная среды `ISC_ISC_USER`, или при использовании доверительной аутентификации.

|`-V[ERIFY]`
|Отчет о каждом выполненном действии.

Обычно `gbak` работает молчаливо, и информация не выводится на дисплей. Этот переключатель изменяет ситуацию и вызывает отображение большого количества информации.

При использовании этого переключателя по умолчанию информация выводится на экран, но вы можете перенаправить её в файл, используя ключ `-y`.

|`-VERBI[NT] _n_`
|Подробный вывод лога действии с заданным интервалом времени.

|`-Y {_log_filename_ {vbar} suppress}`
|Вывод лога действий в указанный файл.

Используется вместе с ключом `-v[erify]` для перенаправления сообщений о состоянии в файл или устройство, а не на экран, или для их полного подавления.

Если используется `-y suppress`, то никакая информация не будет записываться на экран независимо от того, указан ли `-v[erify]`.

Если задано имя файла и указан ключ `-v[erify]`, то сообщения о прогрессе и предупреждениях будут записаны в указанный файл.

|`-Z`
|Вывод версии `gbak` и версии сервера Firebird.

|===

[NOTE]
====
Параметр `-v` в справке, выдаваемой `gbak`, описан как `-v[erify]`. Это неверно, потому что опция `gbak -v` не имеет ничего общего с проверкой БД. Скорее, этот параметр должен расшифровываться как "`verbose`".
====

== Использование диспетчера служб

В обычном режиме при создании резервной копии `gbak` самостоятельно читает с сервера метаданные и данные из записывает их в файл резервной копии. При восстановлении `gbak` читает файл резервной копии и отправляет серверу инструкции для восстановления.

При использовании диспетчера служб `gbak` только даёт команду начать резервную копию или восстановление серверу, и он сам делает это. Однако `gbak` может принимать лог действий от сервера, который будет вестись при указании ключа `-v[erify]`. В этом случае при создании резервной копии файлы копии будут создаваться на сервере. Для возможности восстановления базы данных файлы резервной копии так же должны находится на сервере.

Для использования диспетчера служб необходимо указать параметр `-SE[RVICE] <service>`.

Для локального соединения используйте просто имя диспетчера служб, которое всегда должно быть `service_mgr`.

Чтобы присоединить к удаленной машине необходимо дописать имя хоста в одном из следующих форматов с зависимости от используемого протокола:

TCP/IP:: `_hostname_[/_port_]:service_mgr`
WNET:: `{backslash}{backslash}__hostname__[@_port_]:service_mgr`
XNET:: `service_mgr`

Кроме того вы можете использовать обобщённый URL-подобный синтаксис

[listing,subs="+quotes,attributes"]
----
<protocol>://[_host_[:{_port_ | _service_}]/]service_mgr

<protocol> ::= inet | inet4 | inet6 | xnet | wnet
----

При использовании локального протокола (XNET) имя хоста указывать не нужно.

[IMPORTANT]
====
Если используете диспетчер служб, то не надо указывать спецификацию удалённого хоста в имени базы данных как при резервном копировании, так и при восстановлении.
====

== Создание резервных копий

`gbak` создает непротиворечивую резервную копию базы данных, начиная транзакцию в режиме изолированности `SNAPSHOT`, которая охватывает весь период резервного копирования. В процессе резервного копирования `gbak` читает и сохраняет в специальный файл (или файлы) метаданные (описания таблиц, процедур, триггеров и т. д.) и данные таблиц. Любые изменения, сделанные транзакциями запущенными после начала резервного копирования, не попадут в файл резервной копии. Таким образом резервная копия будет представлять собой копию всей базы данных на момент начала резервного копирования. Это позволяет приложениям беспрепятственно работать с базой данных во время резервного копирования.

Для возможности резервного копирования пользователь должен быть авторизован как `SYSDBA` быть владельцем базы данных или обладать административными привилегиями в ней (соединиться с ролью `RDB$ADMIN`).

Формат командной строки для создания резервной копии выглядит следующим образом:

[listing,subs="+quotes,macros,attributes"]
----
gbak -b <database> <backup set> [<backup options>]

<backup set> ::= _backup_file_ | {_bk1_ _size1_} ... _bkN_

<database> ::= [<server_spec>]{_filepath_ | _db_alias_}

<server_spec> ::=
    _host_[/ {_port_ | _service_}]:
  | {backslash}{backslash}__host__\
  | <protocol>://[_host_[:{_port_ | _service_}]/]

<protocol> ::= inet | inet4 | inet6 | wnet | xnet
----

=== Опции резервного копирования

.Опции резервного копирования
[cols="<1,<1", options="header",stripes="none"]
|===
^|Опция
^|Описание

|`-B[ACKUP_DATABASE]`
|Создать резервную копию

|`-CO[NVERT]`
|Конвертировать внешние таблицы во внутренние таблицы базы данных.

|`-E[XPAND]`
|Отключение сжатия данных при резервном копировании. По умолчанию резервная копия записывается в "`сжатом`" виде.

|`-FA[CTOR] _n_`
|При резервном копировании на физическое ленточное устройство этот переключатель позволяет указать коэффициент блокировки ленты. Атавизм.

|`-G[ARBAGE_COLLECT]`
|Отключение сборки мусора во время резервного копирования.

`gbak` подключается к базе данных как и любое обычное приложение. Обычно при чтении таблиц сервер проверяет записи на наличие мусора, и в случае его обнаружения убирает его. Использование этого параметра предотвращает запуск сборки мусора во время резервного копирования. Это может помочь ускорить резервное копирование.

|`-IG[NORE]`
|Этот переключатель заставляет `gbak` игнорировать неверные контрольные суммы в базе данных.

В обычной командной строке для создания резервной копии базы данных категорически не рекомендуется указывать параметр `-ig`! Если база данных вдруг окажется повреждена, то с этим параметром вы можете "`не увидеть`"повреждение. Так что, `-ig` для `gbak` используется только в крайнем случае -- когда поврежденная база починена утилитой `gfix`, но обычная резервная копия не проходит. Только тогда имеет смысл повторить создание резервной копии с опцией `-ig`.

|`-L[IMBO]`
|Игнорировать зависшие двухфазные транзакции (limbo).

Не сохраняет в резервной копии БД версии записей, которые созданы транзакциями, находящимися в состоянии in limbo. Такое состояние может быть только у не завершившихся транзакций двухфазного подтверждения (Two Phase Commit -- 2PC). Если приложения не используют двухфазное подтверждение, или вы не знаете, что это такое, то этот параметр вам никогда не понадобится.

|`-NOD[BTRIGGERS]`
|Не запускать триггеры уровня базы данных.

|`-NT`
|Формат резервной копии, непереносимой между аппаратными платформами.

Если вы используете этот переключатель для создания резервной копии, вы можете восстановить ее только на аналогичной платформе.

|`-OL[D_DESCRIPTIONS]`
|Устарел. Требовался для создания резервных копий в формате совместимом с Interbase 3.3.

|`-T[RANSPORTABLE]`
|Создаёт транспортабельную (переносимую) резервную копию.

Формат файла резервную копии по умолчанию является переносимым, поэтому указывать данный переключатель не следует. Переносимые файлы резервных копий записываются в формате, известном как формат представления внешних данных (XDR). Такой файл резервной копии можно восстановить на альтернативной аппаратной платформе, где порядок байт в целых числах отличается. То есть, например, между Intel и Sparc, или HP-UX и Intel, и так далее. Но между Windows и Linux (или другой ОС) на Intel файл резервной копии будет и так переносимым, даже при указании ключа `-nt` (non-transportable).

|===

=== Имя базы данных

Как уже было сказано, что `gbak` это обычная программа, которая читает данные из базы данных, то сама база данных и сервер могут находиться где угодно.

Если база данных распложено локально, то достаточно просто указать путь к первичному файлу базы данных или её псевдоним. Пример:

[source,console]
----
gbak -b C:\data\my.fdb D:\backup\my.fbk ...
----

или с использованием псевдонима базы данных

[source,console]
----
gbak -b mydb D:\backup\my.fbk ...
----

Если же база данных расположено на удалённом хосте, то необходимо дополнить её имя спецификацией удалённого сервера. Например:

[source,console]
----
gbak -b server:C:\data\my.fdb D:\backup\my.fbk ...
----

или

[source,console]
----
gbak -b server:mydb D:\backup\my.fbk ...
----

Спецификацию удалённого хоста удобно указывать с помощью URL-подобного синтаксиса, в котором можно явно задать используемый протокол:

[source,console]
----
gbak -b inet://localhost:3053/mydb D:\backup\my.fbk ...

gbak -b wnet:///mydb D:\backup\my.fbk ...
----

[IMPORTANT]
====
При использовании диспетчера служб (переключатель `-SE`) перед именем базы данных не нужно указывать спецификацию удалённого сервера, поскольку в этом случае она указывается перед именем диспетчера служб.
====

=== Имя файла(ов) резервной копии

Сразу после имени базы данных необходимо указать полный путь до файла резервной копии. Если для создания резервной копи не используется диспетчер служб (переключатель `-SE`), то резервная копия будет создана на локальной машине, с которой запущен `gbak`. При использовании диспетчера служб резервная копия будет создана на удалённом компьютере, на котором расположена база данных.

Имя файла резервной копии может любое расширение. Вы можете встретить `bak`, `gbk`, `fbk`, и так далее. Никаких ограничений в этом плане не накладывается. Имя резервной копии лучше формировать как имя базы и дату, причем дату лучше всего указывать в "`японском`" формате, в виде YYYYMMDD -- так имена файлов будут корректно сортироваться при просмотре папки.

Существует возможность делать многофайловую резервную копию, разбивая резервную копию на части. В этом случае указывается несколько файлов резервных копий. После каждого файла резервной копии, кроме самого последнего, необходимо указать его максимальный размер. По умолчанию размер указывается в байтах. Вы можете также указывать размер в килобайтах, мегабайтах и гигабайтах, используя множители (`k`, `m` или `g`).

.Создание многофайловой копии
[example]
====
В примере ниже будут созданы три файла резервной копии, два файла размером по 100 Мегабайт, и третий файл в котором расположена оставшаяся часть резервной копии.

[source,console]
----
gbak -b C:\data\my.fdb D:\backup\copy_1.fbk 100M D:\backup\copy_2.fbk 100M
  D:\backup\copy_3.fbk -user SYSDBA -password masterkey
----
====

=== Ускорение резервного копирования

Есть несколько приемов, которые вы можете использовать для ускорения резервного копирования. Первый -- запретить сборку мусора во время выполнения резервного копирования. Сборка мусора удаляет старые версии записей, которые больше не требуются, и это обычно покрывается чисткой (sweep) -- ручной или автоматической -- или полным сканированием таблицы любой затронутой таблицы. Поскольку `gbak` получает доступ ко всем строкам в резервируемых таблицах, он также запускает сборку мусора, что может замедлить резервное копирование. Чтобы предотвратить сборку мусора во время резервного копирования, используйте параметр `-g[arbage_collect]`.

[source,console]
----
gbak -backup -g employee /backups/employee.fbk
----

Второй вариант -- делать резервное копирование с использованием диспетчера служб, то есть задействовать опцию `-se[rvice]`.

В обычном режиме при создании резервной копии `gbak` самостоятельно читает с сервера метаданные и данные из записывает их в файл резервной копии. При использовании диспетчера служб gbak только даёт команду начать резервную копию или восстановление серверу, и он сам делает это. Однако `gbak` может принимать лог действий от сервера, который будет вестись при указании ключа `-v[erify]`. В этом случае при создании резервной копии файлы копии будут создаваться на сервере. Для возможности восстановления базы данных файлы резервной копии так же должны находится на сервере.

Поскольку при использовании диспетчера служб резервную копию выполняет сам сервер, то это позволяет избежать копирования данных по сети, за исключением лога действий, если он включен. Это в свою очередь позволяет делать резервную копию гораздо быстрее, даже на локальном компьютере.

Примеры резервного копирования с использованием диспетчера служб:

[source,console]
----
gbak -backup -service tux:service_mgr employee /backups/employee.fbk

gbak -backup -service inet4://tux:3051/service_mgr employee /backups/employee.fbk
----

Для достижения лучшего результата вы можете комбинировать опции `-g[arbage_collect]` и `-se[rvice]`.

