[[fbadmgd-nbackup]]
= Утилита NBACKUP

(((NBACKUP))) `nbackup` -- утилита резервного копирования, включенная в Firebird начиная с версии 2.0. Она предоставляет возможности, отсутствующие у `gbak` (штатной утилиты резервного копирования Firebird), но не заменяет `gbak`. Обе утилиты имеют свои достоинства и недостатки, и их вполне можно использовать совместно.

[[fbadmgd-nbackup-common]]
== Обзор возможностей Nbackup

Утилита `nbackup` позволяет выполнять два типа задач:

* Делать полные и инкрементные копии. Инкрементные копии содержат только изменения относительно предыдущей резервной копии.
* Блокировать базу данных для ее онлайн-копирования средствами операционной системы или другими утилитами. В этом режиме `nbackup` ничего не сохраняет и не копирует. Он просто создает условия, при которых копирование файла базы данных является безопасным.

Обе этих задачи могут выполняться над активной базой данных, без необходимости отключения пользователей. Результирующий бэкап (или копия файла базы данных) будет содержать базу данных на момент начала копирования. Только `SYSDBA` и владелец базы данных (или администраторы операционной системы) могут делать бэкап, но при этом любой пользователь может восстановить базу данных из такого бэкапа. В этом плане `nbackup` не отличается от `gbak`.

[[fbadmgd-nbackup-advantage]]
== Преимущества nbackup

* *В обоих режимах*: высокая скорость (насколько позволяет оборудование и операционная система), поскольку `nbackup` оперирует страницами БД, а не записями, и не проверяет данные на страницах.

* *В режиме копирования/восстановления*: экономия времени и дискового пространства, поскольку нет необходимости делать полную копию каждый раз. Это позволяет сильно упростить задачу резервного копирования много-гигабайтных баз данных.

* *В режиме блокировки*: полная свобода выбора способа копирования файла БД.
