[[fbadmgd-isql]]
= Утилита ISQL

(((ISQL))) В этой главе содержится описание консольной утилиты Firebird Interactive SQL Utility (`isql`) и инструкции по его использованию для выполнения задач в базе данных.

Утилита ISQL расположена в корневом каталоге установки Firebird. Она предоставляет интерфейс командной строки для интерактивного доступа к базе данных Firebird. ISQL принимает операторы DSQL вместе с группой команд `SET` и `SHOW` для запросов и взаимодействия с базой данных Firebird. Некоторые команды `SET` могут быть включены в сценарии DDL для выполнения пакетных операций в `isql`. Она также обрабатывает команды DDL, DML и консоли.

Утилита `isql` может использоваться в трех режимах: в качестве интерактивного сеанса; прямо из командной строки; и как неинтерактивный сеанс, используя сценарий оболочки или пакетный файл. В каждом из режимов могут выполняться разные задачи, как показано ниже:

* В интерактивном режиме пользователь последовательно вводит команды для работы с базами данных и тут же получает результат их выполнения. При этом одна команда может быть разбита на несколько строк. После завершения обработки каждой команды и вывода всех результатов её работы пользователь получает приглашение ввести следующую команду до тех пор, пока не будет введена команда выхода из интерактивного режима `QUIT` или `EXIT`. Утилиту `isql` можно использовать в интерактивном режиме для:

** Создания, редактирования, удаления или просмотра данных и метаданных;
** Ввода файла сценария содержащего пакет SQL запросов;
** Добавлять и модифицировать данные;
** Предоставлять разрешение пользователю и отбирать их;
** Управлять учётными записями;
** Выполнять административные функции базы данных.

* Непосредственно из командной строки, с отдельными параметрами и без запуска интерактивного сеанса. Команды выполняются и по завершении возвращают управление автоматически операционной системе.
* В неинтерактивном сеансе пользователь использует сценарий оболочки или пакетный файл для выполнения функций базы данных.

[NOTE]
====
Поскольку другие приложения в среде Linux, например, MySQL, также используют `isql` в качестве имени утилиты, рекомендуется запускать утилиту Firebird из ее собственного каталога или указывать абсолютный путь к файлу, если у вас есть другая реляционная база данных, кроме Firebird, установленная на вашей машине.

Некоторые из затронутых дистрибутивов, такие как Mint Linux -- на основе Ubuntu -- переименовали Firebird в `isql` в `isql-fb`. Аналогичные изменения могут быть и в других дистрибутивах.

Кроме того, не все дистрибутивы устанавливают Firebird в одно и то же место. Например, OpenSuse устанавливает практически все в `/opt/firebird/3.0`, но Ubuntu и его производные устанавливают его в различные места, но утилиты находятся в `/usr/bin`.
====

Далее предполагается что утилита называется `isql`.

[[fbadmgd-isql-invoking]]
== Запуск isql

Перейдите в корневой каталог установки сервера Firebird и введите в командной строке `isql` (Windows) или `./isql` (Linux). Если каталог с `isql` добавлен в `PATH`, то нет необходимости переходить в него.

Синтаксис запуска `isql` следующий:

[listing,subs="+quotes,macros,attributes"]
----
isql <options> <database>

database ::= [<server spec>]{_db_filename_ | _db_alias_}

<server_spec> ::=
    _host_[/ {_port_ | _service_}]:
  | {backslash}{backslash}__host__\
  | <protocol>://[_host_[:{_port_ | _service_}]/]

<protocol> ::= inet | inet4 | inet6 | xnet
----

Если параметры `&lt;options&gt;` не указаны, `isql` запускает интерактивный сеанс. Если база данных не указана, то необходимо подключиться к существующей базе данных или создать новую. Если база данных была указана, `isql` запускает интерактивный сеанс, подключаясь к указанной базе данных.

Если указаны параметры, `isql` запускается в интерактивном или не интерактивном режиме, в зависимости от параметров. Например, чтение входного файла и запись в выходной файл являются не интерактивными задачами, поэтому параметры `-input` или `-output` не запускают интерактивный сеанс. Дополнительные не интерактивные параметры включают `-a`, `-database`, `-extract` и `-x`, которые используются при извлечении операторов DDL.

Когда вы запускаете интерактивный сеанс `isql`, появляется следующее приглашение:

[listing]
----
SQL>
----

Вы должны завершить каждую команду символом-терминатором. Терминатором по умолчанию является точка с запятой (`;`). Вы можете изменить терминатор на любой символ или группу символов с помощью команды `SET TERMINATOR` или с помощью параметра командной строки `-terminator`. Если вы опустите терминатор, появится приглашение для продолжения ввода (`CON>`).

Ниже приведен самый простой способ запуска `isql`. После перехода в интерактивный режим вы должны начать с создания новой базы данных или подключения к ней. Сообщение, выданное `isql`, является подсказкой относительно того, что вы должны делать дальше.

[listing]
----
c:\Firebird\3.0>isql

Use CONNECT or CREATE DATABASE to specify a database
SQL> CONNECT "inet://localhost:3053/employee"
CON> user "SYSDBA" password 'masterkey';
Database: "inet://localhost:3053/employee", User: SYSDBA
SQL>
----

В следующем примере показано, как передать имя базы данных и учетные данные пользователя в командной строке.

[listing]
----
c:\Firebird\3.0>isql -user sysdba -password masterkey "inet://localhost:3053/employee"

Database: inet://localhost:3053/employee, User: SYSDBA
SQL>
----

В этом примере мы использовали псевдоним для базы данных `employee`. Этот пример предопределен в файле `databases.conf`, который обычно находится в каталоге, в котором установлен Firebird, но некоторые дистрибутивы Linux помещают его в `/etc/firebird/n.n`, где `n.n` -- версия сервера базы данных Firebird. Ниже приведена дополнительная информация о подключении к базам данных с использованием полных путей или псевдонимов.

[[fbadmgd-isql-switches]]
== Переключательи командной строки

Переключатели командной строки -- это аргументы, которые начинаются с символа минус/дефис (`-`). Ниже приведен пример того, что происходит, когда вы пытаетесь запустить `isql` с недопустимым переключателем -- он отображает список допустимых ключей с кратким описанием каждого из них.

[listing]
----
c:\Firebird\3.0>isql -help
Unknown switch: -help
usage:    isql [options] [<database>]
        -a(ll)                  extract metadata incl. legacy non-SQL tables
        -b(ail)                 bail on errors (set bail on)
        -c(ache) <num>          number of cache buffers
        -ch(arset) <charset>    connection charset (set names)
        -d(atabase) <database>  database name to put in script creation
        -e(cho)                 echo commands (set echo on)
        -ex(tract)              extract metadata
        -f(etch_password)       fetch password from file
        -i(nput) <file>         input file (set input)
        -m(erge)                merge standard error
        -m2                     merge diagnostic
        -n(oautocommit)         no autocommit DDL (set autoddl off)
        -nod(btriggers)         do not run database triggers
        -now(arnings)           do not show warnings
        -o(utput) <file>        output file (set output)
        -pag(elength) <size>    page length
        -p(assword) <password>  connection password
        -q(uiet)                do not show the message "Use CONNECT..."
        -r(ole) <role>          role name
        -r2 <role>              role (uses quoted identifier)
        -s(qldialect) <dialect> SQL dialect (set sql dialect)
        -t(erminator) <term>    command terminator (set term)
        -tr(usted)              use trusted authentication
        -u(ser) <user>          user name
        -x                      extract metadata
        -z                      show program and server version
----

[NOTE]
====
Требуются только начальные символы в опции. Вы можете ввести любую часть текста, заключенную в скобки, включая полное имя опции. Например, указание `-n`, `-no` или `-noauto` имеет тот же эффект.
====

.Переключатели командной строки
[[fbadmgd-isql-switches-tbl]]
[cols="<1,<3", options="header",stripes="none"]
|===
^|Опция
^|Описание

|-a(ll)
|Извлечение всех метаданных, включая не-SQL объекты. Используется совместно с командой `extract`.

|-b(ail)
|Этот переключатель указывает утилите передать ошибку в ОС, но только в пакетном режиме (`SET BAIL ON`). Он был добавлен, чтобы предотвратить выполнение сценариев `isql` после обнаружения ошибки. Дальнейшие операторы не будут выполняться, и `isql` вернет код ошибки в ОС.

Пользователям по-прежнему необходимо использовать переключатель `-e(cho)` для вывода команд в выходной файл, чтобы выделить точный оператор, вызвавший ошибку.

Когда сервер предоставляет информацию о строках и столбцах, пользователи могут найти точную строку в DML скрипте, вызвавшую проблему. Когда сервер указывает только ошибку, то пользователи могут увидеть только первую строку оператора, вызвавшего сбой по отношению ко сему сценарию.

Эта функция также поддерживается во вложенных скриптах. Например, сценарий A включает в себя сценарий B, а сценарий B вызывает ошибку, номер строки связан со сценарием B. Когда сценарий B полностью прочитан, `isql` продолжает считать строки, относящиеся к сценарию A, поскольку каждый файл получает отдельный счетчик строк. Сценарий A включает сценарий B, когда сценарий A использует команду `INPUT` для загрузки сценария B.

|-c(ache) _n_
|Задаёт количество страниц, которые будут кэшированы при соединении с БД.

|-ch(arset) _charset_
|Задаёт кодировку для текущего соединения. Это же можно сделать с использовании команды `SET NAMES`.

|-d(atabase) _database_
a|Используется совместно с переключателем `-x` или `-ex`. Изменяет оператор `CREATE DATABASE`, который извлекается в файл:

* Без переключателя `-d` оператор `CREATE DATABASE` извлекается в скрипт как комментарий в стиле C, и использует имя базы данных указанное в командной строке `isql`;
* С переключателем `-d` оператор `CREATE DATABASE` извлекается не закомментированным, и подставляет имя базы данных указанное в переключателе.

|-e(cho)
|Включает дублирование команд на указанное устройство вывода (монитор, в файл, и т.д.). Это можно сделать и с использованием команды `SET ECHO ON`.

|-ex(tract)
|Извлечение метаданных из базы данных. Его можно использовать вместе с ключом `-o(utput)` для извлечения информации в указанный выходной файл.

|-f(etch_password) _pwd_file_
|Извлечение пароля из файла.

|-i(nput) _file_
|Задаёт файл с SQL-скриптом для выполнения. Файлы скриптов могут содержать команду `SET INPUT` для включения других файлов.

|-m(erge_stderr)
|Перенаправление ошибок (stderr) на поток стандартного вывода. Ключ командной строки `-m(erge)` может использоваться для включения сообщений об ошибках в выходные файлы.

|-m2
|Отправлять информацию о статистике и планах в выходной файл, который указан в переключателе `-o(utput)`. Ключ командной строки `-m2` гарантирует, что статистика и информация о плане, полученные из команд `SET STATS`, `SET PLAN` и `SET PLANONLY`, также отправляются в выходной файл, а не просто возвращаются в консоль.

|-n(oautocommit)
|Отключить автоматическое подтверждение DDL-операций. По умолчанию операторы DDL фиксируются автоматически в отдельной транзакции. Может быть изменено командой `SET AUTODDL OFF`.

|-nod(btriggers)
|Не запускать триггеры базы данных.

|-now(arnings)
|Не показывать предупреждения.

|-o(utput) _file_
|Задаёт файл для вывода результата выполнения запросов. Без аргументов перенаправляет вывод на стандартное устройство вывода (монитор). Может быть изменён так же командой `SET OUTPUT`.

|-pag(elength) _size_
|Размер печатной страницы. Печатает заголовки столбцов каждые _size_ строк вместо значения по умолчанию 20.

|-p(assword) _password_
|Пароль пользователя при подключении к базе данных.

|-q(uiet)
|Не показывать сообщение "`Use CONNECT...`".

|-r(ole) _role_
|Задаёт имя роли при подключении к базе данных.

|-r2 _role_
|Задаёт имя роли (с использованием квотированных идентификаторов). Этот переключатель можно использовать для указания имени роли с учетом регистра.

По умолчанию для передачи роли используется переключатель `-r(ole)`. В этом случае роль, представленная в командной строке, пишется в верхнем регистре. Если используется переключатель `-r2`, то роль передаются в движок в точности так, как это указано в командной строке.

|-s(qldialect) _dialect_
|Устанавливает SQL диалект к котором интерпретируются последующие команды до конца сеанса или до тех пор, пока диалект не будет изменён с помощью инструкции `SET SQL DIALECT`.

|-t(erminator) _term_
|Изменяет символ конца оператора (терминатора) с точки с запятой "`;`" по умолчанию на `_term_`, где `_term_` -- любой символ или последовательность символов. Тоже самое можно сделать использую команду `SET TERM`.

|-tr(usted)
|Использовать доверительную аутентификацию.

|-u(ser) _user_
|Имя пользователя для подключения к базе данных.

|-x
|Извлечение метаданных из базы данных. Его можно использовать вместе с ключом `-o(utput)` для извлечения информации в указанный выходной файл.

|-z
|Показать версии утилиты и сервера.

|===

=== Примеры использования переключателей в isql

.Выполнение скрипта создания базы данных
[example]
====
[source,bash]
----
isql -input createdb.sql
----
====

.Запуск интерактивного сеанса с подключением к удалённой базе данных
[example]
====
В следующем примере начинается интерактивное соединение с удаленной базой данных. Удаленный сервер jupiter, принимает указанную комбинацию пользователя и пароля с привилегиями, назначенными роли `STAFF`:

[source,bash]
----
isql -user sales -password mycode -role staff 'jupiter:/usr/customer.fdb'
----
====

.Запуск интерактивного сеанса без подключения к базе данных
[example]
====
Следующий пример запускает интерактивный сеанс, но не подключается к базе данных. Все введенные команды `isql` выводятся на печать, а результаты запроса печатают заголовки столбцов каждые 30 строк. Соединение с базой данных по умолчанию использует кодировку `UTF8`.

[source,bash]
----
isql -ch utf8 -echo -page 30
----
====

[[fbadmgd-isql-start-session]]
== Начало сессии isql

Чтобы начать сеанс `isql`, введите параметры командной строки и имя базы данных в оболочке Linux/Unix или командной консоли Windows. Например:

[source,bash]
----
isql -user SYSDBA -password masterkey inet4://localhost/mydatabase
----

При подключении к локальной базе данных в embedded варианте достаточно указать только имя пользователя (пароль будет проигнорирован):

[source,bash]
----
isql -user SYSDBA employee.db
----

В Windows вы можете использовать доверительную аутентификацию, при условии что она настроена в `firebird.conf` или `databases.conf`:

[source,bash]
----
isql -trusted inet4://localhost/mydatabase
----

Если параметры `&lt;options&gt;` не указаны, `isql` запускает интерактивный сеанс. Если база данных не указана, то необходимо подключиться к существующей базе данных или создать новую. Если база данных была указана, `isql` запускает интерактивный сеанс, подключаясь к указанной базе данных.

Чтение входного файла и запись в выходной файл не считаются интерактивными задачами, поэтому параметры командной строки `-input` или `-output` не инициируют интерактивный сеанс. Опции, используемые для извлечения операторов DDL, такие как `-a` и `-x`, также инициируют только неинтерактивный сеанс.

Утилита `isql` может быть запущена с локального или удаленного клиента:

* При подключении с использованием локального клиента вы можете установить переменные среды `ISC_USER` и `ISC_PASSWORD`.
* При подключении с удаленного клиента вам потребуется указать действительные имя и пароль.

[[fbadmgd-isql-end-session]]
== Завершение сессии isql

(((ISQL, QUIT)))(((ISQL, EXIT)))
Существует два способа выхода из isql:

* Если вы хотите откатить всю неподтвержденную работу и выйти из isql, введите в командной строке следующую команду `QUIT`;
* Если вы хотите зафиксировать всю свою работу перед выходом из isql, введите следующую команду `EXIT`.

[[fbadmgd-isql-help]]
== Получение справки

(((ISQL, HELP)))
Утилита `isql` поддерживает команду `HELP`. Она дает краткую информацию о большинстве доступных команд. Команда `HELP` также позволяет перейти к более подробной информации. Чтобы активировать справочную систему, просто введите `HELP` в командной строке, как показано ниже:

[listing]
----
SQL> HELP;

Frontend commands:
BLOBDUMP <blobid> <file>   -- dump BLOB to a file
BLOBVIEW <blobid>          -- view BLOB in text editor
EDIT     [<filename>]      -- edit SQL script file and execute
EDIT                       -- edit current command buffer and execute
HELP                       -- display this menu
INput    <filename>        -- take input from the named SQL file
OUTput   [<filename>]      -- write output to named file
OUTput                     -- return output to stdout
SET      <option>          -- (Use HELP SET for complete list)
SHELL    <command>         -- execute Operating System command in sub-shell
SHOW     <object> [<name>] -- display system information
    <object> = CHECK, COLLATION, DATABASE, DOMAIN, EXCEPTION, FILTER, FUNCTION,
               GENERATOR, GRANT, INDEX, PACKAGE, PROCEDURE, ROLE, SQL DIALECT,
               SYSTEM, TABLE, TRIGGER, VERSION, USERS, VIEW
EXIT                       -- exit and commit changes
QUIT                       -- exit and roll back changes

All commands may be abbreviated to letters in CAPitals
----

(((ISQL, HELP SET)))
Большинство из этих команд не имеют дальнейших уровней детализации, в то время как команда `SET` имеет. Чтобы углубиться в эти дополнительные уровни, выполните следующие действия:

[listing]
----
HELP SET;

Set commands:
    SET                    -- display current SET options
    SET AUTOddl            -- toggle autocommit of DDL statements
    SET BAIL               -- toggle bailing out on errors in non-interactive mode
    SET BLOB [ALL|<n>]     -- display BLOBS of subtype <n> or ALL
    SET BLOB               -- turn off BLOB display
    SET COUNT              -- toggle count of selected rows on/off
    SET MAXROWS [<n>]      -- limit select stmt to <n> rows, zero is no limit
    SET ECHO               -- toggle command echo on/off
    SET EXPLAIN            -- toggle display of query access plan in the explained form
    SET HEADING            -- toggle display of query column titles
    SET LIST               -- toggle column or table display format
    SET NAMES <csname>     -- set name of runtime character set
    SET PLAN               -- toggle display of query access plan
    SET PLANONLY           -- toggle display of query plan without executing
    SET SQL DIALECT <n>    -- set sql dialect to <n>
    SET STATs              -- toggle display of performance statistics
    SET TIME               -- toggle display of timestamp with DATE values
    SET TERM <string>      -- change statement terminator string
    SET WIDTH <col> [<n>]  -- set/unset print width to <n> for column <col>

All commands may be abbreviated to letters in CAPitals
----

Если вы попытаетесь углубиться в какую-либо другую команду, эффект будет точно таким же, как при выполнении только команды `HELP`.

[NOTE]
====
Команда `HELP SET` даёт справку только по собственным командам `isql`. Для управляющих SQL операторов, таких как `SET TRANSACTION` или `SET ROLE` подсказка не будет выведена.
====

[[fbadmgd-isql-connect]]
== Соединение с базой данных

(((ISQL, CONNECT)))
Если при запуске `isql` вы не указали спецификацию для подключения к базе данных, то будет выдана подсказка о том что необходимо соединиться с базой данных с помощью оператора `CONNECT` или создать новую базу данных с помощью оператора `CREATE DATABASE`.

Оператор `CONNECT` не является частью DSQL и доступен только внутри ISQL, а потому не описан в "`Руководство по языку SQL Firebird`". Рассмотрим его синтаксис.

.Синтаксис
[listing,subs="+quotes,attributes"]
----
CONNECT <database>
  [USER _username_ [PASSWORD _password_]]
  [CACHE _cache_size_]
  [ROLE _rolename_]

<database> ::= [<server spec>] {_db_filename_ | _db_alias_}

<server spec> ::=
    _host_[\{_port_ | _service_}]:
  | {backslash}{backslash}__host__[@{_port_ | _service_}]\
  | <protocol>://[_host_[:{_port_ | _service_}]/]

<protocol> ::= inet | inet4 | inet6 | wnet | xnet
----

.Параметры оператора `CONNECT`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|db_filename
|Полный путь и имя файла, включая расширение. Имя файла должно быть задано в соответствии со спецификой используемой платформы.

|db_alias
|Псевдоним (alias) базы данных, присутствующий в файле `databases.conf`.

|username
|Имя пользователя для соединения с базой данных. Может быть заключено в одинарные или двойные кавычки. Если имя пользователя заключено в двойные кавычки, то оно чувствительно к регистру.

|password
|Имя пользователя для соединения с базой данных. Может быть заключено в одинарные или двойные кавычки. Если имя пользователя заключено в двойные кавычки, то оно чувствительно к регистру.

|cache_size
|Размер страничного кеша.

|rolename
|Имя роли для соединения с базой данных. Может быть заключено в одинарные или двойные кавычки. Если имя роли заключено в двойные кавычки, то оно чувствительно к регистру.

|server spec
|Спецификация удалённого сервера. Включает в себя имя сервера и протокол.

|host
|Имя сервера или IP адрес, на котором расположена база данных.

|port
|Номер порта, который слушает удалённый сервер (параметр `RemoteServicePort` файла `firebird.conf`.

|service
|Имя сервиса. Должно совпадать со значением параметра `RemoteServiceName` файла `firebird.conf`.

|protocol
|Наименование протокола.

|===

База данных может состоять из одного или нескольких файлов. Первый, основной, файл называется первичным, остальные файлы -- вторичными. При подключении к базе данных необходимо указывать только путь до первичного файла базы данных.

Спецификация первичного файла -- имя файла базы данных и его расширение с указанием к нему полного пути в соответствии с правилами используемой операционной системы.

[[fbadmgd-isql-connect-aliasedb]]
=== Использование псевдонимов БД

Вместо полного пути к первичному файлу базы можно использовать псевдонимы (aliases). Псевдонимы описываются в файле `databases.conf` в формате:

[listing,subs="+quotes,attributes"]
----
_alias_ = _filepath_
----

[NOTE]
====
Помимо указания псевдонимов для базы данных в этом файле можно задать параметры уровня базы данных для каждой описываемой базы данных. Эти параметры задаются в фигурных скобках сразу после объявления псевдонима. Подробнее читайте <<fbadmgd-config-perdb>>.
====

[[fbadmgd-isql-connect-remotely]]
=== Соединение с БД на удалённом сервере

При соединении с базой данных на удалённом сервере необходимо указать спецификацию удалённого сервера. Спецификация удалённого сервера зависит от используемого протокола.

Если вы при соединении с базой данных используете протокол TCP/IP, то строка соединения должна выглядеть следующим образом:

[listing,subs="+quotes,attributes"]
----
_host_[/{_port_ | _service_}]:{_filepath_ | _db_alias_}
----

Если вы при соединении с базой данных используете протокол под названием именованные каналы (Name Pipes), то строка соединения должна выглядеть следующим образом.

[listing,subs="+quotes,attributes"]
----
{backslash}{backslash}__host__[@{_port_ | _service_}]\{_filepath_ | _db_alias_}
----

Существует также унифицированный URL-подобный синтаксис спецификации удалённого сервера. В этом синтаксисе первым параметром указывается наименование протокола, далее указывается имя сервера или IP адрес, номер порта и путь к первичному файлу базы данных или псевдоним. В качестве протокола можно указать следующие значения:

* `inet` -- TCP/IP (сначала пробует подключится по протоколу TCP/IP v6, если не получилось, то TCP/IP v4);
* `inet4` -- TCP/IP v4 (начиная с 3.0.1);
* `inet6` -- TCP/IP v6 (начиная с 3.0.1);
* `wnet` -- NetBEUI или протокол именованных каналов;
* `xnet` -- локальный протокол.

[listing,subs="+quotes,attributes"]
----
<protocol>://[_host_[:{_port_ | _service_}]/]{_filepath_ | _db_alias_}
----

[[fbadmgd-isql-connect-user]]
=== Имя пользователя, пароль и роль

Необязательные предложения `USER` и `PASSWORD` задают, соответственно, имя и пароль пользователя присутствующего в базе данных безопасности (`{secdb}` или той, что указана в параметре `SecurityDatabase`). Пользователя и пароль можно не указывать, если установлены переменные окружения `ISC_USER` и `ISC_PASSWORD`. Их также можно не указывать при использовании доверительной аутентификации.

Если подключение происходит к embedded версии сервера, то достаточно указать только имя пользователя (проверка пароля не производится).

Необязательное предложение `ROLE` задаёт имя роли, права которой будут учитываться при подключении базы данных. Роль должна быть назначена пользователю в соответствующей базе данных безопасности.

[[fbadmgd-isql-connect-charset]]
=== Набор символов

Команда `CONNECT` не позволяет указать набор символов для подключения, однако вы можете это сделать с помощью команды `SET NAMES`, которую необходимо ввести до использования `CONNECT`.

[[fbadmgd-isql-connect-examples]]
=== Примеры

.Подключение к локальной (embedded) базе данных
[example]
====
В следующем примере происходит подключение к базе данных в embedded варианте с использованием имени пользователя из переменной среды `ISC_USER`:

[source,sql]
----
CONNECT "C:\DATABASES\FIREBIRD\MY_EMPLOYEE.FDB";
----

В Linux это будет выглядеть следующим образом:

[source,sql]
----
CONNECT "/databases/firebird/MY_EMPLOYEE.FDB";
----

При использовании псевдонимов, настроенных в `databases.conf`:

[source,sql]
----
CONNECT MY_EMPLOYEE;
----

Если переменная окружения `ISC_USER` не задана, или требуется указать другого пользователя, то необходимо использовать предложение `USER`:

[source,sql]
----
CONNECT MY_EMPLOYEE USER SYSDBA;
----
====

.Подключение к локальной (не embedded) базе данных
[example]
====
На Windows можно использовать локальный протокол XNET:

[source,sql]
----
CONNECT xnet://MY_EMPLOYEE USER SYSDBA PASSWORD 'masterkey';
----

Во всех операционных системах через TCP:

[source,sql]
----
CONNECT inet://localhost/MY_EMPLOYEE USER SYSDBA PASSWORD 'masterkey';
----
====

.Подключение к удалённой базе данных с ролью RDB$ADMIN
[example]
====
[source,sql]
----
CONNECT inet://dbserver/MY_EMPLOYEE USER BOB PASSWORD 'W45xs' ROLE RDB$ADMIN;
----
====

.Подключение к удалённой базе данных с набором символов WIN1251
[example]
====
[source,sql]
----
SET NAMES WIN1251;
CONNECT inet://dbserver/MY_EMPLOYEE USER BOB PASSWORD 'W45xs';
----
====

[[fbadmgd-isql-create-db]]
== Создание базы данных

Если при запуске `isql` вы не указали спецификацию для подключения к базе данных, то будет выдана подсказка о том что необходимо соединиться с базой данных с помощью оператора `CONNECT` или создать новую базу данных с помощью оператора `CREATE DATABASE`.

Оператор `CREATE DATABASE` является частью DSQL и подробно описан в "`Руководство по языку SQL Firebird`", поэтому здесь будет приведён только краткий синтаксис и примеры использования.

.Синтаксис
[listing,subs="+quotes,attributes"]
----
CREATE DATABASE <filespec>
  [<db_initial_option> [<db_initial_option> ...]]
  [<db_config_option> [<db_config_option> ...]]

<db_initial_option> ::=
    USER _username_
  | PASSWORD '_password_'
  | ROLE _rolename_
  | PAGE_SIZE [=] _size_
  | SET NAMES '_charset_'

<db_config_option> ::=
    DEFAULT CHARACTER SET _default_charset_
      [COLLATION _collation_]
  | DIFFERENCE FILE '_diff_file_'


<filespec> ::= '[<server_spec>]{_filepath_ | _db_alias_}'

<server_spec> ::=
    _host_[/{_port_ | _service_}]:
  | {backslash}{backslash}__host__[@{_port_ | _service_}]\
  | <protocol>://[_host_[:{_port_ | _service_}]/]

<protocol> ::= inet | inet4 | inet6 | xnet | wnet
----

В следующем примере будет создана база данных `monkey.fdb` и сохранена в директории `test` на диске `С`.

[source,sql]
----
CREATE DATABASE 'C:\test\monkey.fdb' page_size 8192
user 'SYSDBA' password 'masterkey';
----

[NOTE]
====
* Путь к базе данных и пароль обязательно должны быть заключены в одинарные или двойные кавычки. Для имени пользователя, пароля и набора символов кавычки необязательны. При использовании двойных кавычек буду использованы правила 3-диалекта, т.е. имя пользователя, роли и набора символов будут чувствительны к регистру символов.
* Поскольку база данных создаётся в режиме embedded сервера, то файл базы данных будет создан с именем входа в систему в качестве владельца. Это может вызвать проблемы с доступом к файлу базы данных для других пользователей, особенно в Linux, которые могут захотеть подключится позднее. Если база данных создаётся с использованием сетевого или локального (Windows) протокола, то файл базы данных будет создан от имени пользователя службы (в Linux это пользователь firebird)
====

В данном случае база данных будет создана с использованием embedded версии Firebird. Для использования сетевых протоколов вы можете использовать префиксы протоколов или другие правила аналогичные правила для оператора `CONNECT`.

.Создание базы данных на удалённом сервере
[example]
====
Создание базы данных на удалённом сервере baseserver расположенном по пути, на который ссылается псевдоним test, описанный в файле `databases.conf`. Используется протокол TCP. Владельцем базы данных будет пользователь wizard.

[source,sql]
----
CREATE DATABASE 'baseserver:test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

То же самое с использованием унифицированного URL-подобного синтаксиса задания спецификации удалённого сервера.

[source,sql]
----
CREATE DATABASE 'inet://baseserver:3050/test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

или

[source,sql]
----
CREATE DATABASE 'inet://baseserver:gds_db/test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

Начиная с Firebird 3.0.1 можно указать какой именно из протоколов IP v4 или IP v6 вы хотите использовать.

[source,sql]
----
CREATE DATABASE 'inet4://baseserver/test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

или

[source,sql]
----
CREATE DATABASE 'inet6://baseserver/test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

Создание базы данных с указанием IP адреса (IPv4) вместо указания имени сервера.

[source,sql]
----
CREATE DATABASE '127:0:0:1:test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

Создание базы данных с указанием IP адреса (IPv6) вместо указания имени сервера.

[source,sql]
----
CREATE DATABASE '[::1]:test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----
====

[NOTE]
====
В отличие от оператора `CONNECT` в операторе `CREATE DATABASE` вы сразу можете указать набор символов, который будет использован в подключении после выполнения оператора `CREATE DATABASE` с помощью предложения `SET NAMES`.
====

После создания базы данных вы можете выполнять к ней запросы в интерактивном режиме.

[listing]
----
SQL>SELECT RDB$RELATION_ID FROM RDB$DATABASE;

RDB$RELATION_ID
===============
128

SQL> commit;
----

Чтобы вернуться в командную строку введите команду `EXIT` или `QUIT`.

[NOTE]
====
Вышеуказанная методика, как показано, работает, но в идеале базы данных и объекты метаданных должны создаваться и поддерживаться с использованием сценариев определения данных.
====

[[fbadmgd-isql-env]]
== Установка переменных окружения ISC_USER и ISC_PASSWORD

Переменная среды -- это именованный объект, который содержит информацию, используемую одним или несколькими приложениями. Они глобальны для своих конкретных операционных систем. Сервер Firebird распознает и использует определенные переменные среды, настроенные в Windows, Linux и других системах Unix.

Переменные среды `ISC_USER` и `ISC_PASSWORD` в Firebird предназначены для предоставления SYSDBA доступа к базе данных из служебных программ командной строки и клиентских приложений всем, кто имеет доступ к хост-машине.

[CAUTION]
====
При запуске таких утилит командной строки, как `isql`, `gbak`, `gstat` и `gfix`, Firebird будет искать, установлены ли переменные среды `ISC_USER` и `ISC_PASSWORD`. Если вы не предоставите имя пользователя и пароль при локальном подключении к базе данных, Firebird позволит вам войти в систему, если найдет эти переменные.

Из соображений безопасности не рекомендуется указывать имя пользователя и пароль `SYSDBA` с использованием этих двух переменных среды, особенно на незащищенном компьютере.
====

Переменные среды `ISC_USER` и `ISC_PASSWORD` могут быть установлены для локального запуска `isql`. Чтобы установить переменные среды:

* В Windows это делается в menu:Панели управления[Система > Дополнительно > Переменные среды]. Любые изменения, сделанные здесь, будут постоянными. Вы также можете определить эти переменные в командном окне до запуска любой из утилит Firebird, например `isql`. Например:
+
[listing]
----
C:\> set ISC_USER=sysdba
C:\> set ISC_PASSWORD=secret
C:\> isql my_employee

SQL>
----

* На платформах Linux и Unix это зависит от типа используемой оболочки и от конфигурации настольного компьютера. Обратитесь к документации вашей операционной системы, чтобы установить переменные среды. Для оболочки bash этот процесс показан в следующем примере:
+
[listing]
----
cosmos> export ISC_USER=sysdba
cosmos> export ISC_PASSWORD=secret
cosmos> /opt/firebird/bin/isql my_employee

SQL>
----

[[fbadmgd-isql-sql_dialect]]
== SQL диалект

Firebird поддерживает три диалекта SQL на каждом клиенте и сервере базы данных. Эти диалекты SQL различаются в контексте формата даты и времени и точности числового типа данных. Диалекты служат для инструктирования сервера Firebird о том, как обрабатывать функции, реализованные в устаревших базах данных Borland Interbase, более ранних, чем версия 6.0. Диалекты устанавливаются во время выполнения и могут быть изменены для клиента во время подключения или с помощью команды `SET SQL DIALECT`.

* Диалект 1 предназначен исключительно для обеспечения обратной совместимости с устаревшими базами данных из очень старых версий InterBase, v.5 и ниже. Базы данных Dialect 1 сохраняют определенные языковые особенности, которые отличаются от Dialect 3, используемого по умолчанию для баз данных Firebird.
** Информация о дате и времени хранится в типе данных `DATE`. Имеется тип данных `TIMESTAMP`, который идентичен `DATE`.
** Двойные кавычки могут использоваться как альтернатива апострофам для разделения строковых данных. Это противоречит стандарту SQL - двойные кавычки зарезервированы для особых синтаксических целей как в стандартном SQL, так и в диалекте 3. Поэтому строки с двойными кавычками следует избегать.
** Точность типов данных `NUMERIC` и `DECIMAL` меньше, чем в 3-м диалекте и в случае, если значение точности более 9, Firebird хранит такие значения как длинные значения с плавающей точкой.
** `BIGINT` не является доступным типом данных.
** Идентификаторы нечувствительны к регистру и всегда должны соответствовать правилам для обычных идентификаторов.
** Хотя значения генератора хранятся как 64-битные целые числа, запрос клиента Dialect 1, например, `SELECT GEN_ID (MyGen, 1)`, вернет значение генератора, усеченное до 32 бит.

* Диалект 2 доступен только в клиентском соединении к Firebird и не может быть применён к базе данных. Он предназначен для того, чтобы помочь в отладке в случае возможных проблем с целостностью данных при проведении миграции с диалекта 1 на 3.

* В базах данных Диалекта 3:
** Числа с типами данных `DECIMAL` и `NUMERIC` хранятся как длинные значения с фиксированной точкой (масштабируемые целые числа) в случае если точность числа больше 9.
** Тип данных `TIME` доступен и используется для хранения значения только времени.
** Тип данных `DATE` хранит информацию только о дате.
** Тип данных `BIGINT` доступен в качестве целого 64-х битного типа данных.
** Двойные кавычки могут использоваться, но только для идентификаторов, которые являются зависимыми от регистра, а не для строковых данных.
** Все строки должны быть разделены одинарными кавычками (апострофам).
** Значения генераторов возвращаются как 64-битное целое.

[IMPORTANT]
====
Для вновь разрабатываемых баз данных и приложений настоятельно рекомендуется использовать 3-й диалект. Диалект при соединении с базой данных должен быть таким же, как и базы данных. Исключением является случай миграции с 1-го в 3-й диалект, когда в строке соединения с базой данных используется 2-й диалект.
====

При подключении к базе данных с использованием `isql` утилита использует диалект базы данных, если не указано иное. Диалекты не могут быть установлены в качестве параметра оператора `CREATE DATABASE`. Таким образом, при создании базы данных с использованием `isql` база данных будет на диалекте, который является текущим в `isql` во время выполнения оператора `CREATE DATABASE`. Вы можете установить диалект с помощью утилиты `isql` двумя способами:

* При старте `isql` укажите диалект с использованием переключателя `-sql_dialect`:
+
[listing]
----
isql -sql_dialect 3
----

* Внутри sql скрипта или в `isql` сессии с помощью команды `SET SQL DIALECT`:
+
[listing]
----
SQL> SET SQL DIALECT 3;
----

[[fbadmgd-isql-terminator]]
== Символ терминатора

Символом терминатором по умолчанию для базы данных Firebird является точка с запятой "`;`". Операторы будут только выполнены если они заканчиваются точкой с запятой. Однако вы можете использовать `isql` для изменения символа на любой печатный символ или несколько символов из первых 127 символов подмножества ASCII с помощью команды `SET TERM`.

[NOTE]
====
Терминатор по умолчанию может быть изменен во всех случаях, за исключением Procedural SQL или PSQL. PSQL не принимает никаких терминаторов, кроме точки с запятой.
====

Для изменения символа терминатора на тильду "`~`" введите следующую команду:

[listing]
----
SET TERM ~;
----

Для возврата терминатора, вы должны использовать текущий терминатор! Изменение терминатора полезно, если вы хотите ввести функцию PSQL, как показано в следующем примере. Поскольку PSQL будет принимать только точку с запятой в качестве терминатора, `isql` должен знать, какая точка с запятой используется для кода PSQL, а какая используется для завершения вводимых команд SQL.

[listing]
----
SQL> set term ~ ;

SQL> create procedure test_proc (iInput integer = 666)
CON> returns (oOutput integer)
CON> as
CON> begin
CON>   oOutput = iInput;
CON>   suspend;
CON> end~

SQL> set term ; ~

SQL> commit;

SQL> select * from test_proc;

     OOUTPUT
============
         666
----

Вы можете видеть, что внутри кода самой процедуры терминатором является точка с запятой. Однако вне фактического кода процедуры терминатором является тильда (~). `isql` обрабатывает одну команду `CREATE PROCEDURE`, но внутри этого одного оператора SQL есть несколько встроенных операторов PSQL:

[source,sql]
----
oOutput = iInput;
suspend;
----

Они имеют точку с запятой, как того требует PSQL. Конец команды `CREATE PROCEDURE` обозначается использованием тильды в качестве терминатора:

[listing]
----
end~
----

При желании вы можете просто изменить терминатор, потому что вы предпочитаете что-то другое, а не точку с запятой.

[listing]
----
SQL> -- Change terminator from ; to +
SQL> set term + ;

SQL> select count(*) from employee+

       COUNT
============
          42

SQL> -- Change terminator from + to 'fred'
SQL> set term fred +

SQL> select count(*) from employee fred

       COUNT
============
          42

SQL> -- Change back from 'fred' to ;
SQL> set term ; fred
----

Однако вы должны быть осторожны, чтобы не выбрать символ-терминатор, который приведет к сбою операторов SQL из-за того, что терминатор используется в какой-то момент в операторе SQL.

[listing]
----
SQL> select 600+60+6 as The_Beast from rdb$database;

THE_BEAST
=====================
666

SQL> set term + ;
SQL> select 600+60+6 as The_Beast from rdb$database+

Statement failed, SQLSTATE = 42000
Dynamic SQL Error
-SQL error code = -104
-Unexpected end of command - line 1, column 8

SQL> set term ; +
----

Присутствие терминатора в выражении вызвало ошибку "`Unexpected end of command`". Анализатор SQL в ядре базы данных Firebird определил, что `select 600` не является допустимым оператором. По этой причине лучше всегда выбирать символ или символы, которые не будут путать синтаксический анализатор.

[listing]
----
SQL> set term !! ;

SQL> select 600+60+6 as The_Beast from rdb$database!!

THE_BEAST
=====================
666
----

[[fbadmgd-isql-prompts]]
== Подсказки ISQL

[float]
=== Подсказка SQL

Как показано выше, обычная подсказка `isql` для ввода -- это подсказка `SQL>`. Это указывает на то, что предыдущая команда была выполнена, и теперь `isql` ожидает обработки новой команды.

[float]
=== Подсказка CON

Подсказка `CON>` отображается, если пользователь нажимает клавишу btn:[ENTER] без завершения оператора SQL с помощью терминатора. Например:

[listing]
----
SQL> HELP
CON>
----

Всякий раз, когда вы видите приглашение `CON>`, вы можете либо продолжить ввод оставшейся части команды, либо ввести терминатор для завершения команды. В последнем случае команда будет выполнена после нажатия клавиши btn:[ENTER].

[[fbadmgd-isql-errors]]
== Обработка ошибок и поддержка исключений

Обработка исключений -- это программная конструкция, предназначенная для обработки ситуаций, которые нарушает нормальное выполнение программы. Это так называемые ошибки. Исключением являются именованное сообщение об ошибке, определяемые пользователем, написанные специально для базы данных и сохраненные в этой базе данных для использования в хранимых процедурах, функциях, пакетах, анонимных блоках и триггерах.

Например, если в триггере обнаруживается, что значение для таблицы неверно, то возникает исключение. Это приводит к откату всей транзакции, которую клиентское приложение пытается зафиксировать. Исключения могут совместно использоваться различными модулями приложения и даже различными приложениями, совместно использующими базу данных. Они предоставляют простой способ стандартизировать обработку заранее запрограммированных ошибок ввода.

Исключения составляют объекты базы данных, такие как таблицы, представления и домены, и являются частью метаданных базы данных. Их можно создавать, изменять и удалять, как и все другие объекты Firebird, используя `isql`.

В `isql` сообщения об ошибках содержат переменную SQLSTATE и статус вектор Firebird. Расшифровку кодов ошибок SQLSTATE вы можете найти в "`Руководстве по языку SQL СУБД Firebird`".

.Сообщение об ошибке в isql
[example]
====
[listing]
----
SQL> select 1/0 from rdb$database;

               DIVIDE
=====================
Statement failed, SQLSTATE = 22012
arithmetic exception, numeric overflow, or string truncation
-Integer divide by zero.  The code attempted to divide an integer value by an
integer divisor of zero.
----
====

[[fbadmgd-isql-transactions]]
== Обработка транзакций

В `isql` транзакция начинается сразу после запуска утилиты. Транзакция начинается в изоляции `SNAPSHOT` с разрешением блокировки в режиме `WAIT`. Поскольку утилита Firebird `isql` принимает DDL, DML и другие команды, транзакции обрабатываются соответствующим образом следующими способами:

* Операторы DDL фиксируются автоматически в двух случаях:
** Когда операторы `COMMIT` включен в скрипт.
** Когда включена автоматическая фиксация транзакций для DDL операторов (режим по умолчанию). В этом случае выполнение каждого DDL оператора транзакция автоматически подтверждается после ввода каждого оператора DDL, и стартует новая транзакция. Чтобы отключить режим автоматической фиксации, выполните инструкцию `SET AUTODDL OFF`. Для возврата в режим автоматической фиксации для DDL операторов выполните инструкцию `SET AUTODDL ON`.

* Операторы DML для выборки или изменения данных стартуют новую транзакцию с уровнем изоляции `SNAPSHOT`, если она не была начата ранее. Такая транзакция будет активной до тех пор, пока не будет вручную подтверждена оператором `COMMIT` или отменена оператором `ROLLBACK`.

* Вы можете использовать различные команды `SHOW` в `isql` для запроса метаданных базы данных. При этом ISQL запускает транзакцию с уровнем изоляции `READ COMMITTED`, что дает возможность видеть все изменения метаданных, подтвержденные другими пользователями.

Пользователи могут указать уровень изоляции и другие параметры для следующей транзакции с помощью оператора `SET TRANSACTION`. Он может быть выполнен только тогда, когда не активна другая транзакция. В противном случае будет задан вопрос: подтвердить или откатить активную транзакцию. Синтаксис оператора `SET TRANSACTION` подробно описан в "`Руководство по языку SQL Firebird`".

.Старт транзакции с режимом изолированности READ COMMITTED
[example]
====
[source,sql]
----
SET TRANSACTION WAIT READ COMMITTED LOCK TIMEOUT 10;
----
====

После выполнения `COMMIT` или `ROLLBACK`, новая DML команда стартует транзакцию с параметрами по умолчанию. Если необходимо, чтобы новая транзакция стартовала с параметрами, которые были указаны для предыдущей транзакции, то необходимо включить режим сохранения параметров транзакции с помощью команды `SET KEEP_TRAN_PARAMS` (может быть сокращена до `SET KEEP_TRAN`).

Если режим `KEEP_TRAN_PARAMS` установлен в:

* `ON`, то `isql` сохраняет текст следующего успешного оператора `SET TRANSACTION`, и новые транзакции DML запускаются с использованием того же SQL (вместо режима по умолчанию `CONCURRENCY WAIT`);
* `OFF`, то `isql` начинает новую транзакцию DML как обычно.

[NOTE]
====
Режим сохранения параметров транзакции появился в Firebird 3.0.6. Ранее невозможно было включить режим сохранения параметров транзакции. После команд `COMMIT` и `ROLLBACK` необходимо было каждый раз выполнять команду `SET TRANSACTION` с необходимыми параметрами.
====

См. также: <<fbadmgd-isql-commands_set-set_keep_tran>>.

[[fbadmgd-isql-script_handling]]
== Обработка скрипта

Пакет операторов DDL и/или DML в текстовом файле называется сценарием (скриптом). Скрипты могут быть использованы для создания и изменения объектов базы данных (метаданных). Они называются сценариями языка определения данных (DDL). Скрипты, которые манипулируют данными путем выбора, вставки, обновления, удаления или выполнения преобразований данных, называются скриптами языка манипулирования данными (DML).

Одной из наиболее важных задач, выполняемых `isql`, является обработка скриптов. Он может обрабатывать как сценарии DDL, так и сценарии DML. Большие файлы сценариев можно разбить на несколько файлов скриптов поменьше с помощью инструкции `INPUT`.

.Синтаксис
[listing,subs="+quotes,attributes"]
----
INPUT _file_name_
----

Данный оператор позволяет включить один файл сценария внутрь другого. Операторы сценариев выполняются в том порядке, в котором они появляются в файле сценариев. Настройка по умолчанию в `isql` для `AUTODDL` установлена на `ON`. Вы можете использовать команду `SET AUTODDL`, чтобы контролировать, где или когда будут подтверждены операторы изменения метаданных.

Параметр `AUTODDL` влияет только на операторы DDL. Он не фиксирует транзакцию для операторов DML. Если вы смешиваете инструкции DDL и DML в одном и том же интерактивном сеансе, то фиксации транзакций для DDL с помощью `AUTODDL` не фиксируют ваши транзакции для операторов DML. Например:

[listing]
----
SQL> set autoddl on;

SQL> insert into test(a) values (666);
SQL> commit;

SQL> select * from test;

A
============
666

SQL> insert into test(a) values (999);
SQL> select * from test;

A
============
666
999

SQL> create table another_test(b integer);
SQL> rollback;

SQL> select * from test;

A
============
666
----

Скрипты могут перенаправить свои выходные данные в файл журнала с помощью команды `OUTPUT _file_name_`. Это можно ввести непосредственно в приглашении `isql` или как часть самого файла скрипта.

[[fbadmgd-isql-commands]]
== ISQL команды

Команды `isql` влияют на работу самого `isql` и никак не влияют на базу данных или данные. Эти команды используются для отображения справки, чтения, записи и запуска сценариев, а также выполнение инструкций командной строки. Вы можете легко увидеть список доступных команд, набрав команду `HELP`, которая выдаст следующий вывод:

[listing]
----
SQL> HELP;
Frontend commands:
BLOBDUMP <blobid> <file>   -- dump BLOB to a file
BLOBVIEW <blobid>          -- view BLOB in text editor
EDIT     [<filename>]      -- edit SQL script file and execute
EDIT                       -- edit current command buffer and execute
HELP                       -- display this menu
INput    <filename>        -- take input from the named SQL file
OUTput   [<filename>]      -- write output to named file
OUTput                     -- return output to stdout
SET      <option>          -- (Use HELP SET for complete list)
SHELL    <command>         -- execute Operating System command in sub-shell
SHOW     <object> [<name>] -- display system information
    <object> = CHECK, COLLATION, DATABASE, DOMAIN, EXCEPTION, FILTER, FUNCTION,
               GENERATOR, GRANT, INDEX, PACKAGE, PROCEDURE, ROLE, SQL DIALECT,
               SYSTEM, TABLE, TRIGGER, VERSION, USERS, VIEW
EXIT                       -- exit and commit changes
QUIT                       -- exit and roll back changes

All commands may be abbreviated to letters in CAPitals
----

Теперь обсудим каждую из команд отдельно.

[NOTE]
====
Обратите внимание на последнюю строку вывода команды `help`. Это объясняет, что каждая из команд может быть сокращена до букв, отображаемых заглавными буквами. В следующем обсуждении дополнительные символы будут отображаться, как указано выше, строчными буквами. Например, команда ввода будет показана как INput, чтобы указать, что символы 'put' являются необязательными.
====

[[fbadmgd-isql-commands-blobdump]]
=== BLOBDUMP

.Назначение
Сохранение данных BLOB в указанном файле.
(((ISQL, BLOBDUMP)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
BLOBDUMP _blob_id_ _filename_
----

.Параметры команды `BLOBDUMP`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|blob_id
|Идентификатор BLOB.

|filename
|Имя файла в который необходимо сохранить BLOB.

|===

Эта команда позволяет вам скопировать BLOB из базы данных во внешний файл. Оператор `BLOBDUMP` требует два параметра, идентификатор BLOB-объекта и имя файла. Вам необходимо передать идентификатор BLOB-объекта в виде пары шестнадцатеричных чисел, разделенных двоеточием. Первое число -- это идентификатор таблицы, а второе -- последовательный номер в базе данных. Для получения этого идентификатора выполните любой оператор `SELECT`, который выбирает столбец BLOB. Вывод покажет шестнадцатеричный идентификатор BLOB выше или на месте столбца BLOB в зависимости от того, установлен ли `SET BLOBDISPLAY` в `ON` или `OFF`.

.Сохранение BLOB во внешний файл
[example]
====
[listing]
----
SQL> set blobdisplay off;

SQL> select proj_id, proj_desc
CON> from project
CON> where proj_id = 'MKTPR';

PROJ_ID PROJ_DESC
======= =================
MKTPR   85:10

SQL> blobdump 85:10 c:\project.jpg;
----
====

Идентификатор BLOB-объекта, необходимый в приведенном выше примере, равен `85:10`.

Смотри также: <<fbadmgd-isql-commands_set-set_blob>>, <<fbadmgd-isql-commands-blobview>>.

[[fbadmgd-isql-commands-blobview]]
=== BLOBVIEW

.Назначение
Отображение данных BLOB в текстовом редакторе по умолчанию.
(((ISQL, BLOBVIEW)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
BLOBVIEW _blob_id_
----

.Параметры команды `BLOBVIEW`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|blob_id
|Идентификатор BLOB.

|===

Команда `BLOBVIEW` отображает данные BLOB в текстовом редакторе по умолчанию.

.Открытие BLOB во внешнем текстовом редакторе
[example]
====
[listing]
----
SQL> set blobdisplay off;

SQL> select proj_id, proj_desc
CON> from project
CON> where proj_id = 'MKTPR';

PROJ_ID PROJ_DESC
======= =================
MKTPR   85:10

SQL> blobview 85:10;
----
====

В примере выше содержимое выбранного BLOB будет отображено во внешнем редакторе. Когда редактор закрыт, управление возвращается в `isql`. Вы не можете использовать `isql`, пока редактор открыт.

[NOTE]
====
`BLOBVIEW` может вернуть ошибку "`Invalid transaction handle`" после закрытия редактора. Для исправления ситуации запустите транзакцию вручную с помощью команды `SET TRANSACTION`.
====

Смотри также: <<fbadmgd-isql-commands_set-set_blob>>, <<fbadmgd-isql-commands-blobdump>>.

[[fbadmgd-isql-commands-edit]]
=== EDIT

.Назначение
Вызов текстового редактора по умолчанию для скрипта.
(((ISQL, EDIT)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
EDIT [_filename_]
----

.Параметры команды `EDIT`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|filename
|Имя файла для редактирования.

|===

Команда `EDIT` позволяет редактировать существующий файл. Это может быть файл команд SQL, который будет использоваться командой ввода `isql` (см. ниже), или любой другой текстовый файл. Файл должен существовать.

Если имя файла не указано, история всех ваших предыдущих команд будет отображаться для редактирования.

[NOTE]
====
Обратите внимание, что при выходе из редактора в этом случае команды, оставленные в буфере в конце редактирования, будут выполняться как файл сценария.
====

[[fbadmgd-isql-commands-help]]
=== HELP

.Назначение
Отображение список команд `isql` с их описанием.
(((ISQL, HELP)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
HELP [SET]
----

Команда `HELP` отображает список основных команд `isql` с их описанием.

[listing]
----
SQL> HELP;
Frontend commands:
BLOBDUMP <blobid> <file>   -- dump BLOB to a file
BLOBVIEW <blobid>          -- view BLOB in text editor
EDIT     [<filename>]      -- edit SQL script file and execute
EDIT                       -- edit current command buffer and execute
HELP                       -- display this menu
INput    <filename>        -- take input from the named SQL file
OUTput   [<filename>]      -- write output to named file
OUTput                     -- return output to stdout
SET      <option>          -- (Use HELP SET for complete list)
SHELL    <command>         -- execute Operating System command in sub-shell
SHOW     <object> [<name>] -- display system information
    <object> = CHECK, COLLATION, DATABASE, DOMAIN, EXCEPTION, FILTER, FUNCTION,
               GENERATOR, GRANT, INDEX, PACKAGE, PROCEDURE, ROLE, SQL DIALECT,
               SYSTEM, TABLE, TRIGGER, VERSION, USERS, VIEW
EXIT                       -- exit and commit changes
QUIT                       -- exit and roll back changes

All commands may be abbreviated to letters in CAPitals
----

Если после `HELP` присутствует необязательное ключевое слово `SET`, то будет отображена справка по набору команд начинающихся с `SET`.

[listing]
----
SQL> help set;
Set commands:
    SET                    -- display current SET options
    SET AUTOddl            -- toggle autocommit of DDL statements
    SET BAIL               -- toggle bailing out on errors in non-interactive mode
    SET BLOB [ALL|<n>]     -- display BLOBS of subtype <n> or ALL
    SET BLOB               -- turn off BLOB display
    SET COUNT              -- toggle count of selected rows on/off
    SET MAXROWS [<n>]      -- limit select stmt to <n> rows, zero is no limit
    SET ECHO               -- toggle command echo on/off
    SET EXPLAIN            -- toggle display of query access plan in the explained form
    SET HEADING            -- toggle display of query column titles
    SET LIST               -- toggle column or table display format
    SET NAMES <csname>     -- set name of runtime character set
    SET PLAN               -- toggle display of query access plan
    SET PLANONLY           -- toggle display of query plan without executing
    SET SQL DIALECT <n>    -- set sql dialect to <n>
    SET STATs              -- toggle display of performance statistics
    SET TIME               -- toggle display of timestamp with DATE values
    SET TERM <string>      -- change statement terminator string
    SET WIDTH <col> [<n>]  -- set/unset print width to <n> for column <col>

All commands may be abbreviated to letters in CAPitals
----

[NOTE]
====
Обратите внимание на последнюю строку вывода команды `help`. Это объясняет, что каждая из команд может быть сокращена до букв, отображаемых заглавными буквами. В следующем обсуждении дополнительные символы будут отображаться, как указано выше, строчными буквами. Например, команда ввода будет показана как `INput`, чтобы указать, что символы 'put' являются необязательными.
====

[[fbadmgd-isql-commands-add]]
=== ADD

.Назначение
Добавление записей в таблицу.
(((ISQL, ADD)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
ADD [_tablename_]
----

.Параметры команды `ADD`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|tablename
|Имя таблицы для добавления данных.

|===

Команда `ADD` запрашивает данные для каждого столбца, указанной таблицы, и добавляет запись в таблицу. Вы можете добавить столько записей, сколько пожелаете, так как команда продолжается до тех пор, пока не произойдет ошибка или не будет нажата клавиша btn:[ENTER] без данных. Если вы хотите установить для столбца значение `NULL`, введите его в точности так, как показано.

.Добавление данных в таблицу с помощью команды ADD
[example]
====
[listing]
----
SQL> add country;

Enter data or NULL for each column. RETURN to end.
Enter COUNTRY>Scotland
Enter CURRENCY>GBP
Enter COUNTRY>

SQL> commit;
----
====

[[fbadmgd-isql-commands-copy]]
=== COPY

.Назначение
Копирование структуры таблицы.
(((ISQL, COPY)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
COPY _from_tablename_ _to_tablename_ [_other_database_]
----

.Параметры команды `COPY`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|from_tablename
|Имя таблицы из которой делается копия.

|to_tablename
|Имя таблицы в которую будет сделана копия.

|other_database
|Спецификация для подключения к другой базе данных, в которую будет производится копирование.

|===

Команда `COPY` позволяет скопировать большую часть структуры таблицы в новую таблицу в текущей базе данных или другой. К сожалению, у неё есть проблемы:

* Она выполняет командную строку для выполнения работы и подключается к принимающей базе данных с помощью приложения с именем `isql`. Если ваша система переименовала `isql` в `isql-fb`, вы на самом деле в конечном итоге запустите неправильное приложение `isql`, и единственным результатом будет запутанная ошибка.

* Предполагается, что `isql` будет находится в `$PATH` или `%PATH%`.

* Вам необходимо определить `ISC_USER` и `ISC_PASSWORD` для дочернего процесса `isql` для входа в получающую базу данных для создания таблицы. Это очень небезопасно.

* Из-за необходимости в `ISC_USER` и `ISC_PASSWORD` принимающая база данных должна работать на том же сервере, что и исходная база данных.

* Данные таблицы не копируются в принимающую базу данных (или таблицу). Копируются только следующие части структур таблицы:
** Домены, необходимые для воссоздания таблицы. Это применимо, только если копия находится в другой базе данных.
** Сама таблица будет создана.
** Ограничение первичного ключа, если оно есть.

* Копируется не вся структура таблицы. Отсутствуют:
** Ограничения внешнего ключа.
** Ограничения проверок (CHECK).
** Индексы, за исключением индекса необходимого для поддержки первичного ключа.
** Триггеры.
** Все данные таблицы.

Если вы хотите скопировать в другую базу данных, то другая база данных должна быть на том же сервере, что и текущая. Например, вы не можете подключиться к базе данных на сервере с именем tux и скопировать таблицу в базу данных, работающую на сервере tuxrep. Команда `COPY` не может передать имя пользователя и/или пароль, установка `ISC_USER` и `ISC_PASSWORD` влияет сразу на все подключения, пользователь может отсутствовать на другом сервере или у него может быть другой пароль.

.Копирование структуры таблицы командой COPY
[example]
====
[listing]
----
tux>$ export ISC_USER=SYSDBA
tux>$ export ISC_PASSWORD=secret
tux>$ isql employee

Database: employee, User: sysdba

SQL> -- MAke a copy of the employee table into this database.
SQL> copy employee employee_2;

SQL> -- Compare table structures...
SQL> show table employee;

EMP_NO              (EMPNO) SMALLINT Not Null
FIRST_NAME          (FIRSTNAME) VARCHAR(15) Not Null
LAST_NAME           (LASTNAME) VARCHAR(20) Not Null
PHONE_EXT           VARCHAR(4) Nullable
HIRE_DATE           TIMESTAMP Not Null DEFAULT 'NOW'
DEPT_NO             (DEPTNO) CHAR(3) Not Null
                    CHECK (VALUE = '000' OR
                    (VALUE > '0' AND VALUE <= '999') OR VALUE IS NULL)
JOB_CODE            (JOBCODE) VARCHAR(5) Not Null
                    CHECK (VALUE > '99999')
JOB_GRADE           (JOBGRADE) SMALLINT Not Null
CHECK               (VALUE BETWEEN 0 AND 6)
JOB_COUNTRY         (COUNTRYNAME) VARCHAR(15) Not Null
SALARY              (SALARY) NUMERIC(10, 2) Not Null DEFAULT 0
                    CHECK (VALUE > 0)
FULL_NAME           Computed by: (last_name || ', ' || first_name)
CONSTRAINT INTEG_28:
  Foreign key (DEPT_NO) References DEPARTMENT (DEPT_NO)
CONSTRAINT INTEG_29:
  Foreign key (JOB_CODE, JOB_GRADE, JOB_COUNTRY)
  References JOB (JOB_CODE, JOB_GRADE, JOB_COUNTRY)
CONSTRAINT INTEG_27:
  Primary key (EMP_NO)
CONSTRAINT INTEG_30:
  CHECK ( salary >= (SELECT min_salary FROM job WHERE
                     job.job_code = employee.job_code AND
                     job.job_grade = employee.job_grade AND
                     job.job_country = employee.job_country) AND
          salary <= (SELECT max_salary FROM job WHERE
                     job.job_code = employee.job_code AND
                     job.job_grade = employee.job_grade AND
                     job.job_country = employee.job_country))
Triggers on Table EMPLOYEE:
SET_EMP_NO, Sequence: 0, Type: BEFORE INSERT, Active
SAVE_SALARY_CHANGE, Sequence: 0, Type: AFTER UPDATE, Active

SQL> show table employee_2;

EMP_NO              (EMPNO) SMALLINT Not Null
FIRST_NAME          (FIRSTNAME) VARCHAR(15) Not Null
LAST_NAME           (LASTNAME) VARCHAR(20) Not Null
PHONE_EXT           VARCHAR(4) Nullable
HIRE_DATE           TIMESTAMP Not Null DEFAULT 'NOW'
DEPT_NO             (DEPTNO) CHAR(3) Not Null
                    CHECK (VALUE = '000' OR
                          (VALUE > '0' AND VALUE <= '999') OR VALUE IS NULL)
JOB_CODE            (JOBCODE) VARCHAR(5) Not Null
                    CHECK (VALUE > '99999')
JOB_GRADE           (JOBGRADE) SMALLINT Not Null
                    CHECK (VALUE BETWEEN 0 AND 6)
JOB_COUNTRY         (COUNTRYNAME) VARCHAR(15) Not Null
SALARY              (SALARY) NUMERIC(10, 2) Not Null DEFAULT 0
CHECK               (VALUE > 0)
FULL_NAME           Computed by: (last_name || ', ' || first_name)
CONSTRAINT INTEG_93:
  Primary key (EMP_NO)

SQL> -- Check indices on both tables...
SQL> show indices employee;

NAMEX INDEX ON EMPLOYEE(LAST_NAME, FIRST_NAME)
RDB$FOREIGN8 INDEX ON EMPLOYEE(DEPT_NO)
RDB$FOREIGN9 INDEX ON EMPLOYEE(JOB_CODE, JOB_GRADE, JOB_COUNTRY)
RDB$PRIMARY7 UNIQUE INDEX ON EMPLOYEE(EMP_NO)

SQL> show indices employee_2;
RDB$PRIMARY27 UNIQUE INDEX ON EMPLOYEE_2(EMP_NO)

SQL> -- Check data counts on both tables...
SQL> select count(*) from employee;

       COUNT
============
          42

SQL> select count(*) from employee_2;

       COUNT
============
           0
----
====

Команда `COPY` работает только при условии, что ваше приложение `isql` действительно называется `isql`. Кроме того, если в таблице много данных, вам все равно придется копировать их вручную, так как команда копирования будет копировать только структуру таблицы. Помните, что в новой таблице не будет ни триггеров, ни внешних ключей, ни индексов, кроме первичного ключа, ни данных.

[NOTE]
====
Возможно команда `COPY` будет удалена из `isql` в следующих версиях.
====

[[fbadmgd-isql-commands-input]]
=== INPUT

.Назначение
Подключение файла скрипта.
(((ISQL, INPUT)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
INPUT _filename_
----

.Параметры команды `INPUT`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|filename
|Имя файла с SQL скриптом.

|===

Команда `INPUT` читает и выполняет блок команд из указанного текстового файла (скрипта SQL). Входные файлы могут содержать другие команды `INPUT`, предоставляя таким образом возможность проектирования цепочного или структурированного набора скриптов DDL.

.Использование команды INPUT для включения скрипта
[example]
====
[listing]
----
SQL> shell;

$ cat test.sql
drop table fred;
commit;

$ exit;

SQL> show table fred;

A       INTEGER Nullable
B       INTEGER Not Null

SQL> input test.sql;

SQL> show table fred;
There is no table FRED in this database
----
====

Смотри также: <<fbadmgd-isql-commands-shell>>

[[fbadmgd-isql-commands-output]]
=== OUTPUT

.Назначение
Перенаправление вывода.
(((ISQL, OUTPUT)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
OUTPUT [_filename_]
----

.Параметры команды `OUTPUT`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|filename
|Имя файла для вывода.

|===

Команда `OUTPUT` перенаправляет весь вывод, который обычно отображается на экране, в определенный файл. Если указано имя файла, все последующие выходные данные отправляются в этот файл и не отображаются на экране. Если имя файла не указано, вывод снова перенаправляется на экран.

.Использование команды OUTPUT
[example]
====
[listing]
----
SQL> output test.log;

SQL> show tables;

SQL> output;

SQL> shell;

$ cat test.log

COUNTRY              CUSTOMER
DEPARTMENT           EMPLOYEE
EMPLOYEE_PROJECT     FRED
JOB                  PROJECT
PROJ_DEPT_BUDGET     SALARY_HISTORY
SALES
----
====

Смотри также: <<fbadmgd-isql-commands-shell>>

[[fbadmgd-isql-commands-set]]
=== SET

.Назначение
Отображение текущий установок.
(((ISQL, SET)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET
----

Команда `SET` выводит текущие опции установленные с помощью команд `SET`.

.Использование команды SET
[example]
====
[listing]
----
SQL> SET;

Print statistics:        OFF
Echo commands:           OFF
List format:             OFF
Show Row Count:          OFF
Select maxrows limit:    0
Autocommit DDL:          ON
Access Plan:             OFF
Access Plan only:        OFF
Explain Access Plan:     OFF
Display BLOB type:       1
Column headings:         ON
Terminator:              ;
Time:                    OFF
Warnings:                ON
Bail on error:           OFF
Keep transaction params: OFF

SQL>
----
====

[[fbadmgd-isql-commands-shell]]
=== SHELL

.Назначение
Предоставление доступа к командной строке.
(((ISQL, SHELL)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHELL [<command>]
----

.Параметры команды `SHELL`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|command
|Команда системной консоли.

|===

Команда `SHELL` позволяет вам временно выйти из `isql` и использовать сеанс системной оболочки для дальнейшей обработки. При этом не происходит подтверждение или откат любой транзакции.

Аргумент `&lt;command&gt;` является необязательным, это команда или вызов, допустимый в командной строке, из которой была запущена `isql`. Команда будет выполнена, а управление возвращено `isql`. Если команда не указана, `isql` открывает интерактивную сессию в командной строке. При выходе из оболочки вы вернетесь в `isql`. Вы не можете использовать сеанс `isql`, который активировал оболочку, пока сеанс оболочки остается открытым.

.Использование команды SHELL
[example]
====
[listing]
----
SQL> shell;

$ cat test.log

  COUNTRY              CUSTOMER
  DEPARTMENT           EMPLOYEE
  EMPLOYEE_PROJECT     FRED
  JOB                  PROJECT
  PROJ_DEPT_BUDGET     SALARY_HISTORY
  SALES
$ exit
SQL>
----
====

[[fbadmgd-isql-commands-exit]]
=== EXIT

.Назначение
Выход из `isql` с подтверждение текущей транзакции.
(((ISQL, EXIT)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
EXIT
----

Команда `EXIT` подтверждает текущую транзакцию без подсказки, закрывает базу данных и завершает сессию `isql`.

Смотри также: <<fbadmgd-isql-commands-quit>>.

[[fbadmgd-isql-commands-quit]]
=== QUIT

.Назначение
Выход из `isql` с откатом текущей транзакции.
(((ISQL, QUIT)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
QUIT
----

Команда `QUIT` отменяет текущую транзакцию и закрывает базу данных и завершает сессию `isql`.

Смотри также: <<fbadmgd-isql-commands-exit>>.

[[fbadmgd-isql-commands_set]]
== ISQL SET команды

Как объясняется в команде `HELP`, вы можете ввести команду `HELP SET,` чтобы перейти к различным опциям доступных для `SET` команды. Команда `HELP SET` выводит следующую справку.

[listing]
----
SQL> help set;

Set commands:
    SET                    -- display current SET options
    SET AUTOddl            -- toggle autocommit of DDL statements
    SET BAIL               -- toggle bailing out on errors in non-interactive mode
    SET BLOB [ALL|<n>]     -- display BLOBS of subtype <n> or ALL
    SET BLOB               -- turn off BLOB display
    SET COUNT              -- toggle count of selected rows on/off
    SET MAXROWS [<n>]      -- limit select stmt to <n> rows, zero is no limit
    SET ECHO               -- toggle command echo on/off
    SET EXPLAIN            -- toggle display of query access plan in the explained form
    SET HEADING            -- toggle display of query column titles
    SET LIST               -- toggle column or table display format
    SET NAMES <csname>     -- set name of runtime character set
    SET PLAN               -- toggle display of query access plan
    SET PLANONLY           -- toggle display of query plan without executing
    SET SQL DIALECT <n>    -- set sql dialect to <n>
    SET STATs              -- toggle display of performance statistics
    SET TIME               -- toggle display of timestamp with DATE values
    SET TERM <string>      -- change statement terminator string
    SET WIDTH <col> [<n>]  -- set/unset print width to <n> for column <col>

All commands may be abbreviated to letters in CAPitals
----

[NOTE]
====
В выше приведённом примере команды BLOB являются неполными. Они должны быть отображены как `BLOBdisplay`. Далее мы будем использовать полную версию команды.
====

Последняя строка вышеприведенного вывода указывает, что эти команды могут быть сокращены до заглавных букв. К сожалению, кроме команды `SET AUTOddl`, ни одна из других не имеет краткой формы.

[[fbadmgd-isql-commands_set-set]]
=== SET

.Назначение
Отображение текущий установок.

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET
----

Команда `SET` выводит текущие опции, установленные с помощью команд `SET`.

.Использование команды SET
[example]
====
[listing]
----
SQL> SET;

Print statistics:        OFF
Echo commands:           OFF
List format:             OFF
Show Row Count:          OFF
Select maxrows limit:    0
Autocommit DDL:          ON
Access Plan:             OFF
Access Plan only:        OFF
Explain Access Plan:     OFF
Display BLOB type:       1
Column headings:         ON
Terminator:              ;
Time:                    OFF
Warnings:                ON
Bail on error:           OFF
Keep transaction params: OFF

SQL>
----
====

[[fbadmgd-isql-commands_set-set_autoddl]]
=== SET AUTODDL

.Назначение
Установка или отключение автоматического подтверждения для DDL операторов.
(((ISQL, SET AUTODDL)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET AUTOddl [ON | OFF]
----

Команда `SET AUTODDL` устанавливает будет ли автоматически подтверждаться транзакция для DDL операторов. Команда без каких-либо параметров действует как переключатель, она отключает функцию `AUTODLL`, если она включена или наоборот. Вы можете указать конкретный параметр, чтобы прояснить свои намерения. Параметр должен быть одним из двух `ON` или `OFF`. Команда `SET` без параметров отобразит текущую настройку. По умолчанию функция `AUTODDL` включена.

[[fbadmgd-isql-commands_set-set_bail]]
=== SET BAIL

.Назначение
Передача обработки ошибок операционной системе.
(((ISQL, SET BAIL)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET BAIL [ON | OFF]
----

Команда `SET BAIL` устанавливает, будет ли `isql` останавливать выполнение скрипта в пакетном режиме при возникновении ошибки и передавать управление операционной системе, возвращая при этом код ошибки. В интерактивном режиме при возникновении ошибок `isql` не будет прекращать свою работу.

Выполнение этой команды без передачи параметра приводит к переключению текущего состояния. Если `SET BAIL` включен, то он отключится и наоборот.

[[fbadmgd-isql-commands_set-set_blob]]
=== SET BLOB

.Назначение
Передача обработки ошибок операционной системе.
(((ISQL, SET BLOB)))(((ISQL, SET BLOBdisplay)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET BLOB [_n_ | ALL | OFF]

SET BLOBdisplay [_n_ | ALL | OFF]
----

.Параметры команды `SET BLOB`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|n
|Номер подтипа BLOB. Значение по умолчанию n=1 (текст).
Положительные числа определены в системе; отрицательные числа определяются пользователем.

|===

Команда `SET BLOB` определяет, должны ли данные столбца типа `BLOB` отображаться в выводе. Если параметры не переданы в команду `SET BLOB` или передан параметр `OFF`, то поля типа `BLOB` отображаться не будут, вместо них будут отображаться идентификаторы BLOB.

Идентификатор BLOB представляет собой два шестнадцатеричных числа, разделенных двоеточием. Первое число -- это идентификатор таблицы, а второе -- последовательный номер в базе данных.

Если в команду `SET BLOB` передан параметр `ALL`, то будут отображаться BLOB поля всех подтипов.

Если передано число, представляющее подтип BLOB, то будут отображаться только BLOB с указанным подтипом. По умолчанию отображаются поля с подтипом 1 (текстовые данные).

.Использование SET BLOB
[example]
====
[listing]
----
SQL> -- Don't display any blob data.
SQL> set blob off;

SQL> select proj_desc
CON> from project
CON> where proj_id = 'HWRII';

        PROJ_DESC
=================
           85:1e4

SQL> -- Display all blob data.
SQL>  set blobdisplay all;

SQL> select proj_desc
CON> from project
CON> where proj_id = 'HWRII';

        PROJ_DESC
=================
           85:1e4
==============================================================================
PROJ_DESC:
Integrate the hand-writing recognition module into the
universal language translator.

==============================================================================

SQL> -- Only display type 1 blob data = text.
SQL> set blob 1;

SQL> select proj_desc
CON> from project
CON> where proj_id = 'HWRII';

        PROJ_DESC
=================
           85:1e4
==============================================================================
PROJ_DESC:
Integrate the hand-writing recognition module into the
universal language translator.

==============================================================================

SQL> -- Only display blob type 7 = not text!
SQL> set blob 7;

SQL> select proj_desc
CON> from project
CON> where proj_id = 'HWRII';

        PROJ_DESC
=================
           85:1e4
==============================================================================
PROJ_DESC:
BLOB display set to subtype 7. This BLOB: subtype = 1
==============================================================================
----
====

В последнем примере вы заметите, что было отображено сообщение о том, что мы отображаем данные BLOB только для подтипа 7, а данные BLOB в этой таблице являются подтипом 1, поэтому данные не отображаются.

Смотри также: <<fbadmgd-isql-commands-blobdump>>, <<fbadmgd-isql-commands-blobview>>.

[[fbadmgd-isql-commands_set-set_bulk_insert]]
=== SET BULK_INSERT

.Назначение
Пакетная вставка записей в таблицу.
(((ISQL, SET BULK_INSERT)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET BULK_INSERT <prepared insert statement>
----

.Параметры команды `SET BULK_INSERT`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|prepared insert statement
|Подготовленный оператор `INSERT`.

|===

Команда `SET BULK_INSERT` осуществляет примитивную обработку подготовленных запросов на вставку. После ввода этой команды пользователь входит в интерактивный режим (`BULK>`), где требуется ввести параметры в виде кортежа
`(_val1_ ... _valN_)`. Для выхода из интерактивного режима введите пустую строку или любой символ, отличный от "`(`" и "`--`" (можно явно выйти, введя слово STOP). Кортежи должны располагаться на одной строке, за исключением параметров в кавычках. Однако, если добавить "`+++`" после запятой, параметры кортежа можно переносить на следующую строку. Одиночные комментарии ("`--`") можно добавлять только между кортежами. Команды `COMMIT` или `COMMIT WORK `вводятся с первого символа строки и располагаются на одной строке. Любые символы, идущие за кортежем, кроме "`)`" и "`+++`", будут игнорироваться.

.Использование SET BULK_INSERT для пакетной вставки
[example]
====
[listing]
----
SQL> create table t1(id int not null primary key, name varchar(50));

SQL> set bulk_insert insert into t1(id, name) values(?, ?);
BULK> (1, 'a')
BULK> (2, 'b')
BULK> (3, 'c')
BULK> commit;
BULK>
SQL> select * from t1;

          ID NAME
============ ==================================================
           1 a
           2 b
           3 c

SQL> set bulk_insert insert into t1(id, name) values(?, ?);
BULK> -- insert 4 record
BULK> (4, 'abcd')
BULK> (5, +++
CON> 'efg')
BULK> stop

SQL> commit;

SQL> select * from t1;

          ID NAME
============ ==================================================
           1 a
           2 b
           3 c
           4 abcd
           5 efg
----
====

[[fbadmgd-isql-commands_set-set_count]]
=== SET COUNT

.Назначение
Включение или выключение отображения количества строк затронутых запросом.
(((ISQL, SET COUNT)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET COUNT [ON | OFF]
----

Команда `SET COUNT` включает или выключает отображение количества строк затронутых DML запросом. Выполнение этой команды без передачи параметра приводит к переключению текущего состояния.

[listing]
----
SQL> set count on;

SQL> select count(*) from employee;

                COUNT
=====================
                   42

Records affected: 1
----

Количество затронутых записей отображается для всех DDL операторов, а не только для `SELECT`.

[listing]
----
SQL> create table fred( a integer);
SQL> commit;

SQL> insert into fred values (666);
Records affected: 1

SQL> update fred set a = 123 where a = 666;
Records affected: 1

SQL> delete from fred;
Records affected: 1

SQL> commit;
----

Смотри также: <<fbadmgd-isql-commands_set-set_rowcount>>.

[[fbadmgd-isql-commands_set-set_echo]]
=== SET ECHO

.Назначение
Включение или выключение отображения команд до их выполнения.
(((ISQL, SET ECHO)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET ECHO [ON | OFF]
----

Команда `SET ECHO` включает или выключает отображение команд до их выполнения. Вы может отключить эхо-вывод для части файла сценария, хотя по умолчанию эхо вывод выключен в ISQL. Выполнение этой команды без передачи параметра приводит к переключению текущего состояния.

.Использование команды SET ECHO
[example]
====
[listing]
----
SQL> set echo on;

SQL> select count(*) from rdb$database;
select count(*) from rdb$database;

                COUNT
=====================
                    1

Records affected: 1
SQL> set echo off;
set echo off;

SQL> select count(*) from rdb$database;

                COUNT
=====================
                    1

Records affected: 1
----
====

Эта команда может быть полезна в файле сценария. Если вы получаете сообщение об ошибке, иногда бывает трудно определить точный оператор SQL, вызвавший ее. Если вы установите `ECHO ON` в своем скрипте, вы по крайней мере сможете точно определить, какой оператор потерпел неудачу.

[[fbadmgd-isql-commands_set-set_explain]]
=== SET EXPLAIN

.Назначение
Включение или выключение отображения расширенного плана запроса.
(((ISQL, SET EXPLAIN)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET EXPLAIN [ON | OFF]
----

Команда `SET EXPLAIN` включает или выключает отображение расширенного плана запроса. Расширенный план выводит более подробную информацию о методах доступа используемых оптимизатором, однако его нельзя включить в запрос. По умолчанию вывод расширенного плана запроса отключен. Выполнение этой команды без передачи параметра приводит к переключению текущего состояния.

.Использование команды SET EXPLAIN
[example]
====
[listing]
----
SQL> set explain on;
SQL> set planonly on;
SQL> select * from employee cross join rdb$database;

Select Expression
    -> Nested Loop Join (inner)
        -> Table "RDB$DATABASE" Full Scan
        -> Table "EMPLOYEE" Full Scan
SQL>
----
====

[TIP]
====
Если вам необходимо вывести только план запроса без его выполнения, то вы можете выполнить команду `SET PLANONLY ON`.
====

Смотри также: <<fbadmgd-isql-commands_set-set_plan>>, <<fbadmgd-isql-commands_set-set_planonly>>.

[[fbadmgd-isql-commands_set-set_heading]]
=== SET HEADING

.Назначение
Включение или выключение отображения заголовков столбцов.
(((ISQL, SET HEADING)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET HEADING [ON | OFF]
----

Команда `SET HEADING` включает или выключает отображение заголовков столбцов. По умолчанию отображение заголовков столбцов включено. Выполнение этой команды без передачи параметра приводит к переключению текущего состояния.

.Использование команды SET HEADING
[example]
====
[listing]
----
SQL> set plan off;
SQL> set heading off;
SQL> select count(*) from employee;

                   42

SQL> set heading on;
SQL> select count(*) from employee;

                COUNT
=====================
                   42
----
====

[[fbadmgd-isql-commands_set-set_keep_tran]]
=== SET KEEP_TRAN_params

.Назначение
Включение или выключение сохранения параметров транзакции.
(((ISQL, SET KEEP_TRAN_PARAMS)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET KEEP_TRAN[_PARAMS] [ON | OFF]
----

Операторы DML для выборки или изменения данных стартуют новую транзакцию с уровнем изоляции `SNAPSHOT` с разрешением блокировки в режиме `WAIT`, если она не была начата ранее. Такая транзакция будет активной до тех пор, пока не будет вручную подтверждена оператором `COMMIT` или отменена оператором `ROLLBACK`.

Пользователи могут указать уровень изоляции и другие параметры для следующей транзакции с помощью оператора `SET TRANSACTION`. Он может быть выполнен только тогда, когда не активна другая транзакция. В противном случае будет задан вопрос: подтвердить или откатить активную транзакцию.

После выполнения `COMMIT` или `ROLLBACK`, новая DML команда стартует транзакцию с параметрами по умолчанию. Если необходимо, чтобы новая транзакция стартовала с параметрами, которые были указаны для предыдущей транзакции, то необходимо включить режим сохранения параметров транзакции с помощью команды `SET KEEP_TRAN_PARAMS` (может быть сокращена до `SET KEEP_TRAN`).

Если режим `KEEP_TRAN_PARAMS` установлен в:

* `ON`, то `isql` сохраняет текст следующего успешного оператора `SET TRANSACTION,` и новые транзакции DML запускаются с использованием того же SQL (вместо режима по умолчанию `CONCURRENCY WAIT`);
* `OFF`, то `isql` начинает новую транзакцию DML как обычно.

.Использование SET KEEP_TRAN_PARAMS
[example]
====
[listing]
----
SQL> SET;
...
Keep transaction params: OFF

SQL> SET TRANSACTION READ COMMITTED WAIT;
Commit current transaction (y/n)?y
Committing.

SQL> SELECT RDB$GET_CONTEXT('SYSTEM', 'ISOLATION_LEVEL') FROM RDB$DATABASE;

RDB$GET_CONTEXT
===============================================================================
READ COMMITTED

SQL> commit;
SQL> SELECT RDB$GET_CONTEXT('SYSTEM', 'ISOLATION_LEVEL') FROM RDB$DATABASE;

RDB$GET_CONTEXT
===============================================================================
SNAPSHOT
----

Как видите после `COMMIT` новая транзакция стартует с параметрами по умолчанию. Теперь установим режим сохранения параметров транзакции.

[listing]
----
SQL> SET KEEP_TRAN_PARAMS ON;
SQL> SET;
...
Keep transaction params: ON

SQL> SET TRANSACTION READ COMMITTED WAIT;
Commit current transaction (y/n)?y
Committing.
SQL> SELECT RDB$GET_CONTEXT('SYSTEM', 'ISOLATION_LEVEL') FROM RDB$DATABASE;

RDB$GET_CONTEXT
===============================================================================
READ COMMITTED

SQL> commit;
SQL> SELECT RDB$GET_CONTEXT('SYSTEM', 'ISOLATION_LEVEL') FROM RDB$DATABASE;

RDB$GET_CONTEXT
===============================================================================
READ COMMITTED
----
====

[NOTE]
====
Данная функциональность была введена в Firebird 3.0.6. Ранее невозможно было включить режим сохранения параметров транзакции. После команд `COMMIT` и `ROLLBACK` необходимо было каждый раз выполнять команду `SET TRANSACTION` с необходимыми параметрами.
====

[[fbadmgd-isql-commands_set-set_list]]
=== SET LIST

.Назначение
Включение или выключение отображения вывода результатов `SELECT` запроса в виде списка.
(((ISQL, SET LIST)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET LIST [ON | OFF]
----

Команда `SET LIST` управляет отображением данных, возвращаемых оператором `SELECT`. По молчанию данные на экране выводятся в табличном варианте, где сверху названия столбцов, а под ними все строки, удовлетворяющие запросу `SELECT`. Включение режима списка приводит к другому формату, в котором заголовок каждого столбца отображается слева, а данные столбца -- справа. Это повторяется для каждой строки, возвращаемой запросом.

Выполнение этой команды без передачи параметра приводит к переключению текущего состояния.

.Использование команды SET LIST
[example]
====
[listing]
----
SQL> set list off;
SQL> select emp_no, first_name, last_name, salary
CON> from employee;

 EMP_NO FIRST_NAME      LAST_NAME                           SALARY
======= =============== ==================== =====================
      2 Robert          Nelson                           105900.00
      4 Bruce           Young                             97500.00
      5 Kim             Lambert                          102750.00
      8 Leslie          Johnson                           64635.00
.............

SQL> set list on;
SQL> select emp_no, first_name, last_name, salary
CON> from employee;

EMP_NO                          2
FIRST_NAME                      Robert
LAST_NAME                       Nelson
SALARY                          105900.00

EMP_NO                          4
FIRST_NAME                      Bruce
LAST_NAME                       Young
SALARY                          97500.00

..........
----
====

[[fbadmgd-isql-commands_set-set_names]]
=== SET NAMES

.Назначение
Установка набора символов для последующий подключений.
(((ISQL, SET NAMES)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET NAMES _character_set_
----

.Параметры команды `SET NAMES`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|character_set
|Набор символов для последующих подключений.

|===

Оператор `SET NAMES` устанавливает набор символов для последующих подключений к базе данных с помощью isql. Это позволяет вам переопределить набор символов по умолчанию для базы данных. Чтобы вернуться к использованию набора символов по умолчанию, используйте `SET NAMES` без аргументов.

Используйте команду `SET NAMES` перед подключением к базе данных для того, чтобы указать требуемый набор символов. Список поддерживаемых наборов символов можно посмотреть выполнив запрос:

[source,sql]
----
select RDB$CHARACTER_SET_NAME
from RDB$CHARACTER_SETS
order by 1;
----

[listing]
----
RDB$CHARACTER_SET_NAME
==============================
ASCII
BIG_5
CP943C
CYRL
...
DOS864
DOS865
DOS866
DOS869
...
NONE
OCTETS
...
UTF8
...
WIN1250
WIN1251
WIN1252
...
----

Выбор набора символов ограничивает возможные порядки сопоставления (сортировки) подмножеством всех доступных порядков сопоставления для заданного набора символов.

Если набор символов по умолчанию для базы данных не равен `NONE`, то в ситуациях, когда клиент использует другой набор символов для базы данных, возможно пострадать от повреждения данных, поскольку некоторые наборы символов не могут преобразовать некоторые символы в подходящий символ в другом наборе символов.

Если вы не передадите набор символов, то по умолчанию будет использоваться набор символов `NONE`.

[[fbadmgd-isql-commands_set-set_plan]]
=== SET PLAN

.Назначение
Включение или отключение отображение плана запроса.
(((ISQL, SET PLAN)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET PLAN [ON | OFF]
----

Команда `SET PLAN` определяет, будет ли `isql` отображать план, который он использовал для доступа к данным для каждого выполненного оператора. По умолчанию `isql` никогда не отображает план. Как и во многих других командах, отсутствие параметра переключает текущее состояние.

.Использование команды SET PLAN
[example]
====
[listing]
----
SQL> set plan on;

SQL> select emp_no, first_name, last_name
CON> from employee
CON> where emp_no = 107;

PLAN (EMPLOYEE INDEX (RDB$PRIMARY7))

 EMP_NO FIRST_NAME      LAST_NAME
======= =============== ====================
    107 Kevin           Cook

SQL> update employee
CON> set first_name = 'Norman'
CON> where last_name = 'Cook';

PLAN (EMPLOYEE INDEX (NAMEX))

SQL> select count(*) from employee;

PLAN (EMPLOYEE NATURAL)

                COUNT
=====================
                   42
----
====

План выполнения отображается перед выводом из оператора `SELECT`.

[TIP]
====
Для вывода расширенного плана используйте команду `SET EXPLAIN`.
====

Смотри также: <<fbadmgd-isql-commands_set-set_explain>>, <<fbadmgd-isql-commands_set-set_planonly>>.

[[fbadmgd-isql-commands_set-set_planonly]]
=== SET PLANONLY

.Назначение
Включение или отключение режима отображение только плана запроса без его выполнения.
(((ISQL, SET PLANONLY)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET PLANONLY [ON | OFF]
----

Команда `SET PLANONLY ON`не позволяет Firebird фактически выполнить оператор SQL, а просто показывает план, который будет использоваться для доступа к данным. Эта команда опирается на команду `SET PLAN`. Если `SET PLAN OFF` был выполнен, то эта команда не имеет никакого эффекта, поэтому включение `PLANONLY ON` имеет дополнительный эффект неявного выполнения `SET PLAN ON`.  Выполнение `SET PLANONLY OFF` не вызывает неявного выполнения `SET PLAN OFF`.

.Использование команды SET PLANONLY
[example]
====
[listing]
----
SQL> set planonly on;

SQL> select count(*) from employee;

PLAN (EMPLOYEE NATURAL)
----
====

Как и во многих других командах, отсутствие параметра переключает текущее состояние.

Действие команды `SET PLANONLY ON` также распространяется и на вывод расширенного плана без фактического выполнения запроса.

.Использование команды SET PLANONLY совместно с SET EXPLAIN
[example]
====
[listing]
----
SQL> set explain on;
SQL> set planonly on;

SQL> select count(*) from employee;

Select Expression
    -> Aggregate
        -> Table "EMPLOYEE" Full Scan
----
====

Смотри также: <<fbadmgd-isql-commands_set-set_plan>>, <<fbadmgd-isql-commands_set-set_explain>>.

[[fbadmgd-isql-commands_set-set_rowcount]]
=== SET MAXROWS или SET ROWCOUNT

.Назначение
Установка максимального количества выводимых записей.
(((ISQL, SET ROWCOUNT)))(((ISQL, SET MAXROWS)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET {MAXROWS | ROWCOUNT} [_n_]
----

.Параметры команды `SET MAXROWS`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|n
|Максимальное количество выводимых записей

|===

Установка `MAXROWS` в ноль (что является значением по умолчанию при запуске `isql`) приводит к тому, что оператор `SELECT` возвращает все строки, соответствующие условиям в предложении `WHERE`. В некоторых случаях вам не нужно, чтобы большой объём данных прокручивался вверх по экрану, поэтому вы можете задать для `MAXROWS` меньшее значение, и все последующие операторы `SELECT` будут отображать только первые _n_ строк, а не все.

.Использование команды SET MAXROWS
[example]
====
[listing]
----
SQL> set count on;
SQL> set maxrows 0;

SQL> select emp_no from employee;

 EMP_NO
=======
      2
      4
...
    144
    145

Records affected: 42

SQL> set maxrows 10;
SQL> select emp_no from employee;

 EMP_NO
=======
      2
      4
...
     15
     20

Records affected: 10
----
====

Нет никаких признаков, что `MAXROWS` ограничивает количество возвращаемых строк. Пользователь должен помнить или проверять, включено ли `MAXROWS`. Использование `MAXROWS` может привести к путанице в точном количестве строк в таблице!

См. также: <<fbadmgd-isql-commands_set-set_count>>.

[[fbadmgd-isql-commands_set-set_sqlda]]
=== SET SQLDA_DISPLAY

.Назначение
Включение или отключение отображения информации о внутренних структурах для входных и выходных сообщений.
(((ISQL, SET SQLDA_DISPLAY)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET SQLDA_DISPLAY [ON | OFF]
----

Это скрытая команда, которая не упоминается в выводе команды `HELP SET`. Она отображает внутренние подробности о структурах для входных и выходных сообщений операторов SQL, выполняемых `isql`. Раньше она была доступна только в специальной отладочной сборке, но начиная с версии 2.0 она доступна в `isql`.

.Использование команды SET SQLDA_DISPLAY
[example]
====
[listing]
----
SQL> set sqlda_display on;

SQL> select count(*) from employee;

INPUT message field count: 0

OUTPUT message field count: 1
01: sqltype: 580 INT64 scale: 0 subtype: 0 len: 8
  :  name: COUNT  alias: COUNT
  : table:   owner:

                COUNT
=====================
                   42

SQL> select emp_no as id, first_name from employee fetch first row only;

INPUT message field count: 0

OUTPUT message field count: 2
01: sqltype: 500 SHORT scale: 0 subtype: 0 len: 2
  :  name: EMP_NO  alias: ID
  : table: EMPLOYEE  owner: SYSDBA
02: sqltype: 448 VARYING scale: 0 subtype: 0 len: 15 charset: 0 NONE
  :  name: FIRST_NAME  alias: FIRST_NAME
  : table: EMPLOYEE  owner: SYSDBA

     ID FIRST_NAME
======= ===============
      2 Robert

SQL> select emp_no as id, first_name from employee
CON> where emp_no = ? fetch first row only;

INPUT message field count: 1
01: sqltype: 500 SHORT scale: 0 subtype: 0 len: 2
  :  name:   alias:
  : table:   owner:

OUTPUT message field count: 2
01: sqltype: 500 SHORT scale: 0 subtype: 0 len: 2
  :  name: EMP_NO  alias: ID
  : table: EMPLOYEE  owner: SYSDBA
02: sqltype: 448 VARYING scale: 0 subtype: 0 len: 15 charset: 0 NONE
  :  name: FIRST_NAME  alias: FIRST_NAME
  : table: EMPLOYEE  owner: SYSDBA
Statement failed, SQLSTATE = 07002
Dynamic SQL Error
-SQLDA error
-No SQLDA for input values provided
----
====

[NOTE]
====
Обратите внимание, что при запуске команд `HELP SET` или `SET` информация об этой команде не отображается.
====

[TIP]
====
Последний оператор вызвал ошибку, поскольку `isql` не позволяет запрашивать значения для входных параметров. Вы можете подавить её отключив фактическое выполнение команды с помощью `SET PLANONLY ON`.
====

[[fbadmgd-isql-commands_set-set_sqldialect]]
=== SET SQL DIALECT

.Назначение
Установка SQL диалекта.
(((ISQL, SET SQL DIALECT)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET SQL DIALECT {1 | 2 | 3}
----

Команда `SET SQL DIALECT` задает диалект SQL Firebird, на который должен быть изменен сеанс клиента. Если сеанс в настоящее время присоединен к базе данных, отличной от диалекта, указанного в команде, отображается предупреждение.

Посмотрите <<fbadmgd-isql-sql_dialect, Диалекты SQL>> для того, чтобы узнать о различиях между тремя диалектами.

.Использование команды SET SQL DIALECT
[example]
====
[listing]
----
SQL> set sql dialect 1;
WARNING: Client SQL dialect has been set to 1 when
connecting to Database SQL dialect 3 database.
...
SQL> set sql dialect 3;
----
====

[NOTE]
====
Предупреждение в приведенном выше примере пришлось разделить на две строки, чтобы оно поместилось на странице. Обычно оно состоит из одной строки.
====

[[fbadmgd-isql-commands_set-set_stats]]
=== SET STATs

.Назначение
Включение или отключение отображения статистки.
(((ISQL, SET STATs)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET STATs [ON | OFF]
----

Команда `SET STATS` определяет, должен ли `isql` отображать различную статистику о каждой выполненной команде SQL. Как и во многих других командах, отсутствие параметра переключает текущее состояние.

.Использование команды SET STATS
[example]
====
[listing]
----
SQL> set stat on;
SQL> select count(*) from employee;

                COUNT
=====================
                   42

Current memory = 19458128
Delta memory = 282544
Max memory = 19531888
Elapsed time= 0.103 sec
Buffers = 2048
Reads = 28
Writes = 0
Fetches = 360
----
====

[[fbadmgd-isql-commands_set-set_time]]
=== SET TIME

.Назначение
Включение или отключение отображение времени для типа `DATE` в 1-диалекте.
(((ISQL, SET TIME)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET TIME [ON | OFF]
----

Команда `SET TIME` применяется только к базам данных диалекта 1. Её выполнение приводит к тому, что часть времени отображается или нет, когда выбираются данные с типом данных `DATE`. Команда не имеет действия с базами данных в других диалектах.

.Использовании команды SET TIME
[example]
====
[listing]
----
SQL> select localtimestamp from rdb$database;

LOCALTIMESTAMP
==============
23-FEB-2020

SQL> set time on;
SQL> select localtimestamp from rdb$database;

           LOCALTIMESTAMP
=========================
23-FEB-2020 13:25:30.7800

SQL>
----
====

[[fbadmgd-isql-commands_set-set_term]]
=== SET TERM

.Назначение
Установка символа (символов) терминатора команды или оператора.
(((ISQL, SET TERM)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET TERM _new_terminator_ _current_terminator_
----

.Параметры команды `SET TERM`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|new_terminator
|Новый символ (символы) терминатор.

|current_terminator
|Текущий символ (символы) терминатор.

|===

Команда `SET TERM` изменяет терминатор оператора по умолчанию с точки с запятой на что-то другое, определенное в переданной строке. Это полезно, когда вы собираетесь ввести строку SQL-операторов, составляющих, например, процедуру или триггер. Утилита `isql` попытается выполнить каждый оператор, когда встречает завершающую точку с запятой, поэтому сначала нужно изменить терминатор, а затем ввести требуемый код. После завершения ввода, вы можете изменить его обратно. При этом необходимо помнить, что вы должны завершить команду `SET TERM` текущим символом (символами) терминатором.

При первом запуске `isql` использует точку с запятой в качестве терминатора по умолчанию.

.Использование команды SET TERM
[example]
====
[listing]
----
SQL> set term ~ ;

SQL> create procedure test_proc (iInput integer = 666)
CON> returns (oOutput integer)
CON> as
CON> begin
CON>   oOutput = iInput;
CON>   suspend;
CON> end~

SQL> set term ; ~

SQL> commit;

SQL> select * from test_proc;

     OOUTPUT
============
         666
----
====

Смотри также: <<fbadmgd-isql-terminator>>.

[[fbadmgd-isql-commands_set-set_warnings]]
=== SET WARNINGS или ЫУЕ ЦТП

.Назначение
Включение или выключение вывода предупреждающих сообщений.
(((ISQL, SET WARNINGS)))(((ISQL, SET WNG)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET {WARNINGS | WNG} [ON | OFF]
----

Команда `SET WARNINGS` включает или выключает вывод предупреждающих сообщений.

[[fbadmgd-isql-commands_set-set_width]]
=== SET WIDTH

.Назначение
Установка ширины вывода для символьных столбцов.
(((ISQL, SET WIDTH)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SET WIDTH _column_name_ _width_
----

.Параметры команды `SET WIDTH`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|column_name
|Наименование или псевдоним символьного столбца.

|width
|Ширина вывода в символах.

|===

Обычно ширина вывода символьных столбцов в таблице определяется по размеру выбираемых символьных полей. Использование команды `SET WIDTH` позволяет пользователю определять ширину выходного столбца в большую или меньшую сторону. Если параметр `width` не указан, то будет использована ширина столбца по умолчанию для этого столбца.

В следующем примере показано изменение ширины столбца `last_name`. Первый `SELECT` отображается с настройками по умолчанию. В этом случае ширина столбца `last_name` составляет 20 символов (считайте количество символов "`=`" в заголовке). Она задаётся определением столбца `last_name` в таблице `employee`. Второй пример показывает таблицу с шириной, уменьшенной до 10 символов.

[listing]
----
SQL> select emp_no, last_name
CON> from employee
CON> order by last_name
CON> fetch first 5 rows only;

 EMP_NO LAST_NAME
======= ====================
     34 Baldwin
    105 Bender
     28 Bennet
     83 Bishop
    109 Brown

SQL> set width last_name 10;

SQL> select emp_no, last_name
CON> from employee
CON> order by last_name
CON> fetch first 5 rows only;

 EMP_NO LAST_NAME
======= ==========
     34 Baldwin
    105 Bender
     28 Bennet
     83 Bishop
    109 Brown
----

Столбец `emp_no` имеет тип `SMALLINT`. Утилита `isql` не может изменить ширину столбцов, которые не являются символьными типами. В следующем примере команда `set width emp_no 10` не имеет никакого эффекта. В нём также показано отключение настройки ширины для столбца `last_name`.

[listing]
----
SQL> set width last_name;

SQL> set width emp_no 10;

SQL> select emp_no, last_name
CON> from employee
CON> order by last_name
CON> fetch first 5 rows only;

 EMP_NO LAST_NAME
======= ====================
     34 Baldwin
    105 Bender
     28 Bennet
     83 Bishop
    109 Brown
----

[[fbadmgd-isql-commands_show]]
== ISQL SHOW команды

Как объясняется в команде `HELP`, в `isql` есть несколько отдельных команд `SHOW`. Общий синтаксис следующий:

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW <object> [_name_]
----

.Параметры команды `SHOW`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|object
|Тип отображаемого или отображаемых объектов метаданных.

|name
|Наименование объекта метаданных.

|===

Тип объекта метаданных требуется указывать всегда, а имя требуется для отображения сведений о конкретном объекте. Без имени команды обычно отображают все имена объекты запрошенного типа.

В отличие от команд `SET`, нет удобной детализации различных команд `SHOW`, c использованием команды `HELP`. Однако, если вы наберете `SHOW` без аргументов, то вам будет оказана небольшая помощь.

[listing]
----
SQL> show;

Valid options are:
CHECKs                   COMMENTs                 COLLATEs
COLLATIONs               DOMAINs                  DB
DATABASE                 DEPENdency               DEPENdencies
EXCEPtions               FILTERs                  FUNCtions
GENerators               GRANTs                   INDexes
INDICES                  MAPping                  PROCedures
PACKages                 ROLEs                    SYStem
SEQuences                SECURITY CLAsses         SECCLAsses
SCHEmas                  TABLEs                   TRIGgers
USERS                    VIEWs
Command error: show
----

Каждый тип объекта метаданных может быть сокращен до букв, отображаемых заглавными буквами.

[NOTE]
====
Подсказка, выданная командой `SHOW`, содержит несколько ошибок. Например, следующие команды не работают:

* `SHOW SCHEmas` (очевидно зарезервирована для будущих версий, где могут появится схемы);
* `SHOW SECURITY CLAsses`.
====

Команды `SHOW` подробно детализированы и описаны ниже. Где это возможно, приведены примеры из базы данных `employee`.

[[fbadmgd-isql-commands_show-show_check]]
=== SHOW CHECK

.Назначение
Отображение ограничений для указанной таблицы.
(((ISQL, SHOW CHECK)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW CHECKs _table_name_
----

.Параметры оператора SHOW CHECK
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|table_name
|Наименование таблицы для которой требуется отобразить ограничения.

|===

Команда `SHOW CHECKs` отображает все проверочные ограничения, определенные пользователем для заданной таблицы. В отличие от других команд `SHOW`, здесь нет опции для отображения списка всех проверочных ограничений в базе данных. Вы всегда должны указывать имя таблицы как часть команды.

.Использование команды SHOW CHECK
[example]
====
[listing]
----
SQL> show check employee;

CONSTRAINT INTEG_30:
  CHECK ( salary >= (SELECT min_salary FROM job WHERE
                        job.job_code = employee.job_code AND
                        job.job_grade = employee.job_grade AND
                        job.job_country = employee.job_country) AND
            salary <= (SELECT max_salary FROM job WHERE
                        job.job_code = employee.job_code AND
                        job.job_grade = employee.job_grade AND
                        job.job_country = employee.job_country))
----
====

[[fbadmgd-isql-commands_show-show_collations]]
=== SHOW COLLATION

.Назначение
Отображение списка пользовательских параметров сортировок или параметров для указанной сортировки.
(((ISQL, SHOW COLLATION)))(((ISQL, SHOW COLLATE)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {COLLATIONs | COLLATION _collate_name_}

SHOW {COLLATEs | COLLATE _collate_name_}
----

.Параметры оператора SHOW COLLATION
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|collate_name
|Имя определённой пользователем сортировки.

|===

Эти команды отображают список всех параметров для определённых пользователем сортировок в текущей базе данных. В первой форме отображается список всех параметров всех определенных пользователем сортировок. Если указано имя конкретной сортировки, то будут отображаться только её параметры.

.Использование команды SHOW COLLATION
[example]
====
[listing]
----
SQL> show collations;
UNICODE_ENUS_CI, CHARACTER SET UTF8, FROM EXTERNAL ('UNICODE'), PAD SPACE,
CASE INSENSITIVE, 'COLL-VERSION=58.0.6.48'
UNICODE_ENUS_CS, CHARACTER SET UTF8, FROM EXTERNAL ('UNICODE'), PAD SPACE,
'COLL-VERSION=58.0.6.48'

SQL> show collation unicode_enus_ci;
UNICODE_ENUS_CI, CHARACTER SET UTF8, FROM EXTERNAL ('UNICODE'), PAD SPACE,
CASE INSENSITIVE, 'COLL-VERSION=58.0.6.48'
----
====

[NOTE]
====
Выше приведённые результаты не являются частью базы данных `employee`. Некоторые строки в приведенном выше тексте пришлось разделить на две, чтобы они поместились на странице.
====

[[fbadmgd-isql-commands_show-show_comments]]
=== SHOW COMMENTS

.Назначение
Отображение всех комментариев, созданных для различных объектов базы данных.
(((ISQL, SHOW COMMENTS)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW COMMENTs
----

Команда `SHOW COMMENTS` отображает все комментарии, которые были созданы для различных объектов в текущей базе данных. Нет возможности отобразить конкретный комментарий. Каждый комментарий перечисляется вместе с типом объекта и именем, к которому он был применен.

.Использование команды SHOW COMMENTS
[example]
====
[listing]
----
SQL> show comments;

COMMENT ON DATABASE IS This is the demonstration EMPLOYEE database.;
COMMENT ON TABLE EMPLOYEE IS The EMPLOYEE table has details of our employees.;
----
====

Фактический текст комментария отображается между ключевым словом `IS` и конечной точкой с запятой.

[[fbadmgd-isql-commands_show-show_db]]
=== SHOW DATABASE

.Назначение
Отображение информации о текущей базе данных.
(((ISQL, SHOW DATABASE)))(((ISQL, SHOW DB)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {DATABASE | DB}
----

Команда `SHOW DATABASE` (или `SHOW DB`) отображает сведения о текущей базе данных (имя файла, владелец, размер и количество выделенных страниц, интервал очистки, счётчики транзакций, флаг Forced Writes, ODS, зашифрована ли база данных, набор символов по умолчанию).

.Использование команды SHOW DATABASE
[example]
====
[listing]
----
SQL> show database;

Database: employee
        Owner: SYSDBA
PAGE_SIZE 8192
Number of DB pages allocated = 326
Number of DB pages used = 297
Number of DB pages free = 29
Sweep interval = 20000
Forced Writes are OFF
Transaction - oldest = 181
Transaction - oldest active = 214
Transaction - oldest snapshot = 214
Transaction - Next = 218
ODS = 12.0
Database not encrypted
Default Character set: NONE
----
====

[[fbadmgd-isql-commands_show-show_dependencies]]
=== SHOW DEPENDENCIES

.Назначение
Отображение зависимости для указанного объекта базы данных.
(((ISQL, SHOW DEPENDENCIES)))(((ISQL, SHOW DEPENDENCY)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {DEPENdencies | DEPENdency} _object_name_
----

.Параметры оператора SHOW DEPENDENCIES
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|object_name
|Наименование объекта метаданных для которого отображаются зависимости.

|===

Команда `SHOW DEPENDENCIES` отображают все зависимости для указанного имени объекта. Указанное имя объекта может быть таблицей, представлением, хранимой процедурой, функцией, пакетом и т.д.

Выводимый список представляет собой разделенный запятыми список других объектов в базе данных, от которых зависит указанный объект. Другими словами, процедура не сможет компилироваться, если, например, будет удалена какая-либо из перечисленных зависимостей.

[listing]
----
SQL> show dependencies SET_CUST_NO;
        [SET_CUST_NO:Trigger]
CUSTOMER:Table<-CUST_NO, CUST_NO_GEN:Generator
+++
----

Вышеприведенный листинг показывает, что `SET_CUST_NO` является триггером и что он зависит от двух объектов, столбца `CUST_NO` таблицы `CUSTOMER` и последовательности/генератора с именем `CUST_NO_GEN`. Если вы отобразите сам триггер, вы увидите оба упомянутых объекта:

[listing]
----
SQL> show trigger set_cust_no;

Triggers on Table CUSTOMER:
SET_CUST_NO, Sequence: 0, Type: BEFORE INSERT, Active
Trigger text:
=============================================================================
AS
BEGIN
  if (new.cust_no is null) then
    new.cust_no = gen_id(cust_no_gen, 1);
END
=============================================================================
----

Иногда вывод может показаться немного запутанным. Вы можете увидеть различные объекты в списке, которые не кажутся релевантными. Таблица `RDB$DEPENDENCIES`, также содержит сведения об объектах, от которых будет зависеть данный объект.

[[fbadmgd-isql-commands_show-show_domain]]
=== SHOW DOMAIN

.Назначение
Отображение списка имён доменов или определение указанного домена.
(((ISQL, SHOW DOMAIN)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {DOMAINs | DOMAIN _domain_name_}
----

.Параметры оператора SHOW DOMAIN
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|domain_name
|Наименование домена.

|===

Команда `SHOW DOMAIN` отображает информацию о домене. Домен -- это определенный пользователем тип данных, глобальный для базы данных.

Команда `SHOW DOMAIN` имеют две формы. Первая отображает список всех известных доменов в базе данных, а вторая отображает сведения о конкретном домене.

.Использование команды SHOW DOMAIN
[example]
====
[listing]
----
SQL> show domains;

       ADDRESSLINE                            BUDGET
       COUNTRYNAME                            CUSTNO
       DEPTNO                                 EMPNO
       FIRSTNAME                              JOBCODE
       JOBGRADE                               LASTNAME
       PHONENUMBER                            PONUMBER
       PRODTYPE                               PROJNO
       SALARY

SQL> show domain addressline;

ADDRESSLINE                     VARCHAR(30) Nullable
----
====

[[fbadmgd-isql-commands_show-show_exception]]
=== SHOW EXCEPTION

.Назначение
Отображение информации обо всех или указанном исключении.
(((ISQL, SHOW EXCEPTION)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {EXCEPTIONs | EXCEPTION _exception_name_}
----

.Параметры оператора SHOW EXCEPTION
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|exception_name
|Наименование исключения.

|===

Команда `SHOW EXCEPTION` отображает все исключения, которые были определены в текущей базе данных. Отображаются также детальная информации об каждом исключениях: сообщение об ошибке, объекты, которые используют исключение. Вы можете отобразить детальную информацию об отдельном исключении, задав в качестве параметра имя исключения.

.Использование команды SHOW EXCEPTION
[example]
====
[listing]
----
SQL> show exceptions;

Exception Name                  Used by, Type
=============================== =============================================
CUSTOMER_CHECK                  SHIP_ORDER, Stored procedure
Msg: Overdue balance -- can not ship.

CUSTOMER_ON_HOLD                SHIP_ORDER, Stored procedure
Msg: This customer is on hold.

ORDER_ALREADY_SHIPPED           SHIP_ORDER, Stored procedure
Msg: Order status is "shipped."

REASSIGN_SALES                  DELETE_EMPLOYEE, Stored procedure
Msg: Reassign the sales records before deleting this employee.

UNKNOWN_EMP_ID                  ADD_EMP_PROJ, Stored procedure
Msg: Invalid employee number or project id.
----

[listing]
----
SQL> show exception customer_on_hold;

Exception Name                  Used by, Type
=============================== =============================================
CUSTOMER_ON_HOLD                SHIP_ORDER, Stored procedure
Msg: This customer is on hold.
----
====

[[fbadmgd-isql-commands_show-show_filter]]
=== SHOW FILTER

.Назначение
Отображение списка BLOB-фильтров или информации об указанном фильтре.
(((ISQL, SHOW FILTER)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {FILTERs | FILTER _filter_name_}
----

.Параметры оператора SHOW FILTER
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|filter_name
|Наименование BLOB-фильтра.

|===

Команда `SHOW FILTER` отображает список BLOB-фильтров определённых оператором `DECLARE FILTER` или информацию об указанном фильтре.

.Использование команды SHOW FILTER
[example]
====
[listing]
----
SQL> show filter;

    FUNNEL
...

SQL> show filter funnel;

BLOB Filter: FUNNEL
Input subtype: 2 Output subtype: 1
Filter library is myfilterlib
Entry point is blr2asc
----
====

[[fbadmgd-isql-commands_show-show_function]]
=== SHOW FUNCTION

.Назначение
Отображение информации обо всех определённых пользователем функциях или определение указанной функции.
(((ISQL, SHOW FUNCTION)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {FUNCTIONs | FUNCTION _function_name_}
----

.Параметры оператора SHOW FUNCTION
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|function_name
|Наименование функции.

|===

Команда `SHOW FUNCTION` отображает все определённые пользователем функции, а так же их зависимости, т.е. объекты которые используются функцией. Если указано имя функции в качестве параметра, то для будет отображена дополнительная информация, которая зависит от типа функции:

* для внешних Legacy функций будет отображена информация о входных параметрах и возвращаемом результате, имя динамической библиотеки, имя точки входа;
* для PSQL функций будет отображена информация о входных параметрах и возвращаемом результате и тексте функции;
* для внешних UDR функций будет отображена информация о входных параметрах и возвращаемом результате, имени используемого плагина и точке входа.

.Использование команды SHOW FUNCTION
[example]
====
[listing]
----
SQL> show functions;
Global functions

Function Name                     Invalid Dependency, Type
================================= ======= =====================================
F                                         T, Table
GETEXACTTIMESTAMPUTC
ISLEAPYEAR
ISLEAPYEAR_2
SUM_ARGS
----

[listing]
----
SQL> show function isleapyear;

External function ISLEAPYEAR:
Function library is fbudf
Entry point is isLeapYear
Returns  BY VALUE INTEGER
Argument 1: TIMESTAMP
----

[listing]
----
SQL> show function isleapyear_2;
Function text:
=============================================================================
begin
  return mod(extract(year from adate), 4) = 0;
end
=============================================================================
Parameters:
                                  OUTPUT BOOLEAN
ADATE                             INPUT TIMESTAMP


SQL> show function f;
Function text:
=============================================================================
begin
  return (select count(*) from t);
end
=============================================================================
Parameters:
                                  OUTPUT INTEGER
----

[listing]
----
SQL> show function sum_args;
External name: myudr!sum_args
Engine: UDR
Parameters:
                                  OUTPUT INTEGER
N1                                INPUT INTEGER
N2                                INPUT INTEGER
N3                                INPUT INTEGER
----
====

Смотри также: <<fbadmgd-isql-commands_show-show_procedure>>, <<fbadmgd-isql-commands_show-show_trigger>>, <<fbadmgd-isql-commands_show-show_package>>.

[[fbadmgd-isql-commands_show-show_generator]]
=== SHOW GENERATOR

.Назначение
Отображение информации обо всех не системных генераторах (последовательностям) или об одном указанном генераторе (последовательности).
(((ISQL, SHOW GENERATOR)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {GENERATORs | GENERATOR _generator_name_}

SHOW {SEQUENCEs | SEQUENCE _sequence_name_}
----

.Параметры оператора SHOW GENERATOR
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|generator_name, sequence_name
|Наименование генератора (последовательности).

|===

Эти две команды идентичны. Генераторы -- это старый термин Firebird для того, что обычно называют последовательностями в других базах данных, а также в SQL стандарте. Вам рекомендуется использовать последовательности, а не генераторы, но Firebird считает их одинаковыми.

Если имя генератора (последовательности) не указано, то будут выведены сведения обо всех генераторах (имя, текущее значение, начальное значение, значение шага приращения). Если указано имя генератора (последовательности), то будет выведены сведения о конкретном генераторе.

.Использование команды SHOW GENERATOR
[example]
====
[listing]
----
SQL> show generators;
Generator CUST_NO_GEN, current value: 1015, initial value: 0, increment: 1
Generator EMP_NO_GEN, current value: 145, initial value: 0, increment: 1

SQL> show generator emp_no_gen;
Generator EMP_NO_GEN, current value: 145, initial value: 0, increment: 1
----
====

Смотри также: <<fbadmgd-isql-commands_show-show_sequence>>.

[[fbadmgd-isql-commands_show-show_grant]]
=== SHOW GRANT

.Назначение
Отображение список всех разрешений в текущей базе данных или разрешений на указанный объект или разрешений для указанной роли.
(((ISQL, SHOW GRANT)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {GRANTs | GRANT {_object_name_ | _role_name_}}
----

.Параметры оператора SHOW GRANT
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|object_name
|Наименование объекта метаданных, для которого отображаются разрешения.

|role_name
|Наименование роли, для которой отображается список пользователей которым эта роль назначена.

|===

Команда `SHOW GRANT` отображает список всех разрешений в текущей базе данных, если команда используется без параметров. Если в качестве аргумента команды указано имя объекта (таблица, процедура, функция, триггер, и т.д.), то будут отображены разрешения для указанного объекта. Если в качестве аргумента указано имя роли, то будет отображён список пользователей (вместе с оператором разрешения на роль) для которых выдана эта роль.

.Использование команды SHOW GRANT
[example]
====
[listing]
----
SQL> show grants;

/* Grant permissions for this database */
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON COUNTRY
TO PUBLIC WITH GRANT OPTION
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES
ON CUSTOMER TO PUBLIC WITH GRANT OPTION
...
GRANT EXECUTE ON PROCEDURE SHIP_ORDER TO PUBLIC WITH GRANT OPTION
GRANT EXECUTE ON PROCEDURE SHOW_LANGS TO PUBLIC WITH GRANT OPTION
GRANT EXECUTE ON PROCEDURE SUB_TOT_BUDGET TO PUBLIC WITH GRANT OPTION
----

[listing]
----
SQL> show grants employee;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES
ON EMPLOYEE TO PUBLIC WITH GRANT OPTION
----

[listing]
----
SQL> show grants ship_order;
GRANT EXECUTE ON PROCEDURE SHIP_ORDER TO PUBLIC WITH GRANT OPTION
----

[listing]
----
SQL> show grants default_user;
GRANT DEFAULT_USER TO SYSDBA
----
====

[NOTE]
====
Обратите внимание, что некоторые строки в приведенном выше разделены, чтобы они могли поместиться на странице.
====

[[fbadmgd-isql-commands_show-show_indexes]]
=== SHOW INDEXES

.Назначение
Отображение информации обо всех индексах или об указанном индексе.
(((ISQL, SHOW INDEXES)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {INDICES | INDexes}

SHOW {INDICES | INDexes} _table_name_

SHOW INDex _index_name_
----

.Параметры оператора SHOW INDEXES
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|table_name
|Наименование таблицы для которой будет отображён список индексов.

|index_name
|Наименование индекса по которому будет отображена информации.

|===

Первая форма этой команды перечислит все индексы в текущей базе данных. В этой форме вы можете использовать либо `INDEXES`, либо `INDECES`, они рассматриваются в Firebird как идентичные.

Вторая форма команды будет отображать список индексов для указанной таблицы `table_name`. Опять же, вы можете использовать `INDEXES`, либо `INDECES`.

В последней форме команды отображаются сведения о указанном индексе `index_name`, и в этой форме команды необходимо использовать ключевое слово `INDEX`.

.Использование команды SHOW INDEX
[example]
====
[listing]
----
SQL> show indices;
RDB$PRIMARY1 UNIQUE INDEX ON COUNTRY(COUNTRY)
CUSTNAMEX INDEX ON CUSTOMER(CUSTOMER)
CUSTREGION INDEX ON CUSTOMER(COUNTRY, CITY)
...
RDB$PRIMARY24 UNIQUE INDEX ON SALES(PO_NUMBER)
SALESTATX INDEX ON SALES(ORDER_STATUS, PAID)
----

[listing]
----
SQL> show indices employee;
NAMEX INDEX ON EMPLOYEE(LAST_NAME, FIRST_NAME)
RDB$FOREIGN8 INDEX ON EMPLOYEE(DEPT_NO)
RDB$FOREIGN9 INDEX ON EMPLOYEE(JOB_CODE, JOB_GRADE, JOB_COUNTRY)
RDB$PRIMARY7 UNIQUE INDEX ON EMPLOYEE(EMP_NO)
----

[listing]
----
SQL> show index namex;
NAMEX INDEX ON EMPLOYEE(LAST_NAME, FIRST_NAME)
----
====

[[fbadmgd-isql-commands_show-show_mapping]]
=== SHOW MAPPING

.Назначение
Информация локальных и глобальных отображений для объектов безопасности.
(((ISQL, SHOW MAPPING)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {MAPpings | MAPping _mapping_name_ }
----

.Параметры оператора SHOW MAPPING
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|mapping_name
|Имя отображения.

|===

Команда `SHOW MAPPING` выводит информацию обо всех отображениях (локальных и глобальных) для объектов безопасности. Если указано имя отображения, то будет выведена информация только он нём.

.Использование команды SHOW MAPPING
[example]
====
[listing]
----
SQL> show mapping;
WIN_ADMINS USING PLUGIN WIN_SSPI FROM PREDEFINED_GROUP DOMAIN_ANY_RID_ADMINS TO ROLE RDB$ADMIN

*** Global mapping ***
TRUSTED_AUTH USING PLUGIN WIN_SSPI FROM ANY USER TO USER

SQL> show mapping win_admins;
WIN_ADMINS USING PLUGIN WIN_SSPI FROM PREDEFINED_GROUP DOMAIN_ANY_RID_ADMINS TO ROLE RDB$ADMIN
----
====

[[fbadmgd-isql-commands_show-show_package]]
=== SHOW PACKAGE

.Назначение
Отображение списка пакетов или информации об указанном пакете.
(((ISQL, SHOW PACKAGE)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {PACKages | PACKage _package_name_ }
----

.Параметры оператора SHOW PACKAGE
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|package_name
|Имя пакета.

|===

Команда `SHOW PACKAGE` отображает список всех пакетов определенных в текущей базе данных. Если в качестве параметра указано имя пакета, то будет отображён исходный код заголовка и тела пакета.

.Использование команды SHOW PACKAGE
[example]
====
[listing]
----
SQL> show packages;

       CHECK_NAME_UTILS                       DATE_UTILS
       REPL_APPLY_UTILS                       REPL_LOG_UTILS
       REPL_TRIGGERS_UTILS                    REPL_WRITE_LOG

SQL> show package date_utils;

DATE_UTILS
Header source:
BEGIN
  ...
  -- Возвращает строковое представление даты в формате dd MMM yyyy
  FUNCTION DateToChar_Rus(ADate DATE) RETURNS VARCHAR(35);
  -- Возвращает строковое представление даты в формате dd MMM yyyy
  FUNCTION DateToChar_En(ADate DATE) RETURNS VARCHAR(35);
  ...
END

Body source:
BEGIN
  ...
  /**
   * Возвращает строковое представление даты в формате dd MMM yyyy
   */
  FUNCTION DateToChar_Rus(ADate DATE) RETURNS VARCHAR(35)
  AS
  BEGIN
    RETURN EXTRACT(DAY FROM ADate) || ' ' ||
           TRIM (CASE EXTRACT(MONTH FROM ADate)
                  WHEN 1 THEN 'января'
                  WHEN 2 THEN 'февраля'
                  WHEN 3 THEN 'марта'
                  WHEN 4 THEN 'апреля'
                  WHEN 5 THEN 'мая'
                  WHEN 6 THEN 'июня'
                  WHEN 7 THEN 'июля'
                  WHEN 8 THEN 'августа'
                  WHEN 9 THEN 'сентября'
                  WHEN 10 THEN 'октября'
                  WHEN 11 THEN 'ноября'
                  WHEN 12 THEN 'декабря'
               END) || ' ' ||
               EXTRACT(YEAR FROM ADate);
  END

  /**
   * Возвращает строковое представление даты в формате dd MMM yyyy
   */
  FUNCTION DateToChar_En(ADate DATE) RETURNS VARCHAR(35)
  AS
  BEGIN
    RETURN EXTRACT(DAY FROM ADate) || ' ' ||
           TRIM (CASE EXTRACT(MONTH FROM ADate)
                   WHEN 1 THEN 'January'
                   WHEN 2 THEN 'February'
                   WHEN 3 THEN 'March'
                   WHEN 4 THEN 'April'
                   WHEN 5 THEN 'May'
                   WHEN 6 THEN 'June'
                   WHEN 7 THEN 'July'
                   WHEN 8 THEN 'August'
                   WHEN 9 THEN 'September'
                   WHEN 10 THEN 'October'
                   WHEN 11 THEN 'November'
                   WHEN 12 THEN 'December'
               END) || ' ' ||
               EXTRACT(YEAR FROM ADate);
  END
  ...
END
----
====

Смотри также: <<fbadmgd-isql-commands_show-show_function>>, <<fbadmgd-isql-commands_show-show_trigger>>, <<fbadmgd-isql-commands_show-show_procedure>>.

[[fbadmgd-isql-commands_show-show_procedure]]
=== SHOW PROCEDURE

.Назначение
Отображение информации обо всех процедурах в текущей базе данных или об указанной процедуре.
(((ISQL, SHOW PROCEDURE)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {PROCedures | PROCedure _procedure_name_ }
----

.Параметры оператора SHOW PROCEDURE
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|procedure_name
|Имя хранимой процедуры.

|===

Команда `SHOW PROCEDURE` позволяет отобразить список всех хранимых процедур определённых в текущей базе данных и их зависимостей, т.е. объекты которые используются процедурой. Если указано имя хранимой процедуры, то будет отображён её исходный код, а также сведения о входных и выходных параметрах.

.Использование команды SHOW PROCEDURE
[example]
====
[listing]
----
SQL> show procedures;
Global procedures

Procedure Name                    Invalid Dependency, Type
================================= ======= =====================================
ADD_EMP_PROJ                              EMPLOYEE_PROJECT, Table
                                          UNKNOWN_EMP_ID, Exception
ALL_LANGS                                 JOB, Table
                                          SHOW_LANGS, Procedure
...


SQL> show procedure all_langs;
Procedure text:
=============================================================================
BEGIN
        FOR SELECT job_code, job_grade, job_country FROM job
                INTO :code, :grade, :country

        DO
        BEGIN
            FOR SELECT languages FROM show_langs
                    (:code, :grade, :country) INTO :lang DO
                SUSPEND;
            /* Put nice separators between rows */
            code = '=====';
            grade = '=====';
            country = '===============';
            lang = '==============';
            SUSPEND;
        END
    END
=============================================================================
Parameters:
CODE                              OUTPUT VARCHAR(5)
GRADE                             OUTPUT VARCHAR(5)
COUNTRY                           OUTPUT VARCHAR(15)
LANG                              OUTPUT VARCHAR(15)
----
====

Смотри также: <<fbadmgd-isql-commands_show-show_function>>, <<fbadmgd-isql-commands_show-show_trigger>>, <<fbadmgd-isql-commands_show-show_package>>.

[[fbadmgd-isql-commands_show-show_role]]
=== SHOW ROLE

.Назначение
Отображение списка ролей в текущей базе данных, или списка пользователей назначенных указанной роли.
(((ISQL, SHOW ROLE)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {ROLEs | ROLE _role_name_ }
----

.Параметры оператора SHOW ROLE
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|role_name
|Имя роли.

|===

Команда `SHOW ROLE` выводит список ролей в текущей базе данных. Если в качестве аргумента передано имя роли, то будет выведен список пользователей которым назначена указанная роль.

.Использование команды SHOW ROLE
[example]
====
[listing]
----
SQL> show roles;
       R1                                     R2
       R3

SQL> show role r1;
Role R1 is granted to:
U1
U2
----
====

[[fbadmgd-isql-commands_show-show_secclasses]]
=== SHOW SECCLASSES

.Назначение
Отображение информации о классах безопасности для заданного объекта.
(((ISQL, SHOW SECCLASSES)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {SECCLASSES _object_name_ }
----

.Параметры оператора SHOW SECCLASSES
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|object_name
|Имя объекта метаданных.

|===

Команда `SHOW SECCLASSES` отображает информацию о классах безопасности для заданного объекта. В качестве `object_name` может быть передано не только имя таблицы, это может быть имя хранимой процедуры, представления и т.д.

.Использование команды SHOW SECCLASSES
[example]
====
[listing]
----
SQL> show secclasses employee;

Table's main sec class SQL$440
Table's default sec class SQL$DEFAULT54
----
====

[[fbadmgd-isql-commands_show-show_sequence]]
=== SHOW SEQUENCE

.Назначение
Отображение информации обо всех не системных последовательностях или об одной указанной последовательности.
(((ISQL, SHOW SEQUENCE)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {SEQUENCEs | SEQUENCE _sequence_name_}

SHOW {GENERATORs | GENERATOR _generator_name_}
----

.Параметры оператора SHOW SEQUENCE
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|sequence_name
|Наименование последовательности (генератора).

|===

Эти две команды идентичны. Генераторы -- это старый термин Firebird для того, что обычно называют последовательностями в других базах данных, а также в SQL стандарте. Вам рекомендуется использовать последовательности, а не генераторы, но Firebird считает их одинаковыми.

Если имя последовательности ( генератора) не указано, то будут выведены сведения обо всех последовательностях (имя, текущее значение, начальное значение, значение шага приращения). Если указано имя последовательности (генератора), то будет выведены сведения о конкретном последовательности.

.Использование команды SHOW SEQUENCE
[example]
====
[listing]
----
SQL> show sequences;
Generator CUST_NO_GEN, current value: 1015, initial value: 0, increment: 1
Generator EMP_NO_GEN, current value: 145, initial value: 0, increment: 1

SQL> show sequence emp_no_gen;
Generator EMP_NO_GEN, current value: 145, initial value: 0, increment: 1
----
====

Смотри также: <<fbadmgd-isql-commands_show-show_generator>>.

[[fbadmgd-isql-commands_show-show_sql_dialect]]
=== SHOW SQL DIALECT

.Назначение
Отображение SQL диалекта клиента и текущей базы данных.
(((ISQL, SHOW SQL DIALECT)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW SQL DIALECT
----

Команда `SHOW SQL DIALECT` отображает SQL диалект установленный в ISQL и диалект подключенной базы данных.

.Использование команды SHOW SQL DIALECT
[example]
====
[listing]
----
SQL> show sql dialect;
        Client SQL dialect is set to: 3 and database SQL dialect is: 3
----
====

[[fbadmgd-isql-commands_show-show_system]]
=== SHOW SYSTEM

.Назначение
Отображение списка системных объектов.
(((ISQL, SHOW SYSTEM)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW SYStem [{TABLEs | FUNCTIONs | COLLATIONs | COLLATEs}]
----

Команда `SHOW SYSTEM` выводит список внутренних, то есть системных объектов, созданных и используемых в текущей базе данных. По умолчанию отображаются системные таблицы, функции и сортировки. Необязательный параметр позволяет уточнить какой именно вид системных объектов необходимо отобразить.

.Использование команды SHOW SYSTEM
[example]
====
[listing]
----
SQL> show system;

Tables:
       MON$ATTACHMENTS                        MON$CALL_STACK
       MON$CONTEXT_VARIABLES                  MON$DATABASE
...
       SEC$DB_CREATORS                        SEC$GLOBAL_AUTH_MAPPING
       SEC$USERS                              SEC$USER_ATTRIBUTES

Collations:
       ASCII                                  BIG_5
       BS_BA                                  CP943C
       CP943C_UNICODE                         CS_CZ
       CYRL                                   DA_DA
....
       WIN1257_EE                             WIN1257_LT
       WIN1257_LV                             WIN1258
       WIN_CZ                                 WIN_CZ_CI_AI
       WIN_PTBR

SQL> show system tables;

       MON$ATTACHMENTS                        MON$CALL_STACK
       MON$CONTEXT_VARIABLES                  MON$DATABASE
...
       SEC$DB_CREATORS                        SEC$GLOBAL_AUTH_MAPPING
       SEC$USERS                              SEC$USER_ATTRIBUTES
----
====

В Firebird 2.0-2.5 существовали системные функции `RDB$GET_CONTEXT` и `RDB$SET_CONTEXT`, которые позже стали встроенными. В Firebird 2.5 команда `SHOW SYSTEM` отобразит следующее:

[listing]
----
SQL> show system;

Tables:
       MON$ATTACHMENTS                        MON$CALL_STACK
       MON$CONTEXT_VARIABLES                  MON$DATABASE
...

Functions:
       RDB$GET_CONTEXT                        RDB$SET_CONTEXT

Collations:
       ASCII                                  BIG_5
       BS_BA                                  CP943C
....
       WIN_CZ                                 WIN_CZ_CI_AI
       WIN_PTBR
----

Если вы хотите отобразить детали определенного объекта, просто используйте соответствующую команду `SHOW`.

[listing]
----
SQL> show table mon$io_stats;

MON$STAT_ID                     (RDB$STAT_ID) INTEGER Nullable
MON$STAT_GROUP                  (RDB$STAT_GROUP) SMALLINT Nullable
MON$PAGE_READS                  (RDB$COUNTER) BIGINT Nullable
MON$PAGE_WRITES                 (RDB$COUNTER) BIGINT Nullable
MON$PAGE_FETCHES                (RDB$COUNTER) BIGINT Nullable
MON$PAGE_MARKS                  (RDB$COUNTER) BIGINT Nullable

SQL> show collation ascii;

ASCII, CHARACTER SET ASCII, PAD SPACE, SYSTEM
----

[[fbadmgd-isql-commands_show-show_table]]
=== SHOW TABLE

.Назначение
Отображение списка таблиц или информации о заданной таблице.
(((ISQL, SHOW TABLE)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {TABLEs | TABLE _table_name_}
----

.Параметры оператора SHOW TABLE
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|table_name
|Имя таблицы.

|===

В первом варианте команда `SHOW TABLES` отображает список таблиц, определённых в базе данных, в алфавитном порядке. Во втором варианте отображается список столбцов и их типы или домены для указанной в качестве параметра таблицы.

.Использование команды SHOW TABLE
[example]
====
[listing]
----
SQL> show tables;

       COUNTRY                                CUSTOMER
       DEPARTMENT                             EMPLOYEE
       EMPLOYEE_PROJECT                       JOB
       PROJECT                                PROJ_DEPT_BUDGET
       SALARY_HISTORY                         SALES

SQL> show table country;

COUNTRY                         (COUNTRYNAME) VARCHAR(15) Not Null
CURRENCY                        VARCHAR(10) Not Null
CONSTRAINT INTEG_2:
  Primary key (COUNTRY)
----
====

Если для таблицы определены комментарии, эта команда не будет их отображать. Вы можете использовать команду `SHOW COMMENTS`, но помните, что тогда вам будут отображены все комментарии в базе данных. По-видимому, не существует метода извлечения комментариев для одного объекта, если только вы не запросите системные таблицы напрямую.

[listing]
----
SQL> comment on table country is 'This table holds details about countries.';
SQL> commit;

SQL> show comments;
...
COMMENT ON TABLE        COUNTRY IS This table holds details about countries.;
...

SQL> show table country;

COUNTRY                         (COUNTRYNAME) VARCHAR(15) Not Null
CURRENCY                        VARCHAR(10) Not Null
CONSTRAINT INTEG_2:
  Primary key (COUNTRY)

SQL> select rdb$description
CON> from rdb$relations
CON> where rdb$relation_name = 'COUNTRY';

  RDB$DESCRIPTION
=================
            6:1ec
==============================================================================
RDB$DESCRIPTION:
This table holds details about countries.
==============================================================================
----

Вывод последнего запроса выше не идеален, но, по крайней мере, он отображает гораздо меньше информации, когда в вашей базе данных много комментариев.

[[fbadmgd-isql-commands_show-show_trigger]]
=== SHOW TRIGGER

.Назначение
Отображение списка триггеров или подробной информации об указанном триггере.
(((ISQL, SHOW TRIGGER)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {TRIGgers | TRIGger _trigger_name_}
----

.Параметры оператора SHOW TRIGGER
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|trigger_name
|Имя триггера.

|===

Команда `SHOW TRIGGER` отображает список всех триггеров определённых в текущей базе данных. Для табличных триггеров будет выведено имя таблицы для которого был создан триггер.

.Использование команды SHOW TRIGGERS
[example]
====
[listing]
----
SQL> show triggers;
Trigger name                     Invalid
================================ =======
TR_BEFORE_DISCONNECT

Table name                       Trigger name                     Invalid
================================ ================================ =======
AGE                              AGE_BD
AGE                              AGE_BI
AGE                              AGE_BU
AIMTYPE                          TR_AIMTYPE_BI
ALGORITHM                        TR_ALGORITHM_BI
......
----
====

Если указано имя триггера, то будет отображена подробная информация о триггере (имя триггера, порядок срабатывания, событие, активен ли триггер), а также его исходный код.

.Использование команды SHOW TRIGGER
[example]
====
[listing]
----
SQL> show trigger set_cust_no;

Triggers on Table CUSTOMER:
SET_CUST_NO, Sequence: 0, Type: BEFORE INSERT, Active
Trigger text:
=============================================================================
AS
BEGIN
    if (new.cust_no is null) then
    new.cust_no = gen_id(cust_no_gen, 1);
END
=============================================================================
----
====

Смотри также: <<fbadmgd-isql-commands_show-show_function>>, <<fbadmgd-isql-commands_show-show_procedure>>, <<fbadmgd-isql-commands_show-show_package>>.

[[fbadmgd-isql-commands_show-show_users]]
=== SHOW USERS

.Назначение
Отображение списка пользователей в текущей БД безопасности.
(((ISQL, SHOW USERS)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW USERs
----

Команда `SHOW USERS` отображает список пользователей определённых в текущей базе данных безопасности. Если пользователь не является администратором в базе данных безопасности, то будет отображены только сведения о нём самом. Перед каждым именем пользователя указано число, которое отображает количество соединений выполненное этим пользователем. Если перед именем пользователя напечатана решётка "`#`", то это текущий пользователь.

.Использование команды SHOW USERS
[example]
====
[listing]
----
SQL> show users;
Users in the database
  1 #SYSDBA                              2  U1
  0  U3
----
====

В данном случае есть одно соединение пользователем `SYSDBA` -- это текущий пользователь, и два соединения пользователем `U1`.

[[fbadmgd-isql-commands_show-show_version]]
=== SHOW VERSION

.Назначение
Отображение информации о версии ISQL, сервера и ODS базы данных.
(((ISQL, SHOW VERSION)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW VERsion
----

Команда `SHOW VERSION` отображает информацию о версии ISQL, версии сервера Firebird, сетевом протоколе, ODS текущей базы данных.

.Использование команды SHOW VERSION
[example]
====
[listing]
----
SQL> show version;

ISQL Version: WI-V3.0.5.33168 Firebird 3.0
Server version:
Firebird/Windows/AMD/Intel/x64 (access method),
version "WI-V3.0.5.33168 Firebird 3.0"
Firebird/Windows/AMD/Intel/x64 (remote server),
version "WI-V3.0.5.33168 Firebird 3.0/tcp (DESKTOP-E3INAFT)/P15:C"
Firebird/Windows/AMD/Intel/x64 (remote interface),
version "WI-V3.0.5.33168 Firebird 3.0/tcp (DESKTOP-E3INAFT)/P15:C"
on disk structure version 12.0
----
====

Обратите внимание, что некоторые строки в приведенном выше разделены, чтобы они могли поместиться на странице.

[[fbadmgd-isql-commands_show-show_view]]
=== SHOW VIEW

.Назначение
Отображение списка представлений или информации об указанном представлении.
(((ISQL, SHOW VIEW)))

.Синтаксис
[listing,subs="+quotes,attributes"]
----
SHOW {VIEWs | VIEW _view_name_}
----

.Параметры оператора SHOW VIEW
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|view_name
|Имя представления.

|===

Команда `SHOW VIEW` отображает список представлений определённых в текущей базе данных. Если в качестве аргумента указано имя представления, то будет отображён список его столбцов с типами или доменами, и исходный код представления.

.Использование команды SHOW VIEW
[example]
====
[listing]
----
SQL> show views;

       PHONE_LIST

SQL> show view phone_list;

EMP_NO                          (EMPNO) SMALLINT Not Null
FIRST_NAME                      (FIRSTNAME) VARCHAR(15) Not Null
LAST_NAME                       (LASTNAME) VARCHAR(20) Not Null
PHONE_EXT                       VARCHAR(4) Nullable
LOCATION                        VARCHAR(15) Nullable
PHONE_NO                        (PHONENUMBER) VARCHAR(20) Nullable
View Source:
==== ======
SELECT
    emp_no, first_name, last_name, phone_ext, location, phone_no
    FROM employee, department
    WHERE employee.dept_no = department.dept_no
----
====
