[[fbadmgd-isql]]
= Утилита ISQL

(((ISQL)))
В этой главе содержится описание консольной утилиты Firebird Interactive SQL Utility (`isql`) и инструкции по его использованию для выполнения задач в базе данных.

Утилита ISQL расположена в корневом каталоге установки Firebird. Она предоставляет интерфейс командной строки для интерактивного доступа к базе данных Firebird. ISQL принимает операторы DSQL вместе с группой команд `SET` и `SHOW` для запросов и взаимодействия с базой данных Firebird. Некоторые команды `SET` могут быть включены в сценарии DDL для выполнения пакетных операций в `isql`. Она также обрабатывает команды DDL, DML и консоли.

Утилита `isql` может использоваться в трех режимах: в качестве интерактивного сеанса; прямо из командной строки; и как неинтерактивный сеанс, используя сценарий оболочки или пакетный файл. В каждом из режимов могут выполняться разные задачи, как показано ниже:

* В интерактивном режиме пользователь последовательно вводит команды для работы с базами данных и тут же получает результат их выполнения. При этом одна команда может быть разбита на несколько строк. После завершения обработки каждой команды и вывода всех результатов её работы пользователь получает приглашение ввести следующую команду до тех пор, пока не будет введена команда выхода из интерактивного режима `QUIT` или `EXIT`. Утилиту `isql` можно использовать в интерактивном режиме для:

** Создания, редактирования, удаления или просмотра данных и метаданных;
** Ввода файла сценария содержащего пакет SQL запросов;
** Добавлять и модифицировать данные;
** Предоставлять разрешение пользователю и отбирать их;
** Управлять учётными записями;
** Выполнять административные функции базы данных.

* Непосредственно из командной строки, с отдельными параметрами и без запуска интерактивного сеанса. Команды выполняются и по завершении возвращают управление автоматически операционной системе.
* В неинтерактивном сеансе пользователь использует сценарий оболочки или пакетный файл для выполнения функций базы данных.

[NOTE]
====
Поскольку другие приложения в среде Linux, например, MySQL, также используют `isql` в качестве имени утилиты, рекомендуется запускать утилиту Firebird из ее собственного каталога или указывать абсолютный путь к файлу, если у вас есть другая реляционная база данных, кроме Firebird, установленная на вашей машине.

Некоторые из затронутых дистрибутивов, такие как Mint Linux -- на основе Ubuntu -- переименовали Firebird в `isql` в `isql-fb`. Аналогичные изменения могут быть и в других дистрибутивах.

Кроме того, не все дистрибутивы устанавливают Firebird в одно и то же место. Например, OpenSuse устанавливает практически все в `/opt/firebird/3.0`, но Ubuntu и его производные устанавливают его в различные места, но утилиты находятся в `/usr/bin`.
====

Далее предполагается что утилита называется `isql`.

[[fbadmgd-isql-invoking]]
== Запуск isql

Перейдите в корневой каталог установки сервера Firebird и введите в командной строке `isql` (Windows) или `./isql` (Linux). Если каталог с `isql` добавлен в `PATH`, то нет необходимости переходить в него.

Синтаксис запуска `isql` следующий:

[listing,subs="+quotes,macros,attributes"]
----
isql <options> <database>

database ::= [<server spec>]{_db_filename_ | _db_alias_}

<server_spec> ::=
    _host_[/ {_port_ | _service_}]:
  | {backslash}{backslash}__host__\
  | <protocol>://[_host_[:{_port_ | _service_}]/]

<protocol> ::= inet | inet4 | inet6 | xnet
----

Если параметры `&lt;options&gt;` не указаны, `isql` запускает интерактивный сеанс. Если база данных не указана, то необходимо подключиться к существующей базе данных или создать новую. Если база данных была указана, `isql` запускает интерактивный сеанс, подключаясь к указанной базе данных.

Если указаны параметры, `isql` запускается в интерактивном или не интерактивном режиме, в зависимости от параметров. Например, чтение входного файла и запись в выходной файл являются не интерактивными задачами, поэтому параметры `-input` или `-output` не запускают интерактивный сеанс. Дополнительные не интерактивные параметры включают `-a`, `-database`, `-extract` и `-x`, которые используются при извлечении операторов DDL.

Когда вы запускаете интерактивный сеанс `isql`, появляется следующее приглашение:

----
SQL>
----

Вы должны завершить каждую команду символом-терминатором. Терминатором по умолчанию является точка с запятой (`;`). Вы можете изменить терминатор на любой символ или группу символов с помощью команды `SET TERMINATOR` или с помощью параметра командной строки `-terminator`. Если вы опустите терминатор, появится приглашение для продолжения ввода (`CON>`).

Ниже приведен самый простой способ запуска `isql`. После перехода в интерактивный режим вы должны начать с создания новой базы данных или подключения к ней. Сообщение, выданное `isql`, является подсказкой относительно того, что вы должны делать дальше.

----
c:\Firebird\3.0>isql

Use CONNECT or CREATE DATABASE to specify a database
SQL> CONNECT "inet://localhost:3053/employee"
CON> user "SYSDBA" password 'masterkey';
Database: "inet://localhost:3053/employee", User: SYSDBA
SQL>
----

В следующем примере показано, как передать имя базы данных и учетные данные пользователя в командной строке.

----
c:\Firebird\3.0>isql -user sysdba -password masterkey "inet://localhost:3053/employee"

Database: inet://localhost:3053/employee, User: SYSDBA
SQL>
----

В этом примере мы использовали псевдоним для базы данных `employee`. Этот пример предопределен в файле `databases.conf`, который обычно находится в каталоге, в котором установлен Firebird, но некоторые дистрибутивы Linux помещают его в `/etc/firebird/n.n`, где `n.n` -- версия сервера базы данных Firebird. Ниже приведена дополнительная информация о подключении к базам данных с использованием полных путей или псевдонимов.

[[fbadmgd-isql-switches]]
== Переключательи командной строки

Переключатели командной строки -- это аргументы, которые начинаются с символа минус/дефис (`-`). Ниже приведен пример того, что происходит, когда вы пытаетесь запустить `isql` с недопустимым переключателем -- он отображает список допустимых ключей с кратким описанием каждого из них.

----
c:\Firebird\3.0>isql -help
Unknown switch: -help
usage:    isql [options] [<database>]
        -a(ll)                  extract metadata incl. legacy non-SQL tables
        -b(ail)                 bail on errors (set bail on)
        -c(ache) <num>          number of cache buffers
        -ch(arset) <charset>    connection charset (set names)
        -d(atabase) <database>  database name to put in script creation
        -e(cho)                 echo commands (set echo on)
        -ex(tract)              extract metadata
        -f(etch_password)       fetch password from file
        -i(nput) <file>         input file (set input)
        -m(erge)                merge standard error
        -m2                     merge diagnostic
        -n(oautocommit)         no autocommit DDL (set autoddl off)
        -nod(btriggers)         do not run database triggers
        -now(arnings)           do not show warnings
        -o(utput) <file>        output file (set output)
        -pag(elength) <size>    page length
        -p(assword) <password>  connection password
        -q(uiet)                do not show the message "Use CONNECT..."
        -r(ole) <role>          role name
        -r2 <role>              role (uses quoted identifier)
        -s(qldialect) <dialect> SQL dialect (set sql dialect)
        -t(erminator) <term>    command terminator (set term)
        -tr(usted)              use trusted authentication
        -u(ser) <user>          user name
        -x                      extract metadata
        -z                      show program and server version
----

[NOTE]
====
Требуются только начальные символы в опции. Вы можете ввести любую часть текста, заключенную в скобки, включая полное имя опции. Например, указание `-n`, `-no` или `-noauto` имеет тот же эффект.
====

.Переключатели командной строки
[[fbadmgd-isql-switches-tbl]]
[cols="<1,<4", options="header",stripes="none"]
|===
^|Опция
^|Описание

|-a(ll)
|Извлечение всех метаданных, включая не-SQL объекты. Используется совместно с командой `extract`.

|-b(ail)
|Этот переключатель указывает утилите передать ошибку в ОС, но только в пакетном режиме (`SET BAIL ON`). Он был добавлен, чтобы предотвратить выполнение сценариев `isql` после обнаружения ошибки. Дальнейшие операторы не будут выполняться, и `isql` вернет код ошибки в ОС.

Пользователям по-прежнему необходимо использовать переключатель `-e(cho)` для вывода команд в выходной файл, чтобы выделить точный оператор, вызвавший ошибку.

Когда сервер предоставляет информацию о строках и столбцах, пользователи могут найти точную строку в DML скрипте, вызвавшую проблему. Когда сервер указывает только ошибку, то пользователи могут увидеть только первую строку оператора, вызвавшего сбой по отношению ко сему сценарию.

Эта функция также поддерживается во вложенных скриптах. Например, сценарий A включает в себя сценарий B, а сценарий B вызывает ошибку, номер строки связан со сценарием B. Когда сценарий B полностью прочитан, `isql` продолжает считать строки, относящиеся к сценарию A, поскольку каждый файл получает отдельный счетчик строк. Сценарий A включает сценарий B, когда сценарий A использует команду `INPUT` для загрузки сценария B.

|-c(ache) _n_
|Задаёт количество страниц, которые будут кэшированы при соединении с БД.

|-ch(arset) _charset_
|Задаёт кодировку для текущего соединения. Это же можно сделать с использовании команды `SET NAMES`.

|-d(atabase) _database_
a|Используется совместно с переключателем `-x` или `-ex`. Изменяет оператор `CREATE DATABASE`, который извлекается в файл:

* Без переключателя `-d` оператор `CREATE DATABASE` извлекается в скрипт как комментарий в стиле C, и использует имя базы данных указанное в командной строке `isql`;
* С переключателем `-d` оператор `CREATE DATABASE` извлекается не закомментированным, и подставляет имя базы данных указанное в переключателе.

|-e(cho)
|Включает дублирование команд на указанное устройство вывода (монитор, в файл, и т.д.). Это можно сделать и с использованием команды `SET ECHO ON`.

|-ex(tract)
|Извлечение метаданных из базы данных. Его можно использовать вместе с ключом `-o(utput)` для извлечения информации в указанный выходной файл.

|-f(etch_password) _pwd_file_
|Извлечение пароля из файла.

|-i(nput) _file_
|Задаёт файл с SQL-скриптом для выполнения. Файлы скриптов могут содержать команду `SET INPUT` для включения других файлов.

|-m(erge_stderr)
|Перенаправление ошибок (stderr) на поток стандартного вывода. Ключ командной строки `-m(erge)` может использоваться для включения сообщений об ошибках в выходные файлы.

|-m2
|Отправлять информацию о статистике и планах в выходной файл, который указан в переключателе `-o(utput)`. Ключ командной строки `-m2` гарантирует, что статистика и информация о плане, полученные из команд `SET STATS`, `SET PLAN` и `SET PLANONLY`, также отправляются в выходной файл, а не просто возвращаются в консоль.

|-n(oautocommit)
|Отключить автоматическое подтверждение DDL-операций. По умолчанию операторы DDL фиксируются автоматически в отдельной транзакции. Может быть изменено командой `SET AUTODDL OFF`.

|-nod(btriggers)
|Не запускать триггеры базы данных.

|-now(arnings)
|Не показывать предупреждения.

|-o(utput) _file_
|Задаёт файл для вывода результата выполнения запросов. Без аргументов перенаправляет вывод на стандартное устройство вывода (монитор). Может быть изменён так же командой `SET OUTPUT`.

|-pag(elength) _size_
|Размер печатной страницы. Печатает заголовки столбцов каждые _size_ строк вместо значения по умолчанию 20.

|-p(assword) _password_
|Пароль пользователя при подключении к базе данных.

|-q(uiet)
|Не показывать сообщение "`Use CONNECT...`".

|-r(ole) _role_
|Задаёт имя роли при подключении к базе данных.

|-r2 _role_
|Задаёт имя роли (с использованием квотированных идентификаторов). Этот переключатель можно использовать для указания имени роли с учетом регистра.

По умолчанию для передачи роли используется переключатель `-r(ole)`. В этом случае роль, представленная в командной строке, пишется в верхнем регистре. Если используется переключатель `-r2`, то роль передаются в движок в точности так, как это указано в командной строке.

|-s(qldialect) _dialect_
|Устанавливает SQL диалект к котором интерпретируются последующие команды до конца сеанса или до тех пор, пока диалект не будет изменён с помощью инструкции `SET SQL DIALECT`.

|-t(erminator) _term_
|Изменяет символ конца оператора (терминатора) с точки с запятой "`;`" по умолчанию на `_term_`, где `_term_` -- любой символ или последовательность символов. Тоже самое можно сделать использую команду `SET TERM`.

|-tr(usted)
|Использовать доверительную аутентификацию.

|-u(ser) _user_
|Имя пользователя для подключения к базе данных.

|-x
|Извлечение метаданных из базы данных. Его можно использовать вместе с ключом `-o(utput)` для извлечения информации в указанный выходной файл.

|-z
|Показать версии утилиты и сервера.

|===

=== Примеры использования переключателей в isql

.Выполнение скрипта создания базы данных
[example]
====
[source,bash]
----
isql -input createdb.sql
----
====

.Запуск интерактивного сеанса с подключением к удалённой базе данных
[example]
====
В следующем примере начинается интерактивное соединение с удаленной базой данных. Удаленный сервер jupiter, принимает указанную комбинацию пользователя и пароля с привилегиями, назначенными роли `STAFF`:

[source,bash]
----
isql -user sales -password mycode -role staff 'jupiter:/usr/customer.fdb'
----
====

.Запуск интерактивного сеанса без подключения к базе данных
[example]
====
Следующий пример запускает интерактивный сеанс, но не подключается к базе данных. Все введенные команды `isql` выводятся на печать, а результаты запроса печатают заголовки столбцов каждые 30 строк. Соединение с базой данных по умолчанию использует кодировку `UTF8`.

[source,bash]
----
isql -ch utf8 -echo -page 30
----
====

[[fbadmgd-isql-start-session]]
== Начало сессии isql

Чтобы начать сеанс `isql`, введите параметры командной строки и имя базы данных в оболочке Linux/Unix или командной консоли Windows. Например:

[source,bash]
----
isql -user SYSDBA -password masterkey inet4://localhost/mydatabase
----

При подключении к локальной базе данных в embedded варианте достаточно указать только имя пользователя (пароль будет проигнорирован):

[source,bash]
----
isql -user SYSDBA employee.db
----

В Windows вы можете использовать доверительную аутентификацию, при условии что она настроена в `firebird.conf` или `databases.conf`:

[source,bash]
----
isql -trusted inet4://localhost/mydatabase
----

Если параметры `&lt;options&gt;` не указаны, `isql` запускает интерактивный сеанс. Если база данных не указана, то необходимо подключиться к существующей базе данных или создать новую. Если база данных была указана, `isql` запускает интерактивный сеанс, подключаясь к указанной базе данных.

Чтение входного файла и запись в выходной файл не считаются интерактивными задачами, поэтому параметры командной строки `-input` или `-output` не инициируют интерактивный сеанс. Опции, используемые для извлечения операторов DDL, такие как `-a` и `-x`, также инициируют только неинтерактивный сеанс.

Утилита `isql` может быть запущена с локального или удаленного клиента:

* При подключении с использованием локального клиента вы можете установить переменные среды `ISC_USER` и `ISC_PASSWORD`.
* При подключении с удаленного клиента вам потребуется указать действительные имя и пароль.

[[fbadmgd-isql-end-session]]
== Завершение сессии isql

(((ISQL, QUIT)))(((ISQL, EXIT)))
Существует два способа выхода из isql:

* Если вы хотите откатить всю неподтвержденную работу и выйти из isql, введите в командной строке следующую команду `QUIT`;
* Если вы хотите зафиксировать всю свою работу перед выходом из isql, введите следующую команду `EXIT`.

[[fbadmgd-isql-help]]
== Получение справки

(((ISQL, HELP)))
Утилита `isql` поддерживает команду `HELP`. Она дает краткую информацию о большинстве доступных команд. Команда `HELP` также позволяет перейти к более подробной информации. Чтобы активировать справочную систему, просто введите `HELP` в командной строке, как показано ниже:

----
SQL> HELP;
----

----
Frontend commands:
BLOBDUMP <blobid> <file>   -- dump BLOB to a file
BLOBVIEW <blobid>          -- view BLOB in text editor
EDIT     [<filename>]      -- edit SQL script file and execute
EDIT                       -- edit current command buffer and execute
HELP                       -- display this menu
INput    <filename>        -- take input from the named SQL file
OUTput   [<filename>]      -- write output to named file
OUTput                     -- return output to stdout
SET      <option>          -- (Use HELP SET for complete list)
SHELL    <command>         -- execute Operating System command in sub-shell
SHOW     <object> [<name>] -- display system information
    <object> = CHECK, COLLATION, DATABASE, DOMAIN, EXCEPTION, FILTER, FUNCTION,
               GENERATOR, GRANT, INDEX, PACKAGE, PROCEDURE, ROLE, SQL DIALECT,
               SYSTEM, TABLE, TRIGGER, VERSION, USERS, VIEW
EXIT                       -- exit and commit changes
QUIT                       -- exit and roll back changes

All commands may be abbreviated to letters in CAPitals
----

(((ISQL, HELP, SET)))
Большинство из этих команд не имеют дальнейших уровней детализации, в то время как команда `SET` имеет. Чтобы углубиться в эти дополнительные уровни, выполните следующие действия:

----
HELP SET;
----

----
Set commands:
    SET                    -- display current SET options
    SET AUTOddl            -- toggle autocommit of DDL statements
    SET BAIL               -- toggle bailing out on errors in non-interactive mode
    SET BLOB [ALL|<n>]     -- display BLOBS of subtype <n> or ALL
    SET BLOB               -- turn off BLOB display
    SET COUNT              -- toggle count of selected rows on/off
    SET MAXROWS [<n>]      -- limit select stmt to <n> rows, zero is no limit
    SET ECHO               -- toggle command echo on/off
    SET EXPLAIN            -- toggle display of query access plan in the explained form
    SET HEADING            -- toggle display of query column titles
    SET LIST               -- toggle column or table display format
    SET NAMES <csname>     -- set name of runtime character set
    SET PLAN               -- toggle display of query access plan
    SET PLANONLY           -- toggle display of query plan without executing
    SET SQL DIALECT <n>    -- set sql dialect to <n>
    SET STATs              -- toggle display of performance statistics
    SET TIME               -- toggle display of timestamp with DATE values
    SET TERM <string>      -- change statement terminator string
    SET WIDTH <col> [<n>]  -- set/unset print width to <n> for column <col>

All commands may be abbreviated to letters in CAPitals
----

Если вы попытаетесь углубиться в какую-либо другую команду, эффект будет точно таким же, как при выполнении только команды `HELP`.

[NOTE]
====
Команда `HELP SET` даёт справку только по собственным командам `isql`. Для управляющих SQL операторов, таких как `SET TRANSACTION` или `SET ROLE` подсказка не будет выведена.
====

[[fbadmgd-isql-connect]]
== Соединение с базой данных

(((ISQL, CONNECT)))
Если при запуске `isql` вы не указали спецификацию для подключения к базе данных, то будет выдана подсказка о том что необходимо соединиться с базой данных с помощью оператора `CONNECT` или создать новую базу данных с помощью оператора `CREATE DATABASE`.

Оператор `CONNECT` не является частью DSQL и доступен только внутри ISQL, а потому не описан в "`Руководство по языку SQL Firebird`". Рассмотрим его синтаксис.

.Синтаксис
[listing,subs="+quotes,attributes"]
----
CONNECT <database>
  [USER _username_ [PASSWORD _password_]]
  [CACHE _cache_size_]
  [ROLE _rolename_]

<database> ::= [<server spec>] {_db_filename_ | _db_alias_}

<server spec> ::=
    _host_[\{_port_ | _service_}]:
  | {backslash}{backslash}__host__[@{_port_ | _service_}]\
  | <protocol>://[_host_[:{_port_ | _service_}]/]

<protocol> ::= inet | inet4 | inet6 | wnet | xnet
----

.Параметры оператора `CONNECT`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|db_filename
|Полный путь и имя файла, включая расширение. Имя файла должно быть задано в соответствии со спецификой используемой платформы.

|db_alias
|Псевдоним (alias) базы данных, присутствующий в файле `databases.conf`.

|username
|Имя пользователя для соединения с базой данных. Может быть заключено в одинарные или двойные кавычки. Если имя пользователя заключено в двойные кавычки, то оно чувствительно к регистру.

|password
|Имя пользователя для соединения с базой данных. Может быть заключено в одинарные или двойные кавычки. Если имя пользователя заключено в двойные кавычки, то оно чувствительно к регистру.

|cache_size
|Размер страничного кеша.

|rolename
|Имя роли для соединения с базой данных. Может быть заключено в одинарные или двойные кавычки. Если имя роли заключено в двойные кавычки, то оно чувствительно к регистру.

|server spec
|Спецификация удалённого сервера. Включает в себя имя сервера и протокол.

|host
|Имя сервера или IP адрес, на котором расположена база данных.

|port
|Номер порта, который слушает удалённый сервер (параметр `RemoteServicePort` файла `firebird.conf`.

|service
|Имя сервиса. Должно совпадать со значением параметра `RemoteServiceName` файла `firebird.conf`.

|protocol
|Наименование протокола.

|===

База данных может состоять из одного или нескольких файлов. Первый, основной, файл называется первичным, остальные файлы -- вторичными. При подключении к базе данных необходимо указывать только путь до первичного файла базы данных.

Спецификация первичного файла -- имя файла базы данных и его расширение с указанием к нему полного пути в соответствии с правилами используемой операционной системы.

[[fbadmgd-isql-connect-aliasedb]]
=== Использование псевдонимов БД

Вместо полного пути к первичному файлу базы можно использовать псевдонимы (aliases). Псевдонимы описываются в файле `databases.conf` в формате:

[listing,subs="+quotes,attributes"]
----
_alias_ = _filepath_
----

[NOTE]
====
Помимо указания псевдонимов для базы данных в этом файле можно задать параметры уровня базы данных для каждой описываемой базы данных. Эти параметры задаются в фигурных скобках сразу после объявления псевдонима. Подробнее читайте <<fbadmgd-config-perdb>>.
====

[[fbadmgd-isql-connect-remotely]]
=== Соединение с БД на удалённом сервере

При соединении с базой данных на удалённом сервере необходимо указать спецификацию удалённого сервера. Спецификация удалённого сервера зависит от используемого протокола.

Если вы при соединении с базой данных используете протокол TCP/IP, то строка соединения должна выглядеть следующим образом:

[listing,subs="+quotes,attributes"]
----
_host_[/{_port_ | _service_}]:{_filepath_ | _db_alias_}
----

Если вы при соединении с базой данных используете протокол под названием именованные каналы (Name Pipes), то строка соединения должна выглядеть следующим образом.

[listing,subs="+quotes,attributes"]
----
{backslash}{backslash}__host__[@{_port_ | _service_}]\{_filepath_ | _db_alias_}
----

Существует также унифицированный URL-подобный синтаксис спецификации удалённого сервера. В этом синтаксисе первым параметром указывается наименование протокола, далее указывается имя сервера или IP адрес, номер порта и путь к первичному файлу базы данных или псевдоним. В качестве протокола можно указать следующие значения:

* `inet` -- TCP/IP (сначала пробует подключится по протоколу TCP/IP v6, если не получилось, то TCP/IP v4);
* `inet4` -- TCP/IP v4 (начиная с 3.0.1);
* `inet6` -- TCP/IP v6 (начиная с 3.0.1);
* `wnet` -- NetBEUI или протокол именованных каналов;
* `xnet` -- локальный протокол.

[listing,subs="+quotes,attributes"]
----
<protocol>://[_host_[:{_port_ | _service_}]/]{_filepath_ | _db_alias_}
----

[[fbadmgd-isql-connect-user]]
=== Имя пользователя, пароль и роль

Необязательные предложения `USER` и `PASSWORD` задают, соответственно, имя и пароль пользователя присутствующего в базе данных безопасности (`{secdb}` или той, что указана в параметре `SecurityDatabase`). Пользователя и пароль можно не указывать, если установлены переменные окружения `ISC_USER` и `ISC_PASSWORD`. Их также можно не указывать при использовании доверительной аутентификации.

Если подключение происходит к embedded версии сервера, то достаточно указать только имя пользователя (проверка пароля не производится).

Необязательное предложение `ROLE` задаёт имя роли, права которой будут учитываться при подключении базы данных. Роль должна быть назначена пользователю в соответствующей базе данных безопасности.

[[fbadmgd-isql-connect-charset]]
=== Набор символов

Команда `CONNECT` не позволяет указать набор символов для подключения, однако вы можете это сделать с помощью команды `SET NAMES`, которую необходимо ввести до использования `CONNECT`.

[[fbadmgd-isql-connect-examples]]
=== Примеры

.Подключение к локальной (embedded) базе данных
[example]
====
В следующем примере происходит подключение к базе данных в embedded варианте с использованием имени пользователя из переменной среды `ISC_USER`:

[source,sql]
----
CONNECT "C:\DATABASES\FIREBIRD\MY_EMPLOYEE.FDB";
----

В Linux это будет выглядеть следующим образом:

[source,sql]
----
CONNECT "/databases/firebird/MY_EMPLOYEE.FDB";
----

При использовании псевдонимов, настроенных в `databases.conf`:

[source,sql]
----
CONNECT MY_EMPLOYEE;
----

Если переменная окружения `ISC_USER` не задана, или требуется указать другого пользователя, то необходимо использовать предложение `USER`:

[source,sql]
----
CONNECT MY_EMPLOYEE USER SYSDBA;
----
====

.Подключение к локальной (не embedded) базе данных
[example]
====
На Windows можно использовать локальный протокол XNET:

[source,sql]
----
CONNECT xnet://MY_EMPLOYEE USER SYSDBA PASSWORD 'masterkey';
----

Во всех операционных системах через TCP:

[source,sql]
----
CONNECT inet://localhost/MY_EMPLOYEE USER SYSDBA PASSWORD 'masterkey';
----
====

.Подключение к удалённой базе данных с ролью RDB$ADMIN
[example]
====
[source,sql]
----
CONNECT inet://dbserver/MY_EMPLOYEE USER BOB PASSWORD 'W45xs' ROLE RDB$ADMIN;
----
====

.Подключение к удалённой базе данных с набором символов WIN1251
[example]
====
[source,sql]
----
SET NAMES WIN1251;
CONNECT inet://dbserver/MY_EMPLOYEE USER BOB PASSWORD 'W45xs';
----
====

[[fbadmgd-isql-create-db]]
== Создание базы данных

Если при запуске `isql` вы не указали спецификацию для подключения к базе данных, то будет выдана подсказка о том что необходимо соединиться с базой данных с помощью оператора `CONNECT` или создать новую базу данных с помощью оператора `CREATE DATABASE`.

Оператор `CREATE DATABASE` является частью DSQL и подробно описан в "`Руководство по языку SQL Firebird`", поэтому здесь будет приведён только краткий синтаксис и примеры использования.

.Синтаксис
[listing,subs="+quotes,attributes"]
----
CREATE DATABASE <filespec>
  [<db_initial_option> [<db_initial_option> ...]]
  [<db_config_option> [<db_config_option> ...]]

<db_initial_option> ::=
    USER _username_
  | PASSWORD '_password_'
  | ROLE _rolename_
  | PAGE_SIZE [=] _size_
  | SET NAMES '_charset_'

<db_config_option> ::=
    DEFAULT CHARACTER SET _default_charset_
      [COLLATION _collation_]
  | DIFFERENCE FILE '_diff_file_'


<filespec> ::= '[<server_spec>]{_filepath_ | _db_alias_}'

<server_spec> ::=
    _host_[/{_port_ | _service_}]:
  | {backslash}{backslash}__host__[@{_port_ | _service_}]\
  | <protocol>://[_host_[:{_port_ | _service_}]/]

<protocol> ::= inet | inet4 | inet6 | xnet | wnet
----

В следующем примере будет создана база данных `monkey.fdb` и сохранена в директории `test` на диске `С`.

[source,sql]
----
CREATE DATABASE 'C:\test\monkey.fdb' page_size 8192
user 'SYSDBA' password 'masterkey';
----

[NOTE]
====
* Путь к базе данных и пароль обязательно должны быть заключены в одинарные или двойные кавычки. Для имени пользователя, пароля и набора символов кавычки необязательны. При использовании двойных кавычек буду использованы правила 3-диалекта, т.е. имя пользователя, роли и набора символов будут чувствительны к регистру символов.
* Поскольку база данных создаётся в режиме embedded сервера, то файл базы данных будет создан с именем входа в систему в качестве владельца. Это может вызвать проблемы с доступом к файлу базы данных для других пользователей, особенно в Linux, которые могут захотеть подключится позднее. Если база данных создаётся с использованием сетевого или локального (Windows) протокола, то файл базы данных будет создан от имени пользователя службы (в Linux это пользователь firebird)
====

В данном случае база данных будет создана с использованием embedded версии Firebird. Для использования сетевых протоколов вы можете использовать префиксы протоколов или другие правила аналогичные правила для оператора `CONNECT`.

.Создание базы данных на удалённом сервере
[example]
====
Создание базы данных на удалённом сервере baseserver расположенном по пути, на который ссылается псевдоним test, описанный в файле `databases.conf`. Используется протокол TCP. Владельцем базы данных будет пользователь wizard.

[source,sql]
----
CREATE DATABASE 'baseserver:test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

То же самое с использованием унифицированного URL-подобного синтаксиса задания спецификации удалённого сервера.

[source,sql]
----
CREATE DATABASE 'inet://baseserver:3050/test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

или

[source,sql]
----
CREATE DATABASE 'inet://baseserver:gds_db/test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

Начиная с Firebird 3.0.1 можно указать какой именно из протоколов IP v4 или IP v6 вы хотите использовать.

[source,sql]
----
CREATE DATABASE 'inet4://baseserver/test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

или

[source,sql]
----
CREATE DATABASE 'inet6://baseserver/test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

Создание базы данных с указанием IP адреса (IPv4) вместо указания имени сервера.

[source,sql]
----
CREATE DATABASE '127:0:0:1:test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

Создание базы данных с указанием IP адреса (IPv6) вместо указания имени сервера.

[source,sql]
----
CREATE DATABASE '[::1]:test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----
====

[NOTE]
====
В отличие от оператора `CONNECT` в операторе `CREATE DATABASE` вы сразу можете указать набор символов, который будет использован в подключении после выполнения оператора `CREATE DATABASE` с помощью предложения `SET NAMES`.
====

После создания базы данных вы можете выполнять к ней запросы в интерактивном режиме.

[listing]
----
SQL>SELECT RDB$RELATION_ID FROM RDB$DATABASE;

RDB$RELATION_ID
===============
128

SQL> commit;
----

Чтобы вернуться в командную строку введите команду `EXIT` или `QUIT`.

[NOTE]
====
Вышеуказанная методика, как показано, работает, но в идеале базы данных и объекты метаданных должны создаваться и поддерживаться с использованием сценариев определения данных.
====

[[fbadmgd-isql-env]]
== Установка переменных окружения ISC_USER и ISC_PASSWORD

Переменная среды -- это именованный объект, который содержит информацию, используемую одним или несколькими приложениями. Они глобальны для своих конкретных операционных систем. Сервер Firebird распознает и использует определенные переменные среды, настроенные в Windows, Linux и других системах Unix.

Переменные среды `ISC_USER` и `ISC_PASSWORD` в Firebird предназначены для предоставления SYSDBA доступа к базе данных из служебных программ командной строки и клиентских приложений всем, кто имеет доступ к хост-машине.

[CAUTION]
====
При запуске таких утилит командной строки, как `isql`, `gbak`, `gstat` и `gfix`, Firebird будет искать, установлены ли переменные среды `ISC_USER` и `ISC_PASSWORD`. Если вы не предоставите имя пользователя и пароль при локальном подключении к базе данных, Firebird позволит вам войти в систему, если найдет эти переменные.

Из соображений безопасности не рекомендуется указывать имя пользователя и пароль `SYSDBA` с использованием этих двух переменных среды, особенно на незащищенном компьютере.
====

Переменные среды `ISC_USER` и `ISC_PASSWORD` могут быть установлены для локального запуска `isql`. Чтобы установить переменные среды:

* В Windows это делается в menu:Панели управления[Система > Дополнительно > Переменные среды]. Любые изменения, сделанные здесь, будут постоянными. Вы также можете определить эти переменные в командном окне до запуска любой из утилит Firebird, например `isql`. Например:
+
[listing]
----
C:\> set ISC_USER=sysdba
C:\> set ISC_PASSWORD=secret
C:\> isql my_employee

SQL>
----

* На платформах Linux и Unix это зависит от типа используемой оболочки и от конфигурации настольного компьютера. Обратитесь к документации вашей операционной системы, чтобы установить переменные среды. Для оболочки bash этот процесс показан в следующем примере:
+
[listing]
----
cosmos> export ISC_USER=sysdba
cosmos> export ISC_PASSWORD=secret
cosmos> /opt/firebird/bin/isql my_employee

SQL>
----

[[fbadmgd-isql-sql_dialect]]
== SQL диалект

Firebird поддерживает три диалекта SQL на каждом клиенте и сервере базы данных. Эти диалекты SQL различаются в контексте формата даты и времени и точности числового типа данных. Диалекты служат для инструктирования сервера Firebird о том, как обрабатывать функции, реализованные в устаревших базах данных Borland Interbase, более ранних, чем версия 6.0. Диалекты устанавливаются во время выполнения и могут быть изменены для клиента во время подключения или с помощью команды `SET SQL DIALECT`.

* Диалект 1 предназначен исключительно для обеспечения обратной совместимости с устаревшими базами данных из очень старых версий InterBase, v.5 и ниже. Базы данных Dialect 1 сохраняют определенные языковые особенности, которые отличаются от Dialect 3, используемого по умолчанию для баз данных Firebird.
** Информация о дате и времени хранится в типе данных `DATE`. Имеется тип данных `TIMESTAMP`, который идентичен `DATE`.
** Двойные кавычки могут использоваться как альтернатива апострофам для разделения строковых данных. Это противоречит стандарту SQL - двойные кавычки зарезервированы для особых синтаксических целей как в стандартном SQL, так и в диалекте 3. Поэтому строки с двойными кавычками следует избегать.
** Точность типов данных `NUMERIC` и `DECIMAL` меньше, чем в 3-м диалекте и в случае, если значение точности более 9, Firebird хранит такие значения как длинные значения с плавающей точкой.
** `BIGINT` не является доступным типом данных.
** Идентификаторы нечувствительны к регистру и всегда должны соответствовать правилам для обычных идентификаторов.
** Хотя значения генератора хранятся как 64-битные целые числа, запрос клиента Dialect 1, например, `SELECT GEN_ID (MyGen, 1)`, вернет значение генератора, усеченное до 32 бит.

* Диалект 2 доступен только в клиентском соединении к Firebird и не может быть применён к базе данных. Он предназначен для того, чтобы помочь в отладке в случае возможных проблем с целостностью данных при проведении миграции с диалекта 1 на 3.

* В базах данных Диалекта 3:
** Числа с типами данных `DECIMAL` и `NUMERIC` хранятся как длинные значения с фиксированной точкой (масштабируемые целые числа) в случае если точность числа больше 9.
** Тип данных `TIME` доступен и используется для хранения значения только времени.
** Тип данных `DATE` хранит информацию только о дате.
** Тип данных `BIGINT` доступен в качестве целого 64-х битного типа данных.
** Двойные кавычки могут использоваться, но только для идентификаторов, которые являются зависимыми от регистра, а не для строковых данных.
** Все строки должны быть разделены одинарными кавычками (апострофам).
** Значения генераторов возвращаются как 64-битное целое.

[IMPORTANT]
====
Для вновь разрабатываемых баз данных и приложений настоятельно рекомендуется использовать 3-й диалект. Диалект при соединении с базой данных должен быть таким же, как и базы данных. Исключением является случай миграции с 1-го в 3-й диалект, когда в строке соединения с базой данных используется 2-й диалект.
====

При подключении к базе данных с использованием `isql` утилита использует диалект базы данных, если не указано иное. Диалекты не могут быть установлены в качестве параметра оператора `CREATE DATABASE`. Таким образом, при создании базы данных с использованием `isql` база данных будет на диалекте, который является текущим в `isql` во время выполнения оператора `CREATE DATABASE`. Вы можете установить диалект с помощью утилиты `isql` двумя способами:

* При старте `isql` укажите диалект с использованием переключателя `-sql_dialect`:
+
[listing]
----
isql -sql_dialect 3
----

* Внутри sql скрипта или в `isql` сессии с помощью команды `SET SQL DIALECT`:
+
[listing]
----
SQL> SET SQL DIALECT 3;
----

[[fbadmgd-isql-terminator]]
== Символ терминатора

Символом терминатором по умолчанию для базы данных Firebird является точка с запятой "`;`". Операторы будут только выполнены если они заканчиваются точкой с запятой. Однако вы можете использовать `isql` для изменения символа на любой печатный символ или несколько символов из первых 127 символов подмножества ASCII с помощью команды `SET TERM`.

[NOTE]
====
Терминатор по умолчанию может быть изменен во всех случаях, за исключением Procedural SQL или PSQL. PSQL не принимает никаких терминаторов, кроме точки с запятой.
====

Для изменения символа терминатора на тильду "`~`" введите следующую команду:

[source,sql]
----
SET TERM ~;
----

Для возврата терминатора, вы должны использовать текущий терминатор! Изменение терминатора полезно, если вы хотите ввести функцию PSQL, как показано в следующем примере. Поскольку PSQL будет принимать только точку с запятой в качестве терминатора, `isql` должен знать, какая точка с запятой используется для кода PSQL, а какая используется для завершения вводимых команд SQL.

[source,sql]
----
SQL> set term ~ ;

SQL> create procedure test_proc (iInput integer = 666)
CON> returns (oOutput integer)
CON> as
CON> begin
CON>   oOutput = iInput;
CON>   suspend;
CON> end~

SQL> set term ; ~

SQL> commit;

SQL> select * from test_proc;

     OOUTPUT
============
         666
----

Вы можете видеть, что внутри кода самой процедуры терминатором является точка с запятой. Однако вне фактического кода процедуры терминатором является тильда (~). `isql` обрабатывает одну команду `CREATE PROCEDURE`, но внутри этого одного оператора SQL есть несколько встроенных операторов PSQL:

[source,sql]
----
oOutput = iInput;
suspend;
----

Они имеют точку с запятой, как того требует PSQL. Конец команды `CREATE PROCEDURE` обозначается использованием тильды в качестве терминатора:

[source,sql]
----
end~
----

При желании вы можете просто изменить терминатор, потому что вы предпочитаете что-то другое, а не точку с запятой.

[source,sql]
----
SQL> -- Change terminator from ; to +
SQL> set term + ;

SQL> select count(*) from employee+

       COUNT
============
          42

SQL> -- Change terminator from + to 'fred'
SQL> set term fred +

SQL> select count(*) from employee fred

       COUNT
============
          42

SQL> -- Change back from 'fred' to ;
SQL> set term ; fred
----

Однако вы должны быть осторожны, чтобы не выбрать символ-терминатор, который приведет к сбою операторов SQL из-за того, что терминатор используется в какой-то момент в операторе SQL.

[source,sql]
----
select 600+60+6 as The_Beast from rdb$database;

THE_BEAST
=====================
666

SQL> set term + ;
SQL> select 600+60+6 as The_Beast from rdb$database+

Statement failed, SQLSTATE = 42000
Dynamic SQL Error
-SQL error code = -104
-Unexpected end of command - line 1, column 8

SQL> set term ; +
----

Присутствие терминатора в выражении вызвало ошибку "`Unexpected end of command`". Анализатор SQL в ядре базы данных Firebird определил, что `select 600` не является допустимым оператором. По этой причине лучше всегда выбирать символ или символы, которые не будут путать синтаксический анализатор.

[source,sql]
----
SQL> set term !! ;

SQL> select 600+60+6 as The_Beast from rdb$database!!

THE_BEAST
=====================
666
----

[[fbadmgd-isql-prompts]]
== Подсказки ISQL

[float]
=== Подсказка SQL

Как показано выше, обычная подсказка `isql` для ввода -- это подсказка `SQL>`. Это указывает на то, что предыдущая команда была выполнена, и теперь `isql` ожидает обработки новой команды.

[float]
=== Подсказка CON

Подсказка `CON>` отображается, если пользователь нажимает клавишу btn:[ENTER] без завершения оператора SQL с помощью терминатора. Например:

[source,sql]
----
SQL> HELP
CON>
----

Всякий раз, когда вы видите приглашение `CON>`, вы можете либо продолжить ввод оставшейся части команды, либо ввести терминатор для завершения команды. В последнем случае команда будет выполнена после нажатия клавиши btn:[ENTER].

[[fbadmgd-isql-errors]]
== Обработка ошибок и поддержка исключений

Обработка исключений -- это программная конструкция, предназначенная для обработки ситуаций, которые нарушает нормальное выполнение программы. Это так называемые ошибки. Исключением являются именованное сообщение об ошибке, определяемые пользователем, написанные специально для базы данных и сохраненные в этой базе данных для использования в хранимых процедурах, функциях, пакетах, анонимных блоках и триггерах.

Например, если в триггере обнаруживается, что значение для таблицы неверно, то возникает исключение. Это приводит к откату всей транзакции, которую клиентское приложение пытается зафиксировать. Исключения могут совместно использоваться различными модулями приложения и даже различными приложениями, совместно использующими базу данных. Они предоставляют простой способ стандартизировать обработку заранее запрограммированных ошибок ввода.

Исключения составляют объекты базы данных, такие как таблицы, представления и домены, и являются частью метаданных базы данных. Их можно создавать, изменять и удалять, как и все другие объекты Firebird, используя `isql`.

В `isql` сообщения об ошибках содержат переменную SQLSTATE и статус вектор Firebird. Расшифровку кодов ошибок SQLSTATE вы можете найти в "`Руководстве по языку SQL СУБД Firebird`".

.Сообщение об ошибке в isql
[example]
====
[listing]
----
SQL> select 1/0 from rdb$database;

               DIVIDE
=====================
Statement failed, SQLSTATE = 22012
arithmetic exception, numeric overflow, or string truncation
-Integer divide by zero.  The code attempted to divide an integer value by an
integer divisor of zero.
----
====

[[fbadmgd-isql-transactions]]
== Обработка транзакций

В `isql` транзакция начинается сразу после запуска утилиты. Транзакция начинается в изоляции `SNAPSHOT` с разрешением блокировки в режиме `WAIT`. Поскольку утилита Firebird `isql` принимает DDL, DML и другие команды, транзакции обрабатываются соответствующим образом следующими способами:

* Операторы DDL фиксируются автоматически в двух случаях:
** Когда операторы `COMMIT` включен в скрипт.
** Когда включена автоматическая фиксация транзакций для DDL операторов (режим по умолчанию). В этом случае выполнение каждого DDL оператора транзакция автоматически подтверждается после ввода каждого оператора DDL, и стартует новая транзакция. Чтобы отключить режим автоматической фиксации, выполните инструкцию `SET AUTODDL OFF`. Для возврата в режим автоматической фиксации для DDL операторов выполните инструкцию `SET AUTODDL ON`.

* Операторы DML для выборки или изменения данных стартуют новую транзакцию с уровнем изоляции `SNAPSHOT`, если она не была начата ранее. Такая транзакция будет активной до тех пор, пока не будет вручную подтверждена оператором `COMMIT` или отменена оператором `ROLLBACK`.

* Вы можете использовать различные команды `SHOW` в `isql` для запроса метаданных базы данных. При этом ISQL запускает транзакцию с уровнем изоляции `READ COMMITTED`, что дает возможность видеть все изменения метаданных, подтвержденные другими пользователями.

Пользователи могут указать уровень изоляции и другие параметры для следующей транзакции с помощью оператора `SET TRANSACTION`. Он может быть выполнен только тогда, когда не активна другая транзакция. В противном случае будет задан вопрос: подтвердить или откатить активную транзакцию. Синтаксис оператора `SET TRANSACTION` подробно описан в "`Руководство по языку SQL Firebird`".

.Старт транзакции с режимом изолированности READ COMMITTED
[example]
====
[source,sql]
----
SET TRANSACTION WAIT READ COMMITTED LOCK TIMEOUT 10;
----
====

После выполнения `COMMIT` или `ROLLBACK`, новая DML команда стартует транзакцию с параметрами по умолчанию. Если необходимо, чтобы новая транзакция стартовала с параметрами, которые были указаны для предыдущей транзакции, то необходимо включить режим сохранения параметров транзакции с помощью команды `SET KEEP_TRAN_PARAMS` (может быть сокращена до `SET KEEP_TRAN`).

Если режим `KEEP_TRAN_PARAMS` установлен в:

* `ON`, то `isql` сохраняет текст следующего успешного оператора `SET TRANSACTION`, и новые транзакции DML запускаются с использованием того же SQL (вместо режима по умолчанию `CONCURRENCY WAIT`);
* `OFF`, то `isql` начинает новую транзакцию DML как обычно.

[NOTE]
====
Режим сохранения параметров транзакции появился в Firebird 3.0.6. Ранее невозможно было включить режим сохранения параметров транзакции. После команд `COMMIT` и `ROLLBACK` необходимо было каждый раз выполнять команду `SET TRANSACTION` с необходимыми параметрами.
====

// TODO: ссылка
См. также: SET KEEP_TRAN

[[fbadmgd-isql-script_handling]]
== Обработка скрипта

Пакет операторов DDL и/или DML в текстовом файле называется сценарием (скриптом). Скрипты могут быть использованы для создания и изменения объектов базы данных (метаданных). Они называются сценариями языка определения данных (DDL). Скрипты, которые манипулируют данными путем выбора, вставки, обновления, удаления или выполнения преобразований данных, называются скриптами языка манипулирования данными (DML).

Одной из наиболее важных задач, выполняемых `isql`, является обработка скриптов. Он может обрабатывать как сценарии DDL, так и сценарии DML. Большие файлы сценариев можно разбить на несколько файлов скриптов поменьше с помощью инструкции `INPUT`.

.Синтаксис
[listing,subs="+quotes,attributes"]
----
INPUT _file_name_
----

Данный оператор позволяет включить один файл сценария внутрь другого. Операторы сценариев выполняются в том порядке, в котором они появляются в файле сценариев. Настройка по умолчанию в `isql` для `AUTODDL` установлена на `ON`. Вы можете использовать команду `SET AUTODDL`, чтобы контролировать, где или когда будут подтверждены операторы изменения метаданных.

[NOTE]
====
Параметр `AUTODDL` влияет только на операторы DDL. Он не фиксирует транзакцию для операторов DML. Если вы смешиваете инструкции DDL и DML в одном и том же интерактивном сеансе, то фиксации транзакций для DDL с помощью `AUTODDL` не фиксируют ваши транзакции для операторов DML. Например:

[source,sql]
----
SQL> set autoddl on;

SQL> insert into test(a) values (666);
SQL> commit;

SQL> select * from test;

A
============
666

SQL> insert into test(a) values (999);
SQL> select * from test;

A
============
666
999

SQL> create table another_test(b integer);
SQL> rollback;

SQL> select * from test;

A
============
666
----
====

Скрипты могут перенаправить свои выходные данные в файл журнала с помощью команды `OUTPUT _file_name_`. Это можно ввести непосредственно в приглашении `isql` или как часть самого файла скрипта.

[[fbadmgd-isql-commands]]
== ISQL команды

Команды `isql` влияют на работу самого `isql` и никак не влияют на базу данных или данные. Эти команды используются для отображения справки, чтения, записи и запуска сценариев, а также выполнение инструкций командной строки. Вы можете легко увидеть список доступных команд, набрав команду `HELP`, которая выдаст следующий вывод:

[listing]
----
SQL> HELP;
Frontend commands:
BLOBDUMP <blobid> <file>   -- dump BLOB to a file
BLOBVIEW <blobid>          -- view BLOB in text editor
EDIT     [<filename>]      -- edit SQL script file and execute
EDIT                       -- edit current command buffer and execute
HELP                       -- display this menu
INput    <filename>        -- take input from the named SQL file
OUTput   [<filename>]      -- write output to named file
OUTput                     -- return output to stdout
SET      <option>          -- (Use HELP SET for complete list)
SHELL    <command>         -- execute Operating System command in sub-shell
SHOW     <object> [<name>] -- display system information
    <object> = CHECK, COLLATION, DATABASE, DOMAIN, EXCEPTION, FILTER, FUNCTION,
               GENERATOR, GRANT, INDEX, PACKAGE, PROCEDURE, ROLE, SQL DIALECT,
               SYSTEM, TABLE, TRIGGER, VERSION, USERS, VIEW
EXIT                       -- exit and commit changes
QUIT                       -- exit and roll back changes

All commands may be abbreviated to letters in CAPitals
----

Теперь обсудим каждую из команд отдельно.

[NOTE]
====
Обратите внимание на последнюю строку вывода команды `help`. Это объясняет, что каждая из команд может быть сокращена до букв, отображаемых заглавными буквами. В следующем обсуждении дополнительные символы будут отображаться, как указано выше, строчными буквами. Например, команда ввода будет показана как INput, чтобы указать, что символы 'put' являются необязательными.
====

[[fbadmgd-isql-commands-blobdump]]
=== BLOBDUMP

(((ISQL, BLOBDUMP)))

*Назначение:* Сохранение данных BLOB в указанном файле.

.Синтаксис
[listing,subs="+quotes,attributes"]
----
BLOBDUMP _blob_id_ _filename_
----

.Параметры оператора `BLOBDUMP`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|blob_id
|Идентификатор BLOB.

|filename
|Имя файла в который необходимо сохранить BLOB.

|===

Эта команда позволяет вам скопировать BLOB из базы данных во внешний файл. Оператор `BLOBDUMP` требует два параметра, идентификатор BLOB-объекта и имя файла. Вам необходимо передать идентификатор BLOB-объекта в виде пары шестнадцатеричных чисел, разделенных двоеточием. Первое число -- это идентификатор таблицы, а второе -- последовательный номер в базе данных. Для получения этого идентификатора выполните любой оператор `SELECT`, который выбирает столбец BLOB. Вывод покажет шестнадцатеричный идентификатор BLOB выше или на месте столбца BLOB в зависимости от того, установлен ли `SET BLOBDISPLAY` в `ON` или `OFF`.

.Сохранение BLOB во внешний файл
[example]
====
[source,sql]
----
SQL> set blobdisplay off;

SQL> select proj_id, proj_desc
CON> from project
CON> where proj_id = 'MKTPR';

PROJ_ID PROJ_DESC
======= =================
MKTPR   85:10

SQL> blobdump 85:10 c:\project.jpg;
----
====

Идентификатор BLOB-объекта, необходимый в приведенном выше примере, равен `85:10`.

// TODO: ссылки
Смотри также: SET BLOBDISPLAY, BLOBVIEW.
