[[fbadmgd-nbackup]]
= Утилита NBACKUP

(((NBACKUP))) `nbackup` -- утилита резервного копирования, включенная в Firebird начиная с версии 2.0. Она предоставляет возможности, отсутствующие у `gbak` (штатной утилиты резервного копирования Firebird), но не заменяет `gbak`. Обе утилиты имеют свои достоинства и недостатки, и их вполне можно использовать совместно.

[[fbadmgd-nbackup-common]]
== Обзор возможностей nbackup

Утилита `nbackup` позволяет выполнять два типа задач:

* Делать полные и инкрементные копии. Инкрементные копии содержат только изменения относительно предыдущей резервной копии.
* Блокировать базу данных для ее онлайн-копирования средствами операционной системы или другими утилитами. В этом режиме `nbackup` ничего не сохраняет и не копирует. Он просто создает условия, при которых копирование файла базы данных является безопасным.

Обе этих задачи могут выполняться над активной базой данных, без необходимости отключения пользователей. Результирующий бэкап (или копия файла базы данных) будет содержать базу данных на момент начала копирования. Только `SYSDBA` и владелец базы данных (или администраторы операционной системы) могут делать бэкап, но при этом любой пользователь может восстановить базу данных из такого бэкапа. В этом плане `nbackup` не отличается от `gbak`.

[[fbadmgd-nbackup-advantage]]
=== Преимущества nbackup

* *В обоих режимах*: высокая скорость (насколько позволяет оборудование и операционная система), поскольку `nbackup` оперирует страницами БД, а не записями, и не проверяет данные на страницах.

* *В режиме копирования/восстановления*: экономия времени и дискового пространства, поскольку нет необходимости делать полную копию каждый раз. Это позволяет сильно упростить задачу резервного копирования много-гигабайтных баз данных.

* *В режиме блокировки*: полная свобода выбора способа копирования файла БД.

[[fbadmgd-nbackup-limitations]]
=== Недостатки nbackup

* Утилита `nbackup` не будет чистить мусор, освобождать место в базе данных, сжимать бэкап, и так далее.
* Вы не можете поменять владельца БД через резервное копирование и восстановление, как это может `gbak`.
* Утилита `nbackup` не делает "`transportable backup`", то есть, полученная копия базы данных может быть несовместима с Firebird на другом аппаратном обеспечении (kdv: имеются в виду платформы с разным порядком байт в integer -- big-endian и little-endian. К разным ОС на одной платформе это не имеет никакого отношения).
* В настоящий момент `nbackup` не работает с много-файловыми базами данных (которые являются атавизмом и практически не используются).
* `nbackup` может оперировать только с локальными файлами баз данных. `nbackup` можно запускать удаленно, но сами базы и их копии все равно должны быть локальными по отношению к серверу Firebird.

[[fbadmgd-nbackup-params]]
== Функции и параметры

В таблице перечислены параметры `nbackup` с общим описанием их назначения.

.Описание параметров nbackup
[cols="<1,<1", options="header",stripes="none"]
|===
^|Опция
^|Описание

|`-B _n_ _database_ [_filename_]`
|Сделать бэкап уровня `_n_` в указанный файл.

|`-R _database_ [_filename_ ...]`
|Восстановить базу данных из указанных файлов.

|`-L _database_`
|Заблокировать базу данных.

|`-N _database_`
|Разблокировать восстановленную базу данных.

|`-F _database_`
|Разблокировать заблокированную базу данных.

|`-S`
|Показать размер базы данных в страницах после блокирования (совместно с `–L`).

|`-T`
|Игнорировать триггеры уровня базы данных (совместно с `–B`, `-L`, `-N`).

|`-D {on | off}`
|Прямой ввод-вывод включить (`on`) или выключить (`off`) (совместно с `-B`).

|`-U _username_`
|Имя пользователя (совместно с `-B`, `-L`, `-N`).

|`-P _password_`
|Пароль пользователя (совместно с `-B`, `-L`, `-N`).

|`-FE _filename_`
|Взять пароль из файла (совместно с `–B`, `-L`, `-N`).

|`-DE <command>`
|Распаковка сжатых бекапов перед их восстановлением. В качестве аргумента принимает командную строку, которая должна распаковать архив и передать в `stdout` распакованный файл бэкапа.

|`-Z`
|Вывести версию (отдельно или совместно с `-B`, `-R`, `-L`, `-N`, `-F`).

|`-?`
|Вывод справки по всем параметрам.

|===

В зависимости от выбранной основной функции (`-B`, `-L`, `-N`, `-R` или `-F`) `nbackup` может требовать определенный уровень доступа к базе данных: соединение с сервером Firebird, прямой доступ к файлам, или и то и другое. Следующая таблица показывает детали:

.Описание параметров nbackup
[cols="<1,<2,<1", options="header",stripes="none"]
|===
^|Параметр
^|Назначение
^|Доступ

|`-B`
|Резервная копия
|Сервер и файл

|`-R`
|Восстановление
|Файл

|`-L`
|Блокирование
|Сервер

|`-N`
|Разблокирование
|Сервер

|`-F`
|Разблокирование после восстановления
|Файл

|===

[NOTE]
====
Регистр параметров не имеет значения, может быть указано `-B` или `-b`, и так далее. Параметры приведены в верхнем регистре как минимум потому, что один из параметров `-L` в нижнем регистре `-l` выглядит как `-1` в большинстве шрифтов.
====

Когда требуется доступ к серверу (с параметрами `-B`, `-L` и `-N`), пользователь должен указать имя пользователя и пароль (параметрами `-U` и `-P|-FE`, или через переменные пользователя `ISC_USER` и `ISC_PASSWORD`), или быть `root` на Unix или доверенным пользователем на Windows.

Когда требуется доступ к файловой системе (с `-B`, `-R` и `-F`), пользователь должен иметь достаточные привилегии к файлу базы данных для чтения и записи.

Когда требуется исключительный доступ к файлу (с `-R` и `-F`), пользователю не нужен логин к Firebird, и сервер Firebird может быть не запущен или отсутствовать.

[NOTE]
====
В приведенных таблицах и тексте имеется в виду доступ к базе данных. Доступ к файлам бэкапов -- всегда на уровне файловой системы.
====

[[fbadmgd-nbackup-backup_and_restore]]
== Создание резервных копий и восстановление

Утилита `nbackup` находится там же, где и другие утилиты Firebird (`gbak`, `gstat` ...), то есть в корневом каталоге установки.

Как и другие утилиты Firebird, `nbackup` не имеет графического интерфейса. Вы запускаете его из командной строки, или из командного файла, или из приложения.

[[fbadmgd-nbackup-full-backup]]
=== Полные резервные копии

Чтобы сделать полный бэкап базы данных, выполните команду

[listing,subs="+quotes,attributes"]
----
nbackup -B 0 _database_ [_filename_] -U _user_ -P _password_
----

Например

[source,console]
----
nbackup -B 0 inventory.fdb inventory_2019-Aug-01.nbk
----

* Параметр `-B` означает "`backup`". Уровень бэкапа 0 производит полный бэкап, т.е. полную копию базы данных. Уровни бэкапа выше 0 используются для инкрементных бэкапов, которые описаны дальше.
* Вместо имени базы данных можно указать её псевдоним.
* Вместо имени файла бэкапа можно указать `stdout`. В этом случае вывод можно перенаправить, например, в архиватор.
* Параметры `-U` и `-P` можно не указывать при следующих условиях:
** Установлены корректные значения в переменных среды `ISC_USER` и `ISC_PASSWORD`, это `SYSDBA` или владелец БД и пароль;
** Вы вошли на Linux как `root`, это эквивалентно `SYSDBA`;
** На Windows: В `firebird.conf` (`databases.conf`) включена доверенная аутентификация (trusted authentification), и вы вошли в Windows с правами администратора, которому доступен файл базы данных. Для получения прав `SYSDBA` должен быть установлен `AUTO ADMIN MAPPING`.

[NOTE]
====
Для упрощения, в дальнейшем параметры `-U` и `-P` не указываются в примерах.
====

* Начиная с Firebird 2.5 вместо `-P _password_` можно указывать `-FE _filename_`. В этом случае `nbackup` прочитает пароль из указанного файла. В случае `-FE` пароль не указывается в командной строек, и это позволяет исключить доступ к паролю людей, которые могут посмотреть историю команд в командной строке (например, командой w на Unix или в скрипте).

// todo: link
* Параметр `-T` отключает триггеры базы данных. Подробнее см. раздел "<link xlink:href="#nbackup-nodbtriggers">Отключение триггеров БД</link>"".

* В Firebird 2.1.4 и выше возможно отключить кэширование БД файловой системой (включить прямой ввод-вывод) параметром `-D on` (или выключить прямой ввод-вывод `-D off`). Подробности см. далее в <link xlink:href="#nbackup-direct_io">соответствующем разделе</link>.

* Разные параметры (`-B`, `-U` и др.) могут быть указаны в любом порядке. Разумеется, за каждым параметром должен следовать его аргумент. В случае `-B` это три аргумента -- уровень бэкапа, имя базы данных, и имя файла бэкапа -- именно в таком порядке.

* Если параметр `-B` указан последним, вы можете не указывать имя файла бэкапа. В этом случае `nbackup` сам сгенерирует имя вида `database.fdb-0-20190807-2105.nbk`, где `0` -- это уровень, `20190807` -- дата, `2105` -- время. Но это может привести к ошибке, если бэкап одного и того же уровня делается два раза в одну и ту же минуту.

[IMPORTANT]
====
Не используйте `nbackup` на много-файловых базах данных. Это может привести к потере данных (неполный и поврежденный бэкап), при том что `nbackup` не выдаст сообщение об ошибке.
====

[%notitle]
==== Немного о том, как это устроено

. Сначала база данных блокируется (выставляется внутренний флаг состояния). С этого момента любые изменения базы данных записываются во временный файл -- так называемый "`дельта-файл`".
. Производится бэкап. Это эквивалент копирования файла, однако для приведения копии в рабочее состояние над ней нужно выполнить `nbackup -F`.
. По завершении бэкапа, содержимое дельта-файла записывается в базу данных. База данных разблокируется, и дельта-файл удаляется.

Шаги 1 и 3 обеспечиваются новыми командами SQL -- `ALTER DATABASE BEGIN BACKUP` и `ALTER DATABASE END BACKUP`. Эти команды не выполняют сам бэкап (копирование), они только создают условия, при которых база данных может быть успешно скопирована. Выполнять эти операторы самостоятельно нет необходимости (так как из SQL вы не имеете доступа к файлам), `nbackup` сделает всё за вас.

[[fbadmgd-nbackup-full-restore]]
=== Восстановление полных резервных копий

Полная резервная копия восстанавливается следующей командой

[listing,subs="+quotes,attributes"]
----
nbackup -R _database_ [_filename_]
----

Например

[source,console]
----
nbackup –R inventory.fdb inventory_2019_08_07.nbk
----

* Не нужно указывать "`уровень`" восстановления.
* При восстановлении параметр `-R` должен быть указан последним. Причина этого будет объяснена далее.
* Вместо имени базы данных можно указать её псевдоним.
* Если указано имя существующей базы данных, то будет выдана ошибка.
* Здесь также можно не указывать имя бэкапа. В этом случае `nbackup` запросит имя файла.
* Восстановление полностью работает на уровне файловой системы, и может быть выполнено без работающего Firebird. Любые значения, указанные для параметров `-U` и `-P` игнорируются. То же самое в отношении опции `-FE`, однако `nbackup` все равно будет пытаться прочитать пароль из файла, и если произошла ошибка, вся операция будет отменена.
