[[fbadmgd-gbak]]
= Утилита GBAK

(((GBAK))) Утилита `gbak` позволяет выполнять резервное копирование или восстановление базы данных с возможностью изменения указанных характеристик базы данных.

Запуск `gbak` без аргументов (или с неверным переключателем) или с переключателем `-?` приводит к отображению следующего экрана справочной информации:

[listing]
----
gbak:Usage:
     gbak -b <db set> <backup set> [backup options] [general options]
     gbak -c <backup set> <db set> [restore options] [general options]
     <db set> = <database> | <db1 size1>...<dbN> (size in db pages)
     <backup set> = <backup> | <bk1 size1>...<bkN> (size in bytes = n[K|M|G])
     -recreate overwrite and -replace can be used instead of -c
gbak:legal switches are:
    -B(ACKUP_DATABASE)    backup database to file
    -C(REATE_DATABASE)    create database from backup file (restore)
    -R(ECREATE_DATABASE) [O(VERWRITE)] create (or replace if OVERWRITE used)
                                database from backup file (restore)
    -REP(LACE_DATABASE)   replace database from backup file (restore)
gbak:backup options are:
    -CO(NVERT)            backup external files as tables
    -E(XPAND)             no data compression
    -FA(CTOR)             blocking factor
    -G(ARBAGE_COLLECT)    inhibit garbage collection
    -IG(NORE)             ignore bad checksums
    -L(IMBO)              ignore transactions in limbo
    -NOD(BTRIGGERS)       do not run database triggers
    -NT                   Non-Transportable backup file format
    -OL(D_DESCRIPTIONS)   save old style metadata descriptions
    -T(RANSPORTABLE)      transportable backup -- data in XDR format
gbak:restore options are:
    -BU(FFERS)            override page buffers default
    -FIX_FSS_D(ATA)       fix malformed UNICODE_FSS data
    -FIX_FSS_M(ETADATA)   fix malformed UNICODE_FSS metadata
    -I(NACTIVE)           deactivate indexes during restore
    -K(ILL)               restore without creating shadows
    -MO(DE) <access>      "read_only" or "read_write" access
    -N(O_VALIDITY)        do not restore database validity conditions
    -O(NE_AT_A_TIME)      restore one table at a time
    -P(AGE_SIZE)          override default page size
    -USE_(ALL_SPACE)      do not reserve space for record versions
gbak:general options are:
    -FE(TCH_PASSWORD)     fetch password from file
    -M(ETA_DATA)          backup or restore metadata only
    -PAS(SWORD)           Firebird password
    -RO(LE)               Firebird SQL role
    -SE(RVICE)            use services manager
    -SKIP_D(ATA)          skip data for table
    -ST(ATISTICS) TDRW    show statistics:
        T                 time from start
        D                 delta time
        R                 page reads
        W                 page writes
    -TRU(STED)            use trusted authentication
    -USER                 Firebird user name
    -V(ERIFY)             report each action taken
    -VERBI(NT) <n>        verbose information with explicit interval
    -Y  <path>            redirect/suppress status message output
    -Z                    print version number
gbak:switches can be abbreviated to the unparenthesized characters
----

Формат команд и список доступных переключателей отличается при создании резервной копи и восстановлении. Эти режимы работы и их переключатели будут описаны отдельно, а сейчас приведём список переключателей, которые являются общими для обоих режимов работы.

== Общие опции

Следующие параметры применимы как в режиме резервного копирования, так и в режиме восстановления базы данных.

.Команды и опции утилиты GBAK
[cols="<1,<1", options="header",stripes="none"]
|===
^|Опция
^|Описание

|`-FE[TCH_PASSWORD] _filename_`
|Извлекает пароль из файла. Если имя файла указано как `stdin`, то пользователю будет предложено ввести пароль. В системах POSIX имя файла `/dev/tty` также приведет к запросу пароля.

|`-M[ETADATA]`
|Этот переключатель приводит к тому, что ваши данные игнорируются, а не копируются и не восстанавливаются. При резервном копировании копируются только метаданные базы данных. При восстановлении любые данные в файле дампа не будут восстановлены.

|`-PAS[SWORD] _password_`
|Пароль пользователя, подключающегося к базе данных для резервного копирования, или используемый при создании БД в режиме восстановления.

Этот ключ не нужно указывать, если установлена переменная среды `ISC_PASSWORD`, а так же при использовании переключателя `-FE[TCH_PASSWORD]`, или доверительной аутентификации.

|`-RO[LE] _rolename_`
|Позволяет указать роль, которая будет использоваться подключающимся пользователем.

|`-SE[RVICE] <service>`
a|Указывает диспетчер служб.

Для локального соединения используйте просто имя диспетчера служб, которое всегда должно быть `service_mgr`.

Чтобы присоединить к удаленной машине необходимо дописать имя хоста в одном из следующих форматов с зависимости от используемого протокола:

TCP/IP:: `_hostname_[/_port_]:service_mgr`
WNET:: `{backslash}{backslash}__hostname__[@_port_]:service_mgr`
XNET:: `service_mgr`

Кроме того вы можете использовать обобщённый URL-подобный синтаксис

[listing,subs="+quotes,attributes"]
----
<protocol>://[_host_[:{_port_ {vbar} _service_}]/]service_mgr

<protocol> ::= inet {vbar} inet4 {vbar} inet6 {vbar} xnet {vbar} wnet
----

При использовании локального протокола (XNET) имя хоста указывать не нужно.

|`-SKIP_D[ATA] _pattern_`
|Пропускает данные таблиц, имена которых соответствуют указанному здесь регулярному выражению в SQL-синтаксисе (см. оператор `SIMILAR TO`).

|`-ST[ATISTICS] TRWD`
|Выводит статистику в процессе работы (работает вместе с `-V[ERIFY]`).

*T* -- время от начала работы `gbak`; +
*R* -- число страниц прочитанных с последнего вывода на экран; +
*W* -- число страниц записанных с последнего вывода на экран; +
*D* -- время прошедшее с последнего вывода на экран.

|`-TRU[STED]`
|Использовать доверительную аутентификацию.

|`-U[SER] _username_`
|Позволяет указать имя пользователя `SYSDBA` или пользователя владельца базы данных, если необходимо выполнить резервное копирование базы данных.

При восстановлении базы данных позволяет указать любого пользователя у которого есть привилегия `CREATE DATABASE`. Этот пользователь будет владельцем восстановленной базы данных.

Этот ключ не нужно указывать, если установлена переменная среды `ISC_ISC_USER`, или при использовании доверительной аутентификации.

|`-V[ERIFY]`
|Отчет о каждом выполненном действии.

Обычно `gbak` работает молчаливо, и информация не выводится на дисплей. Этот переключатель изменяет ситуацию и вызывает отображение большого количества информации.

При использовании этого переключателя по умолчанию информация выводится на экран, но вы можете перенаправить её в файл, используя ключ `-y`.

|`-VERBI[NT] _n_`
|Подробный вывод лога действии с заданным интервалом времени.

|`-Y {_log_filename_ {vbar} suppress}`
|Вывод лога действий в указанный файл.

Используется вместе с ключом `-v[erify]` для перенаправления сообщений о состоянии в файл или устройство, а не на экран, или для их полного подавления.

Если используется `-y suppress`, то никакая информация не будет записываться на экран независимо от того, указан ли `-v[erify]`.

Если задано имя файла и указан ключ `-v[erify]`, то сообщения о прогрессе и предупреждениях будут записаны в указанный файл.

|`-Z`
|Вывод версии `gbak` и версии сервера Firebird.

|===

[NOTE]
====
Параметр `-v` в справке, выдаваемой `gbak`, описан как `-v[erify]`. Это неверно, потому что опция `gbak -v` не имеет ничего общего с проверкой БД. Скорее, этот параметр должен расшифровываться как "`verbose`".
====

== Использование диспетчера служб

В обычном режиме при создании резервной копии `gbak` самостоятельно читает с сервера метаданные и данные из записывает их в файл резервной копии. При восстановлении `gbak` читает файл резервной копии и отправляет серверу инструкции для восстановления.

При использовании диспетчера служб `gbak` только даёт команду начать резервную копию или восстановление серверу, и он сам делает это. Однако `gbak` может принимать лог действий от сервера, который будет вестись при указании ключа `-v[erify]`. В этом случае при создании резервной копии файлы копии будут создаваться на сервере. Для возможности восстановления базы данных файлы резервной копии так же должны находится на сервере.

Для использования диспетчера служб необходимо указать параметр `-SE[RVICE] <service>`.

Для локального соединения используйте просто имя диспетчера служб, которое всегда должно быть `service_mgr`.

Чтобы присоединить к удаленной машине необходимо дописать имя хоста в одном из следующих форматов с зависимости от используемого протокола:

TCP/IP:: `_hostname_[/_port_]:service_mgr`
WNET:: `{backslash}{backslash}__hostname__[@_port_]:service_mgr`
XNET:: `service_mgr`

Кроме того вы можете использовать обобщённый URL-подобный синтаксис

[listing,subs="+quotes,attributes"]
----
<protocol>://[_host_[:{_port_ | _service_}]/]service_mgr

<protocol> ::= inet | inet4 | inet6 | xnet | wnet
----

При использовании локального протокола (XNET) имя хоста указывать не нужно.

[IMPORTANT]
====
Если используете диспетчер служб, то не надо указывать спецификацию удалённого хоста в имени базы данных как при резервном копировании, так и при восстановлении.
====

== Создание резервных копий

`gbak` создает непротиворечивую резервную копию базы данных, начиная транзакцию в режиме изолированности `SNAPSHOT`, которая охватывает весь период резервного копирования. В процессе резервного копирования `gbak` читает и сохраняет в специальный файл (или файлы) метаданные (описания таблиц, процедур, триггеров и т. д.) и данные таблиц. Любые изменения, сделанные транзакциями запущенными после начала резервного копирования, не попадут в файл резервной копии. Таким образом резервная копия будет представлять собой копию всей базы данных на момент начала резервного копирования. Это позволяет приложениям беспрепятственно работать с базой данных во время резервного копирования.

Для возможности резервного копирования пользователь должен быть авторизован как `SYSDBA` быть владельцем базы данных или обладать административными привилегиями в ней (соединиться с ролью `RDB$ADMIN`).

Формат командной строки для создания резервной копии выглядит следующим образом:

[listing,subs="+quotes,macros,attributes"]
----
gbak -b <database> <backup set> [<backup options>] [<general options>]

<backup set> ::= _backup_file_ | {_bk1_ _size1_} ... _bkN_

<database> ::= [<server_spec>]{_filepath_ | _db_alias_}

<server_spec> ::=
    _host_[/ {_port_ | _service_}]:
  | {backslash}{backslash}__host__\
  | <protocol>://[_host_[:{_port_ | _service_}]/]

<protocol> ::= inet | inet4 | inet6 | wnet | xnet
----

=== Опции резервного копирования

.Опции резервного копирования
[cols="<1,<1", options="header",stripes="none"]
|===
^|Опция
^|Описание

|`-B[ACKUP_DATABASE]`
|Создать резервную копию

|`-CO[NVERT]`
|Конвертировать внешние таблицы во внутренние таблицы базы данных.

|`-E[XPAND]`
|Отключение сжатия данных при резервном копировании. По умолчанию резервная копия записывается в "`сжатом`" виде.

|`-FA[CTOR] _n_`
|При резервном копировании на физическое ленточное устройство этот переключатель позволяет указать коэффициент блокировки ленты. Атавизм.

|`-G[ARBAGE_COLLECT]`
|Отключение сборки мусора во время резервного копирования.

`gbak` подключается к базе данных как и любое обычное приложение. Обычно при чтении таблиц сервер проверяет записи на наличие мусора, и в случае его обнаружения убирает его. Использование этого параметра предотвращает запуск сборки мусора во время резервного копирования. Это может помочь ускорить резервное копирование.

|`-IG[NORE]`
|Этот переключатель заставляет `gbak` игнорировать неверные контрольные суммы в базе данных.

В обычной командной строке для создания резервной копии базы данных категорически не рекомендуется указывать параметр `-ig`! Если база данных вдруг окажется повреждена, то с этим параметром вы можете "`не увидеть`"повреждение. Так что, `-ig` для `gbak` используется только в крайнем случае -- когда поврежденная база починена утилитой `gfix`, но обычная резервная копия не проходит. Только тогда имеет смысл повторить создание резервной копии с опцией `-ig`.

|`-L[IMBO]`
|Игнорировать зависшие двухфазные транзакции (limbo).

Не сохраняет в резервной копии БД версии записей, которые созданы транзакциями, находящимися в состоянии in limbo. Такое состояние может быть только у не завершившихся транзакций двухфазного подтверждения (Two Phase Commit -- 2PC). Если приложения не используют двухфазное подтверждение, или вы не знаете, что это такое, то этот параметр вам никогда не понадобится.

|`-NOD[BTRIGGERS]`
|Не запускать триггеры уровня базы данных.

|`-NT`
|Формат резервной копии, непереносимой между аппаратными платформами.

Если вы используете этот переключатель для создания резервной копии, вы можете восстановить ее только на аналогичной платформе.

|`-OL[D_DESCRIPTIONS]`
|Устарел. Требовался для создания резервных копий в формате совместимом с Interbase 3.3.

|`-T[RANSPORTABLE]`
|Создаёт транспортабельную (переносимую) резервную копию.

Формат файла резервную копии по умолчанию является переносимым, поэтому указывать данный переключатель не следует. Переносимые файлы резервных копий записываются в формате, известном как формат представления внешних данных (XDR). Такой файл резервной копии можно восстановить на альтернативной аппаратной платформе, где порядок байт в целых числах отличается. То есть, например, между Intel и Sparc, или HP-UX и Intel, и так далее. Но между Windows и Linux (или другой ОС) на Intel файл резервной копии будет и так переносимым, даже при указании ключа `-nt` (non-transportable).

|===

=== Имя базы данных

Как уже было сказано, что `gbak` это обычная программа, которая читает данные из базы данных, то сама база данных и сервер могут находиться где угодно.

Если база данных распложено локально, то достаточно просто указать путь к первичному файлу базы данных или её псевдоним. Пример:

[source,console]
----
gbak -b C:\data\my.fdb D:\backup\my.fbk ...
----

или с использованием псевдонима базы данных

[source,console]
----
gbak -b mydb D:\backup\my.fbk ...
----

Если же база данных расположено на удалённом хосте, то необходимо дополнить её имя спецификацией удалённого сервера. Например:

[source,console]
----
gbak -b server:C:\data\my.fdb D:\backup\my.fbk ...
----

или

[source,console]
----
gbak -b server:mydb D:\backup\my.fbk ...
----

Спецификацию удалённого хоста удобно указывать с помощью URL-подобного синтаксиса, в котором можно явно задать используемый протокол:

[source,console]
----
gbak -b inet://localhost:3053/mydb D:\backup\my.fbk ...

gbak -b wnet:///mydb D:\backup\my.fbk ...
----

[IMPORTANT]
====
При использовании диспетчера служб (переключатель `-SE`) перед именем базы данных не нужно указывать спецификацию удалённого сервера, поскольку в этом случае она указывается перед именем диспетчера служб.
====

=== Имя файла(ов) резервной копии

Сразу после имени базы данных необходимо указать полный путь до файла резервной копии. Если для создания резервной копи не используется диспетчер служб (переключатель `-SE`), то резервная копия будет создана на локальной машине, с которой запущен `gbak`. При использовании диспетчера служб резервная копия будет создана на удалённом компьютере, на котором расположена база данных.

Имя файла резервной копии может любое расширение. Вы можете встретить `bak`, `gbk`, `fbk`, и так далее. Никаких ограничений в этом плане не накладывается. Имя резервной копии лучше формировать как имя базы и дату, причем дату лучше всего указывать в "`японском`" формате, в виде YYYYMMDD -- так имена файлов будут корректно сортироваться при просмотре папки.

Существует возможность делать многофайловую резервную копию, разбивая резервную копию на части. В этом случае указывается несколько файлов резервных копий. После каждого файла резервной копии, кроме самого последнего, необходимо указать его максимальный размер. По умолчанию размер указывается в байтах. Вы можете также указывать размер в килобайтах, мегабайтах и гигабайтах, используя множители (`k`, `m` или `g`).

.Создание многофайловой копии
[example]
====
В примере ниже будут созданы три файла резервной копии, два файла размером по 100 Мегабайт, и третий файл в котором расположена оставшаяся часть резервной копии.

[source,console]
----
gbak -b C:\data\my.fdb D:\backup\copy_1.fbk 100M D:\backup\copy_2.fbk 100M
  D:\backup\copy_3.fbk -user SYSDBA -password masterkey
----
====

=== Ускорение резервного копирования

Есть несколько приемов, которые вы можете использовать для ускорения резервного копирования. Первый -- запретить сборку мусора во время выполнения резервного копирования. Сборка мусора удаляет старые версии записей, которые больше не требуются, и это обычно покрывается чисткой (sweep) -- ручной или автоматической -- или полным сканированием таблицы любой затронутой таблицы. Поскольку `gbak` получает доступ ко всем строкам в резервируемых таблицах, он также запускает сборку мусора, что может замедлить резервное копирование. Чтобы предотвратить сборку мусора во время резервного копирования, используйте параметр `-g[arbage_collect]`.

[source,console]
----
gbak -backup -g employee /backups/employee.fbk
----

Второй вариант -- делать резервное копирование с использованием диспетчера служб, то есть задействовать опцию `-se[rvice]`.

В обычном режиме при создании резервной копии `gbak` самостоятельно читает с сервера метаданные и данные из записывает их в файл резервной копии. При использовании диспетчера служб gbak только даёт команду начать резервную копию или восстановление серверу, и он сам делает это. Однако `gbak` может принимать лог действий от сервера, который будет вестись при указании ключа `-v[erify]`. В этом случае при создании резервной копии файлы копии будут создаваться на сервере. Для возможности восстановления базы данных файлы резервной копии так же должны находится на сервере.

Поскольку при использовании диспетчера служб резервную копию выполняет сам сервер, то это позволяет избежать копирования данных по сети, за исключением лога действий, если он включен. Это в свою очередь позволяет делать резервную копию гораздо быстрее, даже на локальном компьютере.

Примеры резервного копирования с использованием диспетчера служб:

[source,console]
----
gbak -backup -service tux:service_mgr employee /backups/employee.fbk

gbak -backup -service inet4://tux:3051/service_mgr employee /backups/employee.fbk
----

Для достижения лучшего результата вы можете комбинировать опции `-g[arbage_collect]` и `-se[rvice]`.

=== Примеры команд резервного копирования

.Создание резервной копии на локальном компьютере
[example]
====
Следующая команда создаёт резервную копию на локальном компьютере (`gbak` и сервер базы данных находятся на одном и том же компьютере).

[source,console]
----
gbak -b -g d:\data\employee.fdb d:\backups\employee.fbk -user sysdba -password masterkey
----

Обратите внимание на опцию `-g` которая указана для отключения сборки мусора, чтобы ускорить процесс резервного копирования.

В данном случае будет использован локальный протолок для доступа к базе данных. Вы можете явно указать локальный протокол при помощи префикса `xnet`. Вместо пути к первичному файлу базы данных используется псевдоним базы данных.

[source,console]
----
gbak -b -g xnet://employee d:\backups\employee.fbk -user sysdba -pas masterkey
----

Для более быстрого создания резервной копии на локальном компьютере рекомендуем использовать диспетчер служб.

[source,console]
----
gbak -b -g -se service_mgr employee d:\backups\employee.fbk -user sysdba -pas masterkey
----
====

.Создание резервной копии на удалённом компьютере
[example]
====
Следующая команда создаёт резервную копию на удалённом компьютере (`gbak` и сервер базы данных находятся на разных компьютерах). Используется протокол TCP. Резервная копия будет создана на компьютере на котором запущен `gbak`.

[source,console]
----
gbak -b -g remotehost:d:\data\employee.fdb d:\backups\employee.fbk -user sysdba -password masterkey
----

Если Firebird работает на нестандартном порту, например 3051, то команда измениться так:

[source,console]
----
gbak -b -g remotehost/3051:d:\data\employee.fdb d:\backups\employee.fbk -user sysdba -password masterkey
----

Вы можете явно указать протокол TCP при помощи префиксов: `inet`, `inet4`, `inet6`. Вместо пути к первичному файлу базы данных используется псевдоним базы данных.

[source,console]
----
gbak -b -g inet://remotehost/employee d:\backups\employee.fbk -user sysdba -pas masterkey
----

Если Firebird работает на нестандартном порту, например 3051, то команда измениться так:

[source,console]
----
gbak -b -g inet://remotehost:3051/employee d:\backups\employee.fbk -user sysdba -pas masterkey
----

Для более быстрого создания резервной копии рекомендуем использовать диспетчер служб. Однако учтите, что в этом случае резервная копия будет создана на том же компьютере, на котором расположена база данных.

[source,console]
----
gbak -b -g -se remotehost:service_mgr employee d:\backups\employee.fbk -user sysdba -pas masterkey
----

Вариант с использованием явного указания префикса протокола представлен ниже:

[source,console]
----
gbak -b -g -se inet4://remotehost/service_mgr employee d:\backups\employee.fbk -user sysdba -pas masterkey
----

// todo: link
Существует возможность создания резервной копии на удалённом компьютере с использованием диспетчера служб, однако утилита `gbak` её не предоставляет. Однако вы можете воспользоваться утилитой `fbsvcmgr`. Пример использования вы можете найти в разделе "`Утилита FBSVCMGR. Резервная копия (gbak)`".
====

.Создание резервной копии с логом операций gbak
====
Следующая команда создаст резервную копию на локальном компьютере с использование диспетчера служб. Журнал операций выполняем gbak будет выведен на консоль.

[source,bash]
----
gbak -b -g -se inet://localhost/service_mgr -user sysdba -password masterkey employee /copy/employee.dmp -v
----

Каждую операцию можно снабдить статистикой с помощью опции `-ST`.

[source,bash]
----
gbak -b -g -se inet://localhost/service_mgr -user sysdba -password masterkey employee /copy/employee.dmp -v -st trwd
----

Для того чтобы журнал операций `gbak` был записан в файл добавим опцию `-Y`.

[source,bash]
----
gbak -b -g -se inet://localhost/service_mgr -user sysdba -password masterkey employee /copy/employee.dmp -v -st trwd -y /copy/employee_dump.log
----
====

.Создание резервной копии только метаданных
[example]
====
Следующая команда создаст резервную копию на локальном компьютере с использование диспетчера служб. В резервную копию попадут только метаданные (описания таблиц, представлений, хранимых, процедур и функций, триггеров, но без данных в таблицах).

[source,bash]
----
gbak -b -g -metadata -se inet://localhost/service_mgr -user sysdba -password masterkey employee /copy/employee.dmp
----
====

.Создание резервной копии с исключением данных некоторых таблиц
[example]
====
Иногда требуется создать резервную копию, но исключить из неё данные некоторых таблиц, чтобы уменьшить объём резервной копии. Например, это могут быть таблицы логирования, которые могут содержать довольно значительный объём данных, но хранение которых не критично. Учтите, что от данных исключаемой таблицы не должно быть зависимостей, т.е. ссылок на её строки из других по внешнему ключу. Если таковые имеются, то их следует также исключить из резервной копии, в противном случае из-за нарушения ограничений целостности. база данных не может быть восстановлена.

В следующей команде будет создана резервная копия из которой будут исключены данные таблиц `table1` и `table2`. Для исключения данных таблиц из резервной копии используется переключатель `-SKIP_D[ATA] _pattern_`, где `_pattern_` -- регулярное выражение в SQL-синтаксисе (см. оператор `SIMILAR TO`). Из резервной копии будут исключены таблицы соответствующие регулярному выражению. Если вам необходимо исключить конкретный список таблиц, вы можете перечислить их имена, разделив их символом "`|`".

[source,bash]
----
gbak -b -g -se inet://localhost/service_mgr -user sysdba -password masterkey -skip_data table1|table2 employee /copy/employee.dmp
----
====

.Создание многофайловой резервной копии
[example]
====
В примере ниже будут созданы три файла резервной копии, два файла размером по 100 Мегабайт, и третий файл в котором расположена оставшаяся часть резервной копии.

[source,console]
----
gbak -b -g inet://localhost/service_mgr -user SYSDBA -password masterkey C:\data\my.fdb D:\backup\copy_1.fbk 100M D:\backup\copy_2.fbk 100M D:\backup\copy_3.fbk
----
====

== Восстановление базы данных из резервной копии

Процесс восстановления базы данных из резервной копии происходит следующим образом:

* Сервер создает пустую базу данных. Причем, создает ее в том формате баз данных (ODS), который является для него "`родным`". Пустая база данных будет содержать все системные таблицы `rdb$` (пока пустые), и будет иметь ряд параметров, например, такие как размер страницы, forced write и т. д., которые или взяты из резервной копии, или установлены в командной строке `gbak`.
* Сервер считывает метаданные (описания таблиц и индексов, процедур, функций) из резервной копии и переносит их в базу данных.
* Сервер считывает данные из резервной копии и переносит их в базу данных.
* Сервер считывает остальные метаданные (триггеры, привилегии, check constraints и т. п.) из резервной копии и переносит их в базу данных.
* Сервер создает (активирует) все индексы таблиц (которые были активны в момент создания резервной копии).

[NOTE]
====
Если вас интересует точная последовательность действий `gbak` при backup и restore, например, порядок сохранения и восстановления объектов метаданных, то вы можете обратиться к исходным текстам -- `backup.epp` и `restore.epp`> соответственно. По мере развития IB/FB и исправления ошибок порядок сохранения-восстановления некоторых объектов изменялся.
====

Таким образом, восстановленная из резервной копии база данных будет на самом деле не копией старой базы, а совершенно новой базой данных, наполненной старыми данными.

Помните, что если вы делаете восстановление на новой версии сервера, например, резервную копию делали на Firebird 2.5 (формат БД ODS 11.2), а восстанавливаете на Firebird 3.0 (формат БД ODS 12.0), то база будет создана в формате, поддерживаемом по умолчанию Firebird 3.0, и Firebird 2.5 с этой базой работать не сможет.

Резервные копии тоже имеют свой формат, и резервная копия БД, сделанная например в Firebird 2.5 утилитой `gbak` этой же версии, не может быть восстановлена утилитой `gbak` от Firebird 2.1. Резервная копия сделанная в Firebird 3.0 моет быть восстановлена в Firebird 2.5, при условии, что база данных не использует новые возможности ODS 12 (хранимые функции, пакеты, новые типы данных, новые возможности SQL и PSQL в метаданных и другое).

Для восстановления базы данных пользователь должен обладать административной привилегией в базе данных безопасности (`SYSDBA` или соединиться с ролью `RDB$ADMIN`) или обладать привилегией `CREATE DATABASE`. Этот пользователь будет владельцем восстановленной базы данных.

Формат командной строки для восстановления базы данных из резервной копии выглядит следующим образом:

[listing,subs="+quotes,macros,attributes"]
----
gbak {-c | -r o | -rep} <backup set> <db set> [<backup options>] [<general options>]

<backup set> ::= _backup_file_ [_backup_file_2_ ... [_backup_file_N_]]

<db set> ::= <database> [_size1_ _db2_ ... [_sizeN-1_ _dbN_]]

<database> ::= [<server_spec>]{_filepath_ | _db_alias_}

<server_spec> ::=
    _host_[/ {_port_ | _service_}]:
  | {backslash}{backslash}__host__\
  | <protocol>://[_host_[:{_port_ | _service_}]/]

<protocol> ::= inet | inet4 | inet6 | wnet | xnet
----

=== Создание базы данных, восстановление или замена

Восстановление базы данных из резервной копии может происходить в нескольких режимах.

* `-C[REATE_DATABASE]` -- создание новой базы данных из резервной копии. Если файл базы данных уже существует, то будет выдана ошибка.
* `-R[ECREATE_DATABASE] [O[VERWRITE]]` -- создание новой (или замена существующей при использовании опции `O[VERWRITE]`) базы данных из резервной копии. Если базы данных не существует, то будет создана новая база данных. Если база данных уже существует, то при использовании опции `O[VERWRITE]` она будет заменена на новую, в противном случае будет выдана ошибка.
* `-REP[LACE_DATABASE]` -- замена существующей базы данных при восстановлении из резервной копии.

[NOTE]
====
Настоятельно рекомендуем не пользоваться ключами `-R O` и `-REP`. Если база данных существует на диске, и вы просите `gbak` восстановить ее с помощью одного из двух указанных выше ключей, вы можете повредить базу данных, особенно если база данных используется и не была закрыта с помощью `gfix`.

Кроме того, процесс восстановления базы данных из резервной копии может завершиться неудачей, и в этом случае вы окажетесь без рабочей базы данных.

В целях безопасности всегда заново создавайте базу данных с новым именем. Только после того как вы проверили целостность новой базы данных, вы можете заменить ею рабочую базу данных.
====

=== Опции восстановления базы данных из резервной копии

.Опции восстановления базы данных из резервной копии с помощью GBAK
[cols="<1,<1", options="header",stripes="none"]
|===
^|Опция
^|Описание

|`-C[REATE_DATABASE]`
|Создание новой базы данных из резервной копии. Если файл базы данных уже существует, то будет выдана ошибка.

|`-R[ECREATE_DATABASE] [O[VERWRITE]]`
|Создание новой (или замена существующей при использовании опции `O[VERWRITE]`) базы данных из резервной копии. Если базы данных не существует, то будет создана новая база данных. Если база данных уже существует, то при использовании опции `O[VERWRITE]` она будет заменена на новую, в противном случае будет выдана ошибка.

|`-REP[LACE_DATABASE]`
|Замена существующей базы данных при восстановлении из резервной копии.

|`-BU[FFERS] _n_`
|Изменить (или указать новый) размер страничного кэша базы данных. Принимается значение больше 0. Размер кэша базы данных прописывается в её заголовок, его можно изменить позже с помощью утилиты `gfix`. Рекомендуем не устанавливать кэш на уровне заголовка базы данных, а использовать вместо этого параметр `DefaultDbCachePages`в файле `databases.conf`.

|`-FIX_FSS_D[ATA] _charset_`
|Этот переключатель заставляет `gbak` исправлять искаженные символьные данные `UNICODE_FSS` во время восстановления.

Этот и следующий переключатель не требуется при нормальных обстоятельствах. Однако, если операция восстановления завершается неудачно с ошибкой "`malformed string`", то сообщение, выведенное из `gbak`, отсылает пользователя к одному  или обоим этим переключателям для исправления неверно сформированных данных или метаданных `UNICODE_FSS` в зависимости от ситуации.

|`-FIX_FSS_M[ETADATA] _charset_`
|Этот переключатель заставляет `gbak` исправлять некорректные метаданные `UNICODE_FSS` во время восстановления.

Этот переключатель, как и предыдущий, не требуется в нормальных условиях. Однако, если операция восстановления завершается неудачно с ошибкой "`malformed string`", сообщение, выведенное из `gbak`, отсылает пользователя к одному или обоим этим переключателям для исправления неверно сформированных данных или метаданных `UNICODE_FSS` в зависимости от ситуации.

|`-I[NACTIVE]`
|Не выполнять активацию индексов. После восстановления базы данных все индексы в ней останутся отключены (неактивны). Фактически с такой базой данных работать нельзя, так как при отключенных индексах Primary key, Foreign key и Unique возможны нарушения целостности данных в таблицах (дублирование первичных ключей и т. д.).

Если вы восстановили резервную копию с опцией `-i`, индексы можно активировать командой `alter index _indexname_ active` (для каждого индекса).

|`-K[ILL]`
|Этот ключ восстанавливает базу данных, но не воссоздает файлы теневых копий, которые существовали ранее.

|`-MO[DE] {read_write | read_only}`
|Этот переключатель позволяет восстановить базу данных в заданном режиме доступа "`read_only`" или "`read_write`". По умолчанию режим берется из базы данных, с которой была сделана резервная копия.

|`-N[O_VALIDITY]`
|Не выполнять проверку ограничений. Может потребоваться, если при обычном восстановлении базы оказалось, что логическая целостность оригинальной базы данных была повреждена.

Крайне не рекомендуется для использования в "`командной строке автоматизированного восстановления`".

|`-O[NE_AT_A_TIME]`
|Этот переключатель заставляет восстанавливать одну таблицу за раз. Обычно восстановление данных таблиц выполняется в одной транзакции с одним подтверждением в конце восстановления. При использовании опции `-o[ne_at_a_time]` транзакция стартует и фиксируется для восстановления каждой таблицы.

Эта опция может быть полезна, если предыдущее восстановление не удалось из-за ошибок данных.

|`-P[AGE_SIZE] _n_`
|Указать новый размер страницы для базы данных. Принимаются значения: 4096, 8192, 16384. По умолчанию база данных восстанавливается с использованием того же размера страницы, который использовался при создании резервной базы данных.

|`-USE_[ALL_SPACE]`
|Этот переключатель заставляет при восстановлении использовать 100% каждой страницы данных (DP). По умолчанию Firebird резервирует приблизительно 20% на каждой странице для размещения версий при будущих удалениях или обновлениях записей. Этот переключатель может быть полезен если база данных создается и используется в режиме только для чтения, а обновления существующих данных не требуются.

// todo: link
Вы можете переопределить этот параметр, используя `gfix -use {full | reserve} _database_name_`, где `full` использует 100% каждой страницы, а `reserve` зарезервирует некоторое место для версий. Подробнее смотри в главе "`Утилита GFIX`" секции "`Использование пространства страниц базы данных`".

|===

=== Имя файла(ов) резервной копии

Необходимо указывать полный путь до файла резервной копии. Если при восстановлении базы данных не используется диспетчер служб (переключатель `-SE`), то файл резервной копии будет прочитан с локальной машины, на которой расположен `gbak`. При использовании диспетчера служб, файл резервной копии будет прочитан с машины, на которой расположен Firebird (хост указан в спецификации диспетчера служб).

Вы можете восстанавливать базу данных из многофайловой резервной копии. В этом случае файлы резервной копии должны быть разделены пробелами.

.Восстановление из многофайловой копии
[example]
====
В примере восстановлена база данных из многофайловой резервной копии.

[source,console]
----
gbak -c -se inet://localhost/service_mgr -user sysdba -password masterkey d:\copy\db1.fbk d:\copy\db.fbk d:\copy\db3.fbk d:\data\db.fdb
----
====

=== Имя файла(ов) базы данных

Если база данных распложено локально, то достаточно просто указать путь к первичному файлу базы данных или её псевдоним. Например:

[source,console]
----
gbak -c d:\copy\db.fbk d:\data\db.fdb
----

Или с использованием псевдонима базы данных:

[source,console]
----
gbak -c d:\copy\db.fbk db
----

Если же база данных расположено на удалённом хосте, то необходимо дополнить её имя спецификацией удалённого сервера. Например:

[source,console]
----
gbak -c d:\copy\db.fbk remotehost:d:\data\db.fdb
----

Спецификацию удалённого хоста удобно указывать с помощью URL-подобного синтаксиса, в котором можно явно задать используемый протокол:

[source,console]
----
gbak -c d:\copy\db.fbk inet://remotehost:3053/d:\data\db.fdb

gbak -c d:\copy\db.fbk xnet://d:\data\db.fdb
----

[IMPORTANT]
====
При использовании диспетчера служб (переключатель `-SE`) перед именем базы данных не нужно указывать спецификацию удалённого сервера, поскольку в этом случае она указывается перед именем диспетчера служб.
====

Существует возможность восстанавливать многофайловую базу данных из резервной копию. В этом случае указывается несколько файлов базы данных. После каждого файла базы данных, кроме самого последнего, необходимо указать его максимальный размер в страницах. Например:

[source,console]
----
gbak -c -se inet://localhost/service_mgr -user sysdba -password masterkey d:\copy\db.fbk  d:\data\db.fdb 50000 d:\data\db2.fdb
----

Кроме того, существует возможность восстановления многофайловой базы данных из многофайловой резервной копии. В этом случае утилита `gbak` сама определит где заканчивается перечисление файлов резервной копии и начинается перечисление файлов баз данных. Либо файл базы данных указан последним, либо после файла базы данных указан размер в страницах. Пример:

[source,console]
----
gbak -c -se inet://localhost/service_mgr -user sysdba -password masterkey d:\copy\db_1.fbk d:\copy\db_2.fbk d:\copy\db_3.fbk d:\data\db.fdb 50000 d:\data\db.fdb
----

=== Ошибки искажения строк во время процесса восстановления

Во время операции восстановления, скорее всего, при восстановлении резервной копии, созданной с использованием более старой версии `gbak`, в выводе `gbak` можно увидеть сообщения об ошибках, указывающие на искаженные Unicode строки. Причина, по которой это может произойти, объясняется Хелен Борри:

[quote]
____
Исходный текст хранимых процедур (и некоторых других типов объектов, таких как ограничения CHECK) хранится в BLOB поле, как и "`скомпилированный`" код BLR. При восстановлении базы данных BLR не воссоздается из исходного когда: этот же BLR используется до тех пор, пока вы в следующий раз не создадите или не измените объект метаданных.

Исторически Firebird не делал правильных вещей в отношении транслитерации строк с исходным кодом и BLR. В Firebird 2.1 и Firebird 2.5 была проделана большая работа для решения международных языковых проблем. Побочным эффектом этого было то, что все, что было прочитано из данных и метаданных, стало предметом проверки "`правильности`". Следовательно, при восстановлении, те ранее сохраненные исходные коды объектов и BLR выдают ошибки "`malformed string`", когда `gbak` пытается прочитать и записать данные в этих записях системной таблицы. Эта очень старая ошибка также влияет на пользовательские BLOB, если они были сохранены с использованием набора символов `NONE`, а клиент настроен на чтение указанного набора символов, для которого сохраненные данные не могут быть транслитерированы.

В версии 2.1 в `../misc` были сценарии, которые вы могли запускать для восстановления BLOB метаданных, а также использовать в качестве шаблона для исправления подобных ошибок в BLOB ваших пользовательских данных. Ключи восстановления были добавлены в код восстановления `gbak` в версии 2.5 для внесения таких же исправлений в метаданные (опция `-fix_fss_m[etadata]`) и данные (опция `-fix_fss_d[ata]`), соответственно, в процессе восстановления базы данных для обновления.
____

[WARNING]
====
Обе опции `-fix_fss_*` указываются *ОДИН* раз в том случае, если при восстановлении бэкапа возникает ошибка "`malformed string`". При указании этих опций повторно при backup/restore база данных будет испорчена.
====

=== Ускорение восстановления базы данных

Восстановление базы данных из резервной копии может быть выполнено быстрее, если используется опция `-se[rvice]`. Чаще всего эта опция используется для удаленного восстановления, но она также может использоваться локально. Данная опция позволяет избежать копирования данных по сети TCP, что замедляет действия по восстановлению.

[source,console]
----
tux> gbak -replace -service tux:service_mgr /backups/employee.fbk employee
----

=== Примеры команд восстановления из резервной копии

.Восстановление из резервной копии на локальном компьютере
[example]
====
Следующая команда восстановит (создаст новую базу данных) из резервной копии на локальном компьютере (`gbak` и сервер базы данных находятся на одном и том же компьютере).

[source,console]
----
gbak -с d:\backups\employee.fbk d:\data\employee.fdb -user sysdba -password masterkey
----

[IMPORTANT]
====
Обратите внимание, если файл базы данных уже существует, то будет выдана ошибка.

Существуют так же опции `-r o` (`-RECREATE_DATABASE OVERWRITE`) или `-rep` (`-REPLACE_DATABASE`), которые позволяют заменить существующий файл базы данных, однако мы не рекомендуем использовать их, поскольку они могут привести к утрате оригинального файла базы данных в случае если восстановление завершиться с ошибкой.
====

// todo: я в этом не уверен. В 3.0 это может быть не так
В примере выше будет использован локальный протолок. Вы можете явно указать локальный протокол при помощи префикса `xnet`.

[source,console]
----
gbak -с d:\backups\employee.fbk xnet://d:\data\employee.fdb -user sysdba -password masterkey
----

Для более быстрого восстановления базы данных из резервной копии на локальном компьютере рекомендуем использовать диспетчер служб.

[source,console]
----
gbak -с -se service_mgr d:\backups\employee.fbk d:\data\employee.fdb -user sysdba -password masterkey
----

====

.Восстановление из резервной копии на удалённом компьютере
[example]
====
Следующая команда восстанавливает базу данных (создаёт новую) из резервной копии расположенной на удалённом компьютере (`gbak` и сервер базы данных находятся на разных компьютерах). Используется протокол TCP. База данных будет создана на компьютере на котором расположен сервер Firebird.

[source,console]
----
gbak -с d:\backups\employee.fbk remotehost:d:\data\employee.fdb -user sysdba -password masterkey
----

Если Firebird работает на нестандартном порту, например 3051, то команда измениться так:

[source,console]
----
gbak -с d:\backups\employee.fbk remotehost/3051:d:\data\employee.fdb -user sysdba -password masterkey
----

Вы можете явно указать протокол TCP при помощи префиксов: `inet`, `inet4`, `inet6`. Вместо пути к первичному файлу базы данных используется псевдоним.

[source,console]
----
gbak -с d:\backups\employee.fbk inet://remotehost/employee -user sysdba -password masterkey
----

Если Firebird работает на нестандартном порту, например 3051, то команда измениться так:

[source,console]
----
gbak -с d:\backups\employee.fbk inet://remotehost:3051/employee -user sysdba -password masterkey
----

Для более быстрого восстановления базы данных из резервной копии рекомендуем использовать диспетчер служб. Однако учтите, что в этом случае резервная копия должна быть распложена на том же компьютере, на котором расположен сервер Firebird.

[source,console]
----
gbak -с -se remotehost:service_mgr d:\backups\employee.fbk d:\data\employee.fdb -user sysdba -password masterkey
----

Вариант с использованием явного указания префикса протокола представлен ниже:

[source,console]
----
gbak -с -se inet://remotehost/service_mgr d:\backups\employee.fbk d:\data\employee.fdb -user sysdba -password masterkey
----

// todo: link
Существует возможность восстановления из удалённой резервной копии с использованием диспетчера служб, однако утилита `gbak` её не предоставляет. Однако вы можете воспользоваться утилитой `fbsvcmgr`. Пример использования вы можете найти в разделе "`Утилита FBSVCMGR. Восстановление (gbak)`".
====

.Восстановление из резервной копии с новым размером страницы
[example]
====
Следующая команда восстановит базу данных из резервной копии на локальном компьютере с использование диспетчера служб. База данных будет восстановлена с новым размером страницы.

[source,console]
----
gbak -с -se inet://localhost/service_mgr -user sysdba -password masterkey -p 16384 d:\backups\employee.fbk d:\data\employee.fdb
----

[NOTE]
====
Указывать опцию `-p[age_size]` имеет смысл только если резервная копия была сделана с базы данных имеющий другой размер страницы.
====

====

.Восстановление из резервной копии с логом операций gbak
[example]
====
Следующая команда восстановит базу данных из резервной копии на локальном компьютере с использование диспетчера служб. Журнал операций выполняем `gbak` будет выведен на консоль.

[source,console]
----
gbak -с -se inet://localhost/service_mgr -user sysdba -password masterkey d:\backups\employee.fbk d:\data\employee.fdb -v
----

Каждую операцию можно снабдить статистикой с помощью опции `-ST`:

[source,console]
----
gbak -с -se inet://localhost/service_mgr -user sysdba -password masterkey d:\backups\employee.fbk d:\data\employee.fdb -v -st trwd
----

Для того чтобы журнал операций `gbak` был записан в файл добавим опцию `-Y`.

[source,console]
----
gbak -с -se inet://localhost/service_mgr -user sysdba -password masterkey d:\backups\employee.fbk d:\data\employee.fdb -v -st trwd -y /copy/employee_dump.log
----

====

.Восстановление только метаданных
[example]
====
Следующая команда восстановит базу данных из резервной копии на локальном компьютере с использование диспетчера служб. В базе данных будут только метаданные (описания таблиц, представлений, хранимых, процедур и функций, триггеров, но без данных в таблицах).

[source,console]
----
gbak -с -metadata -se inet://localhost/service_mgr -user sysdba -password masterkey d:\backups\employee.fbk d:\data\employee.fdb
----
====

.Восстановление из резервной копии с исключением данных некоторых таблиц
[example]
====
Иногда требуется восстановить базу данных, но исключить из неё данные некоторых таблиц, чтобы уменьшить объём базы данных. Например, это могут быть таблицы логирования, которые могут содержать довольно значительный объём данных, но хранение которых не критично. Учтите, что от данных исключаемой таблицы не должно быть зависимостей, т.е. ссылок на её строки из других по внешнему ключу. Если таковые имеются, то их следует также исключить, в противном случае из-за нарушения ограничений целостности, база данных не может быть восстановлена.

В следующей команде будет восстановлена резервная копия из которой будут исключены данные таблиц `table1` и `table2`. Для исключения данных таблиц из базы данных используется переключатель `-SKIP_D[ATA] _pattern_`, где `_pattern_` -- регулярное выражение в SQL-синтаксисе (см. оператор `SIMILAR TO`). Из резервной копии будут исключены таблицы соответствующие регулярному выражению. Если вам необходимо исключить конкретный список таблиц, вы можете перечислить их имена, разделив их символом "`|`".

[source,console]
----
gbak -с -se inet://localhost/service_mgr -user sysdba -password masterkey -skip_data table1|table2 /copy/employee.dmp /data/employee.fdb
----
====

== Рецепты резервного копирования и восстановления

В следующих рецептах показаны примеры задач резервного копирования и восстановления с использованием `gbak`. Это, вероятно, самые частые случаи, с которыми вы можете столкнуться как администратор баз данных. Во всех примерах используется база данных сотрудников, поставляемая с Firebird, а фактическое местоположение правильно настроено в `databases.conf`. Каждый из следующих рецептов выполняется с предположением, что переменным среды `ISC_USER` и `ISC_PASSWORD` присвоены подходящие значения.

=== Предварительные условия для резервного копирования и восстановления

Если вы замените открытую и работающую базу данных, есть большая вероятность, что вы ее повредите. Для достижения наилучших результатов и минимальной вероятности повреждения базы данных вам следует закрыть ее перед заменой. Чтобы закрыть базу данных, используйте `gfix` следующим образом:

[source,console]
----
tux> gfix -shut -tran 60 employee
----

В приведенном выше примере предотвращается запуск любой новой транзакции, что предотвращает выполнение новых запросов или подключение новых сеансов к базе данных. Firebird будет ждать 60 секунд, пока все выйдут из системы и все текущие транзакции завершатся, прежде чем закрыть базу данных. Если какие-либо длительные транзакции не завершены по истечении 60 секунд, тайм аут истечёт, и база данных останется открытой.

[NOTE]
====
После завершения восстановления базы данных она автоматически откроется для использования.
====

=== Простое резервное копирование и восстановление

В этом примере создается резервная копия, а затем исходная база данных немедленно перезаписывается из новой резервной копии. Обычно это не лучшая идея, поскольку первое действие при восстановлении -- стереть оригинальную базу данных.

[source,console]
----
tux> # Backup the database.
tux> gbak -backup employee /backups/employee.fbk

tux> # Restore the database.
tux> gfix -shut -tran 60 employee
tux> gbak -replace /backups/employee.fbk employee
----

=== Только метаданные

Можно использовать `gbak` для воссоздания пустой базы данных, содержащей только различные домены, таблицы, индексы и так далее, то есть исходной базы данных, но без данных. Это может быть полезно, когда вы завершили тестирование своего приложения в тестовой среде и хотите перенести систему в производственную среду без каких-либо тестовых данных.

[source,console]
----
tux> #Backup only the database metadata.
tux> gfix -shut -tran 60 employee
tux> gbak -backup -meta_data employee employee.meta.fbk
----

Когда указанный выше файл копии восстанавливается на рабочем сервере, в базе данных будут присутствовать только метаданные.

Есть еще один способ создать базу данных без данных и только с метаданными. Просто выполните восстановление из существующего дампа, содержащего данные, и укажите ключ `-m[eta_data]` в командной строке восстановления. База данных будет восстановлена, но исходных данных не будет.

[source,console]
----
tux> #Restore only the database metadata.
tux> gbak -create employee.fbk mytest.fdb -meta_data
----

Ключ `-m[eta_data]` можно использовать как при резервном копировании, так и при восстановлении, чтобы упростить создание клонированной базы данных (или перезаписи существующей) без фактических данных.

=== Разделение резервной копии

Приложение фильтра `gsplit`, описанное в отдельном руководстве, на самом деле больше не работает. Этот фильтр поставлялся со старыми версиями InterBase и Firebird, чтобы можно было разделить большие резервные копии баз данных на несколько файлов для преодоления ограничений файловой системы. Такими ограничениями могут быть размер компакт-диска, ограничение в 2 ГБ на размер отдельных файлов на DVD и так далее.

Утилита `gbak` позволяет разбивать файлы дампа на различные размеры (минимум 2048 байт) и создает только необходимые файлы.

[source,console]
----
tux> # Backup the database to multiple files.
tux> gbak -backup employee /backups/emp.a.fbk 600m /backups/emp.b.fbk 600m
----

После каждого имени файла указывается максимальный размер этого файл. Размер по умолчанию указывается в байтах, но вы можете указать суффикс `k`, `m` или `g`, чтобы использовать единицы килобайт, мегабайт или гигабайт.

Если дамп завершается до записи в некоторые файлы, то эти файлы не создаются. Файл дампа создается только тогда, когда это необходимо.

Размер окончательного файла дампа будет игнорироваться, если база данных стала слишком большой, чтобы можно было завершить усеченное резервное копирование. Если в приведенном выше примере для резервного копирования требуется всего 1500 МБ, то последний файл будет записан с конечным размером 900 МБ, а не с указанными 600 МБ.

Для восстановления такой многофайловой резервной копии необходимо указать все имена файлов в дампе и в правильном порядке. В следующем примере показано восстановление базы данных сотрудников из двух созданных выше файлов резервной копии:

[source,console]
----
tux> # Restore the database from multiple files.
tux> gfix -shut -tran 60 employee
tux> gbak -replace /backups/employee.a.fbk /backups/employee.b.fbk employee
----

=== Изменение ODS

Обычно используется ODS той версии Firebird, которая используется для восстановления базы данных. Таким образом, приведенные выше примеры фактически изменят ODS при восстановлении базы данных. Резервное копирование должно быть выполнено с помощью утилиты `gbak`, входящей в состав старой версии InterBase или Firebird (с родной для них ODS). Восстановление следует производить с помощью `gbak` из более новой версии Firebird.

[source,console]
----
tux> setenv_firebird 2.5
Firebird environment set for version 2.5.

tux> # Check current ODS version (as root user!)
tux> gstat -h employee|grep ODS
        ODS version             11.2

tux> # Backup the (old) database.
tux> gbak -backup employee /backups/employee.2_5.fbk

tux> setenv_firebird 3.0
Firebird environment set for version 3.0.

tux> # Recreate the database and upgrade the ODS.
tux> gfix -shut -tran 60 employee
tux> gbak -replace /backups/employee.2_5.fbk employee

tux> # Check new ODS version (as root user!)
tux> gstat -h employee|grep ODS
        ODS version             12.0
----

После вышесказанного старая база данных Firebird 2.5 будет воссоздана -- с удалением старой базы данных -- как база данных Firebird 3.0 с соответствующим обновлением ODS с 11.2 до 12.0.

Сценарий `setenv_firebird` не поставляется с Firebird и просто устанавливает `PATH` и т.д., чтобы использовать правильную версию Firebird в соответствии с предоставленным параметром.

=== Изменение размера кеша

Размер страничного кеша по умолчанию задаётся при создании базы данных или может быть переопределён позже с помощью утилиты `gfix`. Утилита `gbak` может восстановить базу данных и сбросить размер кеша по умолчанию. Процесс выглядит следующим образом:

[source,console]
----
tux> # Check current cache size (as root user!)
tux> gstat -h employee | grep -i buffer
        Page buffers            0

tux> # Restore the database &amp; change the cache size.
tux> gfix -shut -tran 60 employee
tux> gbak -replace -buffer 200 /backups/employee.fbk employee

tux> # Check the new cache size (as root user!)
tux> gstat -h employee | grep -i buffer
        Page buffers            200
----

Размер кэша по умолчанию используется, когда количество буферов равно нулю, как в первом примере выше. Утилита `gbak` позволяет при желании это изменить. Однако `gbak` не может сбросить размер кэша на ноль. Для этого вы должны использовать `gfix`.

=== Изменение размера страницы

Подобно приведенному выше примеру для изменения размера кэша базы данных по умолчанию, размер страницы базы данных также можно изменить с помощью `gbak`.

[source,console]
----
tux> # Check current page size (as root user!)
tux> gstat -h employee | grep -i "page size"
        Page size               4096

tux> # Restore the database &amp; change the page size.
tux> gfix -shut -tran 60 employee
tux> gbak -replace -page_size 8192 /backups/employee.fbk employee

tux> # Check the new page size (as root user!)
tux> gstat -h employee | grep -i "page size"
        Page size               8192
----

=== Создание клона базы данных только для чтения

Иногда вы не хотите, чтобы ваш персонал, составляющий отчеты, выполнял интенсивные запросы к вашей производственной базе данных. С этой целью вы можете создать клон своей производственной базы данных и сделать ее доступной только для чтения. Это позволяет группе составления отчетов запускать столько интенсивных отчетов, сколько они пожелают, без вредных последствий для производственной базы данных и предотвращает непреднамеренное внесение изменений.

В следующем примере показана рабочая база данных `employee`, работающая на сервере Linux _tux_, клонируемая на сервер Linux группы создания отчетов с именем _tuxrep_. Сначала на рабочем сервере _tux_ выполните:

[source,console]
----
tux> # Backup the production database.
tux> gbak -backup employee /backups/employee.fbk
----

Затем на сервере _tuxrep_ группы отчетов:

[source,console]
----
tuxrep> # Scp the dump file from tux.
tuxrep> scp fbuser@tux:/backups/employee.fbk ./
Using keyboard-interactive authentication.
Password:
employee.fbk              |         19 kB |  19.3 kB/s | ETA: 00:00:00 | 100%

tuxrep> # Restore the employee database as read-only.
tuxrep> gfix -shut -tran 60 employee
tuxrep> gbak -replace -mode read_only employee.fbk employee

tuxrep> # Check database mode (as root user)
tuxrep> gstat -h employee|grep -i attributes
        Attributes              no reserve, read only
----

=== Создание клона базы данных только без файла дампа

Вы можете использовать `gbak` для создания клона базы данных на том же сервере без необходимости создавать потенциально большой файл дампа. Для этого необходимо передать вывод резервной копии `gbak` прямо на вход восстановления `gbak`, как показано ниже.

[source,console]
----
tux> # Clone a test database to the same server, without requiring a dump file.
tux> gbak -backup emptest stdout | gbak -replace stdin emptest_2
----

Обратите внимание, что имя выходного файла для резервной копии -- `stdout`, а имя входного файла для восстановления -- `stdin`. Благодаря этой способности передавать стандартный вывод одного процесса стандартному вводу другого можно избежать создания промежуточного файла дампа. Приведенные выше команды предполагают, что для `emptest` и `emptest_2` настроены подходящие псевдонимы. Если нет, вам нужно будет указать полный путь к двум базам данных, а не псевдоним.

Параметр `-replace` в процессе восстановления перезапишет указанную базу данных если он существует, и создаст её заново, в противном случае. В качестве альтернативы вы также можете использовать параметр `-recreate overwrite`. Оба имеют одинаковый результат.

Если вы не хотите перезаписывать существующие базы данных, используйте `-create`, который создаст базу данных только в том случае, если она еще не существует, и завершит работу с ошибкой в противном случае. В POSIX-совместимых системах код ошибки в `$?` в данном случае равно 1

Дополнительные примеры резервного копирования и восстановления удаленных баз данных по ssh с использованием имен файлов `stdin` и `stdout` можно увидеть ниже.

=== Резервное копирование и восстановление с теневой копией и без неё

Базы данных могут иметь прикрепленные файлы теневых копий при обычном использовании. Утилита `gbak` создает резервные копии и восстанавливает их, и при обычном использовании теневые файлы будут воссозданы. Если вы хотите восстановить только базу данных и игнорировать тени, `gbak` может сделать это за вас, как показано в следующем примере.

[source,console]
----
tux> # Check current shadows, use isql as gstat is broken.
tux> isql employee

Database:  employee
SQL> show database;
Database: employee
        Owner: SYSDBA
 Shadow 1: "/opt/firebird/shadows/employee.shd1" manual
 Shadow 2: "/opt/firebird/shadows/employee.shd2" manual
...

SQL> quit;
----

[source,console]
----
tux> # Restore the database preserving shadow files.
tux> gfix -shut -tran 60 employee
tux> gbak -replace overwrite /backups/employee.fbk employee

tux> # Check shadows again, use isql as gstat is broken.
tux> isql employee

Database:  employee
SQL> show database;
Database: employee
        Owner: SYSDBA
 Shadow 1: "/opt/firebird/shadows/employee.shd1" manual
 Shadow 2: "/opt/firebird/shadows/employee.shd2" manual
...

SQL> quit;
----

[source,console]
----
tux> # Restore the database killing shadow files.
tux> gfix -shut -tran 60 employee
tux> gbak -replace overwrite -kill /backups/employee.fbk employee

tux> # Check shadows again, use isql as gstat is broken.
tux> isql employee

Database:  employee
SQL> show database;
Database: employee
        Owner: SYSDBA
...

SQL> quit;
----

Я использую `isql` в приведенных выше примерах, так как `gstat -h`, кажется, не понимает, сколько теней существует в базе данных. Он сообщает об нуле, когда их два, в конце концов он догоняет и сообщает, что их двое, затем, если вы убиваете тень, он сообщает, что теперь их три!

=== Удаленное резервное копирование и восстановление

Утилита Firebird `gbak` может создавать резервные копии удаленной базы данных. Для этого вам необходимо подключиться к диспетчеру служб, запущенному на удаленном сервере, обычно он называется `service_mgr`. В следующем примере показано резервное копирование базы данных сотрудников Firebird на сервере _tuxrep_ с сервера _tux_. Резервная копия будет записана на удаленный сервер, другими словами, файл резервной копии будет создан на сервере _tuxrep_, а не на сервере _tux_. Используемый сетевой протокол -- TCP.

[source,console]
----
tux> # Backup the reporting database on remote server tuxrep.
tux> gbak -backup -service tuxrep:service_mgr employee /backups/remote_backup.fbk
----

Файл резервной копии будет иметь того же владельца и группу, что и сервер базы данных Firebird -- по крайней мере, в системах Unix.

Таким же образом можно восстановить удаленную базу данных, и `gbak` позволяет это.

[source,console]
----
tux> # Restore the read-only reporting database on remote server tuxrep.
tux> gbak -replace -mode read_only -service tuxrep:service_mgr \
     /backups/remote_backup.fbk employee
----

[NOTE]
====
В приведенном выше примере используется удобная способность Unix разбивать длинную строку на множество более коротких, используя обратную косую черту в качестве последнего символа в строке.
====

Как всегда, вам рекомендуется остерегаться замены базы данных в случае возникновения проблем во время восстановления. В приведенном выше примере воссоздается существующая база данных в режиме только для чтения, но это не всегда так.

Удаленное резервное копирование также можно запустить на самом сервере базы данных! В Windows это не имеет значения, но в системах Unix этот локально-удаленный метод резервного копирования и восстановления снижает сетевой трафик. "`Удаленный`" сервер в этом случае фактически не является удаленным, это просто способ запуска резервного копирования -- подключение к диспетчеру служб -- подразумевает удаленность.

[source,console]
----
tux> # Backup the employee database on this server, but pseudo-remotely!
tux> gbak -backup -service tux:service_mgr employee /backups/remote_backup.fbk
----

Соответствующее восстановление также можно запускать удаленно:

[source,console]
----
tux> # Restore the employee database on this server, but pseudo-remotely!
tux> gbak -replace -service tux:service_mgr /backups/remote_backup.fbk employee
----

Формат параметра, используемого для переключателя `-service`, различается в зависимости от характера используемого сетевого протокола:

* *TCP* -- При использовании сетей TCP разделителем параметров является двоеточие, например `-service server_name:service_mgr`. В Firebird 3.0 допускается также указание префикса протокола в url подобном синтаксисе `-service inet://server_name/service_mgr`. Вы можете уточнить версию используемого TCP протокола с помощью префиксов `inet4` или `inet6`.
* *Named pipes* -- При использовании именованных каналов для параметра требуются две ведущие обратные косые черты, а в качестве разделителя используется еще одна обратная косая черта, как в `-service \\server_name\service_mgr`. Как и в случае TCP протокола, вы можете воспользоваться URL подобным синтаксисом. В этом случае указание параметра будет выглядеть следующим образом `-service wnet://server_name/service_mgr`.

=== Удаленное резервное копирование и восстановление с помощью SSH

Как показано выше, вы можете использовать специальные имена файлов `stdin` и `stdout` для резервного копирования и восстановления базы данных в отдельную базу данных на том же сервере. Однако вы также можете использовать те же инструменты через SSH-соединение с удаленным сервером и передать резервную копию одной базы данных напрямую для восстановления другой.

В первом примере локальная база данных копируется на удаленный сервер, на котором запущен Firebird, а среда пользователя *firebird* настроена так, что инструмент `gbak` по умолчанию находится в `$PATH` при входе в систему.

[NOTE]
====
В каждом из следующих примеров параметры `-user sysdba` и `-password` в командной строке заменены на `{...}`. При выполнении этих команд любые удаленные команды `gbak` потребуют их указания, если только пользователь *firebird* в удаленных базах данных не имеет `ISC_USER` и `ISC_PASSWORD` определенных в файлах входа в систему `.profile` или `.bashrc` (или эквивалентных). Однако это очень плохая идея и невероятно небезопасная.
====

[source,console]
----
tux> # Clone a test database to a different server, without requiring a dump file.
tux> gbak -backup employee stdout | \
ssh firebird@tuxrep "gbak {...} -replace stdin emptest"
----

Когда это будет выполнено, вам будет предложено ввести пароль для удаленного пользователя *firebird* на сервере _tuxrep_, предполагая, что у вас нет уже настроенной и активной пары ключей SSH. Команда заменит локальную базу данных в соответствии с псевдонимом `emptest`, но при необходимости вы можете указать полные имена путей для баз данных. Ниже показан пример выполнения вышеуказанного.

[source,console]
----
tux> # Clone a test database to a different server, without requiring a dump file.
tux> gbak -backup employee stdout | \
ssh firebird@tuxrep "gbak {...} -replace stdin emptest"

firebird@tuxrep's password:
----

Как видите, вывода не так много, но вы можете подключиться удаленно и проверить:

[source,console]
----
tux> isql {...} tuxrep:emptest

Database:  tuxrep:emptest

SQL> show database;

Database: tuxrep:emptest
        Owner: SYSDBA
PAGE_SIZE 4096
...
----

В следующем примере показано резервное копирование удаленной базы данных в локальную аналогичным образом.

[source,console]
----
tux> ssh firebird@tuxrep "gbak -backup {...} emptest stdout" | \
gbak -create stdin data/tuxrep_emptest.fdb

firebird@tuxrep's password:

tux> ls data

employee.fdb  tuxrep_emptest.fdb
----

Вы видите, что создана новая база данных `tuxrep_emptest.fdb`. Это работает? Проверка с помощью `isql` показывает, что это так.

[source,console]
----
tux> isql data/tuxrep_emptest.fdb

Database:  data/tuxrep_emptest.fdb

SQL> quit;
----

В последнем примере показано, как сделать резервную копию удаленной базы данных на одном сервере в удаленную базу данных на другом.

[source,console]
----
tux> ssh firebird@tuxrep "gbak -backup {...} emptest stdout" |  \
ssh firebird@tuxqa "gbak -create {...} stdin data/tuxrep_empqa.fdb"

firebird@tuxrep's password:
firebird@tuxqa's password

tux> ssh firebird@tuxqa "ls data"

employee.fdb  tuxrep_empqa.fdb
----

=== Использование внешних инструментов

`gbak` и `nbackup` -- лучшие инструменты для резервного копирования и/или восстановления баз данных Firebird. Они были тщательно протестированы и знают внутреннее устройство базы данных и то, как она работает, поэтому шансы, что эти инструменты повредят ваши ценные данные, очень малы. Однако некоторые администраторы баз данных по-прежнему предпочитают использовать внешние инструменты (не поставляемые с Firebird) для создания резервных копий по какой-либо причине.

Поскольку внешние инструменты не могут знать, где находится база данных, с учетом псевдонима, автор сценария и/или DBA должны явно определить правильное местоположение файла(ов) базы данных и передать их внешнему орудие труда. Чтобы упростить эту задачу для авторов сценариев, моя собственная установка использует стандарт в моем файле `databases.conf` следующим образом:

* Псевдоним базы данных должен начинаться с первого столбца.
* Перед знаком равенства (=) должен стоять один пробел.
* После знака равенства (=) должен быть один пробел.
* Двойные кавычки вокруг имени файла базы данных не допускаются -- это также не работает для утилит Firebird.
* Все базы данных представляют собой однофайловые базы данных.

Последнее правило применяется только к моей установке и означает, что следующий простой сценарий резервного копирования будет работать. Если бы использовалось многофайловые баз данных, потребовалось бы больше кода для создания резервной копии с использованием внешних инструментов.

[source,console]
----
tux> cat /opt/firebird/aliases.conf
# ---------------------------------------------------------
# WARNING: Backup Standards require that:
#          The database name starts in column 1.
#          There is a single space before the equals sign.
#          There is a single space after the equals sign.
#          The path has no double quotes (they don't work!)
# ----------------------------------------------------------
employee = /opt/firebird/examples/empbuild/employee.fdb
----

Ниже показано использование утилиты `gzip` на сервере Linux для создания и сжатия резервной копии работающей базы данных. Следующее запускается от имени пользователя `root` из-за необходимости запуска `gfix` для завершения работы базы данных.

[source,console]
----
tux> # Backup the production employee database using gzip.
tux> gfix -shut -tran 60 employee
tux> DBFILE=`grep -i "^employee =" /opt/firebird/aliases.conf | cut -d" " -f3`
tux> gzip -9 --stdout $DBFILE > /backups/employee.fdb.gz
----

Процесс восстановления для этой базы данных будет обратным описанному выше. Опять же, следующий сценарий запускается как `root`.

[source,console]
----
tux> # Restore the production employee database from a gzip backup.
tux> gfix -shut -tran 60 employee
tux> DBFILE=`grep -i "^employee =" /opt/firebird/aliases.conf | cut -d" " -f3`
tux> gunzip --stdout /backups/employee.fdb.gz > $DBFILE

tux> # Make sure firebird can see the file.
tux> chown firebird:firebird $DBFILE
----

== Предостережения gbak

Ниже приводится краткий список подводных камней и забавных моментов, которые я обнаружил при собственном использовании `gbak`. Некоторые из них упомянуты выше, другие могут не упоминаться. Собрав их все в одном месте, вы сможете узнать, что происходит, если у вас возникнут проблемы.

=== Gbak режим по умолчанию

Если вы не укажете переключатель режима, такой как `-b[ackup]` или `-c[reate]`, то `gbak` выполнит резервное копирование, как если бы был указан переключатель `-b[ackup]` -- при условии, что другие указанные переключатели верны для резервного копирования.

[WARNING]
====
Это определение того, пытаетесь ли вы выполнить резервное копирование или восстановление, означает, что если вы используете параметр командной строки `-z` для просмотра информации `gbak`, то вы создадите резервную копию и перезапишете предоставленный вами файл резервной копии, если в командной строке также есть присутствует имя базы данных и имя файла резервной копии. Это предполагает, что у `gbak` есть способ определить имя пользователя и пароль, которые будут использоваться -- либо как параметры командной строки, либо через определенные переменные среды.
====

=== Обычные и привилегированные пользователи

Только `SYSDBA` или владелец базы данных могут сделать резервную копию базы данных, однако любой аутентифицированный пользователь может восстановить резервную копию базы данных с помощью переключателя `-c[reate]`. Это означает, что вы должны убедиться, что ваши файлы резервных копий не попадут в чужие руки, потому что тогда нет ничего, что могло бы помешать неавторизованным людям увидеть ваши данные с помощью простого процесса восстановления ваших резервных копий на их сервере.

Конечно, восстановление базы данных не удастся, если выполняющий его пользователь не является владельцем базы данных и база данных с таким же именем файла уже существует.

=== Молчаливый запуск

Ключ `-y suppress_output` должен подавлять весь вывод. Фактически аналогично запуску без переключателя `-v[erify]`. Однако `-y suppress_output` заставляет вывод (в соответствии с настройкой переключателя `-v[erify]`) записываться в файл с именем `suppress_output`. К сожалению это работает только один раз, потому что следующий запуск `gbak -с -y suppress_output` завершится неудачно, потому что файл `suppress_output` уже существует.

Возможно, эта проблема появилась в версии 2 для Firebird, потому что версии 2.0 и 2.1 фактически используют переключатель `-y suppress`, а не `-y suppress_output`. Использование этой (более короткой) опции действительно работает по назначению, и вывод действительно подавляется.

=== Файл журнала gbak не может быть перезаписан

Если вы укажете имя файла журнала с помощью переключателя `-y _log_file_`, и файл уже существует, то даже если пользователь firebird владеет файлом и имеет права на запись в него, gbak не может его перезаписать. Вы всегда должны указывать имя несуществующего файла журнала. В системах Linux может помочь следующее:

[source,console]
----
tux> # Generate unique dump and logfile name.
tux> FILENAME=employee_`date "+%Y%m%d_%H%M%S"`

tux> # Shut down and Backup the database
tux> gfix -shut -tran 60 employee
tux> gbak -backup employee /backups/${FILENAME}.fbk -y /logs/${FILENAME}.log -v
----

Вышеуказанное весьма полезно, поскольку предотвращает перезапись предыдущих резервных копий, которые могут потребоваться. Обратной стороной является то, что теперь вам необходимо внедрить систему обслуживания, чтобы убрать старые, ненужные резервные копии, чтобы предотвратить переполнение дискового пространства под область резервных копий.

=== Использование имен файлов stdin или stdout

Утилита `gbak` распознает строковые литералы `stdin` и `stdout` как имена файлов источника или назначения. В системах POSIX, когда используются стандартные входные и/или выходные каналы, не разрешается выполнять операции поиска на этих каналах. Использование `stdin` или `stdout` в качестве имен файлов заставит `gbak` использовать обработку, которая не будет искать во входных или выходных каналах, что делает их пригодными для использования в качестве конвейера -- согласно примерам в разделе рецептов выше.

Эти имена файлов, хотя они кажутся именами POSIX, определенно не являются синонимами для `/dev/stdin` или `/dev/stdout`, они просто литералы, которые `gbak` проверяет при обработке своих параметров. Не пытайтесь использовать имена `/dev/stdin` или `/dev/stdout` в конвейерном процессе, так как это, скорее всего, потерпит неудачу.

Если вы хотите создать файл дампа с именем `stdin` или `stdout`, вы должны указать имя файла как полный или относительный путь, например `./stdin` или `./stdout`, что заставляет `gbak` рассматривать их как буквальное имя файл, а не специальное имя файла, которое вызывает отличную от нормальной обработку во время процесса дампа или восстановления.
