[[fbadmgd-config]]
= Описание параметров конфигурации

Для настройки сервера Firebird используется файл `firebird.conf`. Настройки считываются из файла один раз при старте сервера, если архитектура SuperSever или SuperClassic, и при каждом соединении с базой, если архитектура сервера Classic.

По умолчанию все параметры в файле конфигурации закомментированы. Для обозначения комментариев используется символ "`#`".

Текст, следующий после символа "`#`" , до конца строки является комментарием, например:

[listing]
----
#комментарий
DefaultDbCachePages = 2048 #комментарий
----

Максимальная длина строки в файле конфигурации сервера равна 80 символов.

Первое слово в строке, начинающейся не с символа комментария, считается названием параметра. Справа от имени параметра, после символа "`=`", указывается значение параметра.

[[fbadmgd-config-param_types]]
== Типы параметров

В файле конфигурации присутствуют параметры трех типов: 

* целочисленный (Integer);
* строковый (String);
* логический (Boolean).


[[fbadmgd-config-param_types_integer]]
=== Целочисленные параметры

Целочисленные как ясно из названия могут содержать только целые числа. Они могут быть записаны со множителями `k`, `m` и `g`.

.Целочисленные параметры
[example]
====
[listing]
----
MaxUnflushedWrites = 100                        
DefaultDbCachePages = 8K        # 8 * 1024 = 8192
DatabaseGrowthIncrement = 128M  # 128 * 1024 * 1024
----
====

[NOTE]
====
Значения параметров, определяющих объем памяти, указываются в байтах. В конце таких значений можно ставить сокращения `k`, `m` и `g`, соответствующие килобайтам, мегабайтам и гигабайтам. 
====

[[fbadmgd-config-param_types_boolean]]
=== Логические параметры

Логическое значение выражается в виде целочисленных значений, где 0 (ноль) означает `false`, а ненулевое значение означает `true`. Для согласованности мы рекомендуем использовать только 0/1. Также строки 'y', 'yes' и 'true' означают `true`, а 'n', 'no' и 'false' -- `false`.

.Логические параметры
[listing]
====
[listing]
----
RemoteAccess = true       # true
RemoteFileOpenAbility = 0 # false
----
====

[[fbadmgd-config-param_types_string]]
=== Строковые параметры

Строковые как ясно из названия представляют собой строки.

.Строковые параметры
[example]
====
[listing]
----
RemoteServiceName = gds_db
RemotePipeName = pipe47
----
====

[[fbadmgd-config-scope]]
== Область действия

Параметры конфигурации могут быть применены к экземпляру сервера (Per-server), отдельной базе данных (Per-database) или отдельному соединению (Per-connection).

Параметры, которые могут быть применены к отдельной базе данных можно указывать в файле `databases.conf`.
В этом случае они перекроют значение одноимённого параметра указанного в `firebird.conf`.

Параметры, которые могут быть применены к отдельному соединению, предназначены для использования на стороне клиента.
Они устанавливаются с помощью `isc_dpb_config` параметра в DPB (Database parameters buffer) (`isc_spb_config` для служб).

[NOTE]
====
Параметры уровня базы данных могут быть установлены используя DPB при первом соединении с базой данных, если используется встроенный режим сервера.
====

Параметры, которые могут быть применены к отдельному соединению, могут быть прочитаны из файлов `firebird.conf` и `databases.conf` расположенных в том же каталоге, что и клиентская библиотека `fbclient`. Эти параметры будут перекрыты установками через DPB.

[[fbadmgd-config-macro]]
== Макроподстановки

Существует ряд предопределенных макроподстановок, которые могут быть использованы в файлах конфигурации, где требуется имя каталога.

Они используют следующий синтаксис:

[listing]
----
$(<name>)
----

Полный список таких макроподстановок представлен ниже: 

root:: корневой каталог экземпляра сервера;
install:: директория в которую установлен Firebird. Изначально `$(root)` и `$(install)` одинаковые. `$(root)` может быть переопределена установкой или изменением переменной окружения FIREBIRD. В таком случае эта подстановка отлична от `$(install)`;
this:: каталог, в котором находится текущий файл конфигурации;
dir_conf:: каталог, в котором расположены файлы конфигурации `firebird.conf` и `databases.conf`;
dir_secDb:: директория, в которой расположена база данных безопасности по умолчанию;
dir_plugins:: директория, в которой расположены плагины;
dir_udf:: директория, предназначенная для размещения UDF функций по-умолчанию;
dir_sample:: каталог с примерами (`examples`);
dir_sampleDb:: директория, где лежит пример базы данных (`examples/empbuild`);
dir_intl:: директория, в которой расположены библиотеки интернационализации;
dir_msg:: каталог, в котором расположен файл с сообщениями сервера `firebird.msg`. Обычно он совпадает с `$(root)`, но может быть переопределён переменной окружения `FIREBIRD_MSG`.


[NOTE]
====
Внутренние макроподстановки не чувствительны к регистру. Большие буквы используются исключительно для повышения читабильности.
====

.Пример использования макроподстановки в файле databases.conf
[example]
====
[listing]
----
employee = $(dir_sampleDb)/employee.fdb
----
====

[[fbadmgd-config-includes]]
== Включение других файлов

Один файл конфигурации может включать другой с помощью директивы `include`:

[listing]
----
include some_file.conf
----

Относительный путь представляет собой путь по отношению к текущему файлу конфигурации. Так, в примере выше файл `/opt/config/master.conf` ссылается на файл расположенный по пути `/opt/config/some_file.conf`.

Директива include поддерживает групповые символы "`*`" и "`?`". Все совпадающие с шаблоном файлы будут подключены, порядок включения не определён.

.Использование групповых символов с директивой include
[example]
====
[listing]
----
include $(dir_plugins)/config/*.conf
----
====

[[fbadmgd-config-perdb]]
== Параметры уровня базы данных

Настройка конфигурации на уровне базы данных осуществляется с помощью формальных записей в файле `databases.conf`.
Такие параметры помечены как "`Per-database`".

[[fbadmgd-config-perdb_format]]
=== Формат конфигурационных записей

Если вы не добавляете каких либо специфичных для базы данных директив конфигурации для псевдонима, то формат будет такой же, как он был в `aliases.conf` (Firebird 2.5 и ранее):

[listing]
----
emp = c:\Program Files\examples\empbuild\employee.fdb
# или
emp = /opt/firebird/examples/empbuild/employee.fdb
# или
emp = $(dir_sampleDb)/employee.fdb
----

Несколько более сложный формат используется для случаев, когда определенные не глобальные параметры должны быть нацелены на отдельные базы данных. Запись для базы данных определяется объявлением псевдонима, как и ранее. Директивы, относящиеся к базе данных, перечислены ниже в фигурных скобках.

[listing]
----
# Directives for MYBIGDB
MYBIGDB = opt/databases/mybigdb.fdb
{
    LockMemSize = 32M           # We know that MYBIGDB needs a lot of locks
    LockHashSlots = 19927       # and a hash table large enough for them
}
----

[[fbadmgd-config-perdb_params]]
=== Доступные параметры

Следующие параметры можно скопировать/вставить в файл `database.conf` и использовать в качестве переопределений для конкретных баз данных. 

.Параметры доступные в databases.conf
[cols="1,1,1", frame="all"]
|===
3+|**Связанные с ядром сервера**

|<<fbadmgd-config-param_databasegrowthincrement,DatabaseGrowthIncrement>>
|<<fbadmgd-config-param_deadlocktimeout,DeadlockTimeout>>
|<<fbadmgd-config-param_defaultdbcachepages,DefaultDbCachePages>>

|<<fbadmgd-config-param_eventmemsize,EventMemSize>>
|<<fbadmgd-config-param_filesystemcachethreshold,FileSystemCacheThreshold>>
|<<fbadmgd-config-param_externalfileaccess,ExternalFileAccess>>

|<<fbadmgd-config-param_gcpolicy,GCPolicy>>
|<<fbadmgd-config-param_lockacquirespins,LockAcquireSpins>>
|<<fbadmgd-config-param_lockhashslots,LockHashSlots>>

|<<fbadmgd-config-param_lockmemsize,LockMemSize>>
|<<fbadmgd-config-param_maxunflushedwrites,MaxUnflushedWrites>>
|<<fbadmgd-config-param_maxunflushedwritetime,MaxUnflushedWriteTime>>

|<<fbadmgd-config-param_securitydatabase,SecurityDatabase>>
|<<fbadmgd-config-param_usermanager,UserManager>>
|

|<<fbadmgd-config-param_wirecompression,WireCompression>>
|<<fbadmgd-config-param_wirecrypt,WireCrypt>>
|<<fbadmgd-config-param_wirecryptplugin,WireCryptPlugin>>

|**Связанные с клиентом**
2+|Некоторые параметры могут быть настроены в клиентском соединении через DPB/SPB, в качестве альтернативы их настройке в `database.conf`. Подробнее смотри в <<fbadmgd-config-scope,Область действия>>.

|<<fbadmgd-config-param_auth,AuthClient>>
|<<fbadmgd-config-param_providers,Providers>>
|{nbsp}

3+|Следующие параметры могут быть настроены на стороне клиента только через DPB/SPB.

|<<fbadmgd-config-param_connectiontimeout,ConnectionTimeout>>
|<<fbadmgd-config-param_dummypacketinterval,DummyPacketInterval>>
|<<fbadmgd-config-param_ipcname,IpcName>>

|<<fbadmgd-config-param_remoteauxport,RemoteAuxPort>>
|<<fbadmgd-config-param_remotepipename,RemotePipeName>>
|<<fbadmgd-config-param_remoteserviceport,RemoteServiceName>>

|<<fbadmgd-config-param_remoteserviceport,RemoteServicePort>>
|<<fbadmgd-config-param_tcpnonagle,TCPNoNagle>>
|{nbsp}
|===

[[fbadmgd-config-common]]
== Общие настройки

[[fbadmgd-config-param_databaseaccess]]
=== DatabaseAccess
(((Параметр конфигурации,DatabaseAccess)))

.Область действия:
Per-server.

.Тип параметра:
String (специальный формат).

.Синтаксис
[listing]
----
DatabaseAccess = None | Full | { Restrict <dir_1>[;<dir_2>[...;<dir_N>] }
----

Параметр `DatabaseAccess` позволяет обеспечить управление безопасностью при доступе к файлам базы данных. Доступ к файлам базы данных на сервере может быть полным (`Full`), ограниченным (`Restrict`) или запрещённым (`None`).

Параметр `DatabaseAccess` имеет строковый тип; по умолчанию значение параметра равно `Full` -- полный доступ.

Для ограничения доступа используется параметр `Restrict`. В этом случае после слова `Restrict` указываются директории, в которых могут быть сохранены файлы базы данных. При указании списка каталогов могут быть использованы как абсолютные, так и относительные пути. Относительные пути считаются от корневого каталога сервера Firebird. В качестве разделителя каталогов используется символ "`;`".

Если параметр `DatabaseAccess` установлен в значение `None`, то позволено соединяться только с базами данных, перечисленными в файле `databases.conf`.

.Значения параметра `DatabaseAccess`
[example]
====
[source]
----
DatabaseAccess = None
DatabaseAccess = Restrict C:\DataBase
DatabaseAccess = Restrict C:\DataBase;D:\Mirror
DatabaseAccess = Restrict /db
DatabaseAccess = Restrict /db;/mnt/mirrordb
DatabaseAccess = Full
----
====

[WARNING]
====
Неконтролируемый доступ к файлам баз данных может поставить под угрозу безопасность вашей системы. Поэтому настоятельно рекомендуем ограничивать директории для размещения баз данных.
====

[[fbadmgd-config-param_remoteaccess]]
=== RemoteAccess

.Область действия:
Per-database.

.Тип параметра:
Boolean.

Параметр предоставляет или отменяет удалённый доступ к базам данных.

[listing]
----
RemoteAccess = true
----

По-умолчанию `RemoteAccess` включен для всех баз данных, за исключением базы данных безопасности. Если вы намереваетесь использовать больше одной специализированной базы безопасности, то рекомендуем отключить удалённый доступ к ним в файле `databases.conf`.

Для повышения безопасности можно отключить `RemoteAccess` глобально в файле `firebird.conf` и включить его для отдельных баз данных в `databases.conf`.

Параметр имеет тип Boolean и может принимать значения `true`/`false`, `1`/`0` или `yes`/`no`.

[[fbadmgd-config-param_externalfileaccess]]
=== ExternalFileAccess
(((Параметр конфигурации,ExternalFileAccess)))

.Область действия:
Per-database.

.Тип параметра:
String (специальный формат).

.Синтаксис
[listing]
----
ExternalFileAccess = None | Full | { Restrict <dir_1>[;<dir_2>[...;<dir_N>] }
----

Параметр `ExternalFileAccess` позволяет управлять правами размещения файлов внешних таблиц. Разрешение на доступ к внешним файлам может быть полным (`Full`), ограниченным (`Restrict`) или запрещённым (`None`).

Параметр `ExternalFileAccess` имеет строковый тип; значение по умолчанию равно `None` -- запрет на создание внешних таблиц. Для того, чтобы разрешить создание и доступ к внешним файлам, следует выставить значение параметра равным `Full`.

Для ограничения доступа используется значение `Restrict`. В этом случае после слова `Restrict` указываются директории, в которых могут быть сохранены файлы внешних таблиц. При указании каталогов могут быть использованы как абсолютные, так и относительные пути. Относительные пути берутся от корневого каталога Firebird. В качестве разделителя директорий используется символ "`;`".

.Примеры задания значения параметра `ExternalFileAccess`
[example]
====
[source]
----
ExternalFileAccess = None
ExternalFileAccess = Restrict C:\DataBase
ExternalFileAccess = Restrict C:\DataBase;D:\Mirror
ExternalFileAccess = Restrict /db;/mnt/mirrordb
ExternalFileAccess = Full
----
====

[WARNING]
====
Неконтролируемая возможность использования внешних таблиц может поставить под угрозу безопасность вашего сервера. Поэтому настоятельно рекомендуется использовать этот параметр для ограничения директорий размещения внешних таблиц.
====

[[fbadmgd-config-param_udfaccess]]
=== UdfAccess

.Область действия:
Per-server.

.Тип параметра:
String (специальный формат).

.Синтаксис
[listing]
----
UdfAccess = None | Full | { Restrict <dir_1>[;<dir_2>[...;<dir_N>] }
----

Параметр `UdfAccess` предназначен для определения директорий, в которых могут быть сохранены библиотеки UDF. Разрешение на доступ к библиотекам внешних функций может быть полным (`Full`), ограниченным (`Restrict`) или запрещённым (`None`).

Параметр `UdfAccess` имеет строковый тип; значение по умолчанию равно Restrict UDF -- udf-библиотеки ищутся только в корневом каталоге сервера в папке `udf`. Для того, чтобы запретить использование udf, нужно выставить значение параметра равным None.

При указании каталогов могут быть использованы как абсолютные, так и относительные пути. Относительные пути берутся от корневого каталога сервера Firebird. В качестве разделителя директорий используется символ "`;`".

[listing]
----
UdfAccess = Restrict UDF
----

[WARNING]
====
Неконтролируемая возможность использования внешних функций может быть использована для того, чтобы поставить под угрозу безопасность как баз данных, так и всей системы. Поэтому настоятельно рекомендуется использовать данный параметр для ограничения директорий размещения udf-библиотек.
====

[NOTE]
====
Этот параметр никак не влияет на правила размещения нового типа внешних библиотек UDR.
====

[[fbadmgd-config-param_tempdirectories]]
=== TempDirectories
(((Параметр конфигурации,TempDirectories)))

.Область действия:
Per-server.

.Тип параметра:
String (специальный формат).

С помощью параметра `TempDirectories` можно задать временный каталог сервера Firebird. Временный каталог необходим для выгрузки данных во время сортировки (и в некоторых других случаях), когда исчерпывается выделенная оперативная память.

Параметр `TempDirectories` имеет строковый тип; значение по умолчанию равно пустой строке. Если параметр `TempDirectories` не активен, то путь к временному каталогу определяется исходя из значения переменных окружения `FIREBIRD_TMP`, `TEMP`, `TMP`. Если никакая из вышеперечисленных переменных не задана, то значением для POSIX будет каталог `/tmp`, а для Windows -- `C:\TEMP`.

В качестве значения параметра может быть задан путь к одному или нескольким каталогам. В этом случае выгрузка временных данных при сортировке будет осуществляться в указанные каталоги. Для папок допускаются как абсолютные, так и относительные пути. Относительные пути берутся от корневого каталога инсталляции сервера Firebird. Если требуется определить несколько временных каталогов, то в качестве разделителя используется символ "`;`".

Если указана одна или несколько директорий, то выгрузка временных данных при сортировке будет осуществляться в указанные каталоги по очереди (если в текущей временной директории не осталось места, то временные файлы будут сохраняться в следующую по списку).

.Примеры задания значения параметра TempDirectories
[example]
====
[listing]
----
TempDirectories = c:\temp
TempDirectories = c:\temp;d:\temp
----
====

Количество ресурсов, выделяемых под `TempDirectories`, следует увеличивать, если планируется восстановление базы (restore), имеющей большие индексы. Иначе могут возникнуть проблемы с нехваткой места для `fb_sort*` файлов, создаваемых СУБД в процессе построения индексов (СУБД не будет запрашивать у операционной системы новое место в этом случае).

.Замечания
[NOTE]
====
* Данные GTT (глобальных временных таблиц) хранятся в файлах с маской `fb_table*`, создаваемых в каталогах, заданных переменными `FIREBIRD_TMP` (затем -- `TMP`; при отсутствии их обоих GTT-данные будут сохраняться -- для POSIX -- в каталоге `/tmp`). СУБД при определении места, где надо хранить GTT-данные, не учитывает значение параметра `TempDirectories`. Поэтому правильным методом является назначение переменной `FIREBIRD_TMP` того же каталога, что указан в `TempDirectories`.

* В POSIX временные файлы, создаваемые СУБД (`fb_table*`, `fb_sort*`, `fb_recbuf*`, `fb_blob*`, `fb_merge*`), сразу маркируются как "`deleted`" и не видны при обычном просмотре каталога. Для получения их списка воспользуйтесь, например, пакетом `lsof` с указанием в качестве аргумента PID процесса Firebird (если он работает как SuperServer или SuperClassic).

* В следующем примере процесс firebird имеет PID = 9447, и для получения открытых им временных файлов следует ввести команду:
+
[listing]
----
#lsof -p 9447 | grep "/fb_table\|/fb_sort\|/fb_recbuf\|/fb_blob\|/fb_merge"
----
+
Пример вывода:
+
[listing]
----
firebird 9447 firebird  296u REG  253,0    147456  2490547 /tmp/fb_table_5aNN2s 
  (deleted)
firebird 9447 firebird 1503u REG  253,0    147456  2490573 /tmp/fb_table_0Jwjo3 
  (deleted)
firebird 9447 firebird  623u REG   0,16  75497472 25189649 /tmp/fb_sort_kv21Av 
  (deleted)
firebird 9447 firebird  296u REG  253,0    147456  2490547 /tmp/fb_table_5aNN2s 
  (deleted)
----

* В Windows временные файлы видны, но их равен нулю до тех пор, пока остается свободная память, заданные параметром `TempCacheLimit`.

====

[[fbadmgd-config-param_audittraceconfigfile]]
=== AuditTraceConfigFile

.Область действия:
Per-server.

.Тип параметра:
String.

Параметр `AuditTraceConfigFile` в файле конфигурации `firebird.conf` задает имя и расположение файла с настройками системного аудита. Этот параметр имеет строковый тип и по умолчанию имеет пустое значение. Пустое значение параметра означает, что системный аудит выключен.

Указанный файл конфигурации должен иметь ту же структуру, что и `fbtrace.conf`.

.Примеры задания значения параметра `AuditTraceConfigFile`
[example]
====
[source]
----
AuditTraceConfigFile = fbtrace.conf
----
====

[[fbadmgd-config-param_maxusertracelogsize]]
=== MaxUserTraceLogSize
(((Параметр конфигурации,MaxUserTraceLogSize)))

.Область действия:
Per-server.

.Тип параметра:
Integer.

Задает максимальный суммарный размер (в мегабайтах) временных файлов, создаваемых сессией пользовательской трассировки. После прочтения временного файла приложением он автоматически удаляется. Параметр имеет целочисленный тип. Единица измерения -- мегабайты. По умолчанию максимальный размер файла вывода ограничен 10 МБ. Если значения ограничения `MaxUserTraceLogSize` достигнуто, то сервер автоматически приостанавливает сессию слежения.

.Примеры задания значения параметра `MaxUserTraceLogSize`
[example]
====
[source]
----
MaxUserTraceLogSize = 10
----
====

[NOTE]
====
Количество пользовательских сессий трассировки, которые можно запускать на одном сервере, ничем не ограничено. Указанный параметр лимитирует размер файлов для каждой отдельной сессии трассировки, а не для всех сеансов. Поэтому общий размер временных файлов может превышать 10 Мб.
====

[[fbadmgd-config-param_defaultdbcachepages]]
=== DefaultDbCachePages

.Область действия:
Per-database.

.Тип параметра:
Integer.

Параметр `DefaultDbCachePages` используется для настройки количества страниц одной базы данных, находящихся в кеш-памяти одновременно. SuperServer использует единый страничный кеш (2048 страниц по умолчанию) для всех подключений. Classic и SuperClassic создает отдельный страничный кеш (по умолчанию 256 страниц) для каждого соединения.

Параметр имеет целочисленный тип. Допустимо использовать множители (k, m, g). Максимальное значение 2147483647 страниц.

Этот параметр может быть установлен для каждой базы данных индивидуально в файле `databases.conf`. Это особенно удобно если на вашем сервере находятся несколько разных баз данных под управлением одного экземпляра Firebird.

Размер страничного кеша может быть установлен на странице заголовков файла базы данных с помощью утилиты `gfix`.

[listing]
----
gfix -b[uffers] <page-count> <database>
----

В этом случае размер страничного кеша устанавливается для каждой базы одновременно. На наш взгляд предпочтительно делать это в файле `databases.conf`, где вы можете установить и другие параметры индивидуальные для вашей базы данных.

Обратите внимание, размер страничного кеша установленный на уровне заголовка базы данных перекрывает значение установленное в `firebird.conf` и `databases.conf`.

[TIP]
====
Чтобы проверить установлен ли размер страничного кеша на уровне заголовка базы данных вы можете воспользоваться утилитой `gstat`

[listing]
----
d:\fb\fb30>gstat -u sysdba -p masterkey -h testdb
----

[listing]
----
Database "d:\fb\fb30\data\testdb.fdb"
Gstat execution time Wed Jul 17 12:59:26 2019

Database header page information:
        Flags                   0
        Generation              2180
        System Change Number    0
        Page size               16384
        ODS version             12.0
        Oldest transaction      2037
        Oldest active           2038
        Oldest snapshot         2038
        Next transaction        2038
        Sequence number         0
        Next attachment ID      391
        Implementation          HW=AMD/Intel/x64 little-endian OS=Windows CC=MSVC
        Shadow count            0
        Page buffers            0
        Next header page        0
        Database dialect        1
        Creation date           Jun 28, 2016 18:04:35
        Attributes              force write

    Variable header data:
        Sweep interval:         20000
        *END*
Gstat completion time Wed Jul 17 12:59:26 2019
----

Page buffers -- размер кэша базы данных. Если это значение равно 0, то будет использоваться значение параметра `DefaultDbCachePages` в `firebird.conf` или `databases.conf`.
====

При изменении данного параметра стоит учитывать архитектуру сервера, максимальное количество соединений с базой данных (Classic, SuperClassic), количество доступной оперативной памяти, а также некоторые другие настройки сервера.

В архитектуре Classic количество страниц может управляться отдельным подключением (то есть оно само может сказать, сколько ему сейчас нужно страниц). Размер страничного кеша может быть увеличен только после рестарта Firebird (для архитектуры SuperServer) или переподключения (для Classic).

В архитектуре SuperServer (предоставляющей для всех подключений общий страничный кеш) рекомендуется назначать страничный кеш как можно большим, но также есть рекомендация не делать его размер более, чем половина от физического размера ОЗУ. Для очень больших БД достаточно выделить такой размер кеша, чтобы в него помещалась активная часть БД. Достаточность кеша обычно проверяют соотношением read/fetch. Хорошим соотношением для FB является `read/fetch < 0.005`.

.Установка параметра `DefaultDbCachePages` в `firebird.conf`
[example]
====
[listing]
----
DefaultDbCachePages = 2048
----
====

.Установка параметра `DefaultDbCachePages` в `databases.conf` для базы данных testdb
[example]
====
[listing]
----
testdb = d:\fb\fb30\data\testdb.fdb
{
    DefaultDbCachePages = 8K
}
----
====

Кроме того, следует обращать внимание на значение параметра `FileSystemCacheThreshold`. Если размер страничного кеша превышает значение параметра `FileSystemCacheThreshold`, то системный файловый кеш будет отключен.

.Смотри также:
<<fbadmgd-config-param_filesystemcachethreshold,FileSystemCacheThreshold>>

[[fbadmgd-config-param_databasegrowthincrement]]
=== DatabaseGrowthIncrement
(((Параметр конфигурации,DatabaseGrowthIncrement)))

.Область действия:
Per-database.

.Тип параметра:
Integer.

Параметр позволяет указать объем дискового пространства, которое может быть предварительно выделено под базу данных. Дисковое пространство резервируется в системе, что позволяет в дальнейшем снизить физическую фрагментацию файла(-ов) базы данных и дает возможность продолжить работу в условиях недостатка места на диске. Если режим резервирования включен, то сервер резервирует 1/16 часть от уже используемого дискового пространства для одного соединения, но не меньше 128 KB и не больше, чем значение, заданное параметром `DatabaseGrowthIncrement` (по умолчанию 128 MB).

Для отключения резервирования дискового пространства необходимо выставить значение `DatabaseGrowthIncrement` равным 0.

.Установка параметра `DatabaseGrowthIncrement`
[example]
====
[listing]
----
DatabaseGrowthIncrement = 128M
----
====

[NOTE]
====
Пространство под теневые копии баз данных не резервируется.
====

[[fbadmgd-config-param_filesystemcachethreshold]]
=== FileSystemCacheThreshold

.Область действия:
Per-database.

.Тип параметра:
Integer.

Параметр `FileSystemCacheThreshold` устанавливает порог использования системного файлового кэша сервером Firebird. Системный файловый кэш используется, если размер страничного кэша (установленного явно в заголовке базы данных или через параметр конфигурации `DefaultDbCachePages`) меньше чем значение `FileSystemCacheThreshold`.

Параметр имеет целочисленный тип. Единица измерения -- страница базы данных. По умолчанию параметр имеет значение -- 65536 страниц. Максимально допустимое значение параметра -- 2147483647. Минимальное значение параметра -- 0.

Если значение параметра `FileSystemCacheThreshold` равно 0, то сервер не будет использовать системный файловый кэш.

.Установка параметра `FileSystemCacheThreshold`
[example]
====
[listing]
----
FileSystemCacheThreshold = 128K
----
====

[NOTE]
====
Системный файловый кэш имеет смысл отключать только при достаточно большом размере страничного кэша базы данных. Это позволяет избегать двойного кэширования и снизить потребление оперативной памяти. Это может быть полезным для баз, работающих в режиме read-only на архитектуре SuperServer. 

Для баз данных, работающих в режиме OLTP-нагрузки, отказ от кеширования файловой системой почти всегда приводит к крайне сильной просадке производительности. Одна из причин -- отсутствие в СУБД Firebird возможности упреждающего чтения и отложенной записи, которые есть в операционной системе. Для таких баз всегда должно соблюдаться правило: `DefaultDbCachePages` < `FileSystemCacheThreshold`.
====

.Смотри также:
<<fbadmgd-config-param_defaultdbcachepages,DefaultDbCachePages>>

[[fbadmgd-config-param_filesystemcachesize]]
=== FileSystemCacheSize
(((Параметр конфигурации,FileSystemCacheSize)))

.Область действия:
Per-server.

.Тип параметра:
Integer, измеряется в процентах от объёма доступной оперативной памяти.

Параметр `FileSystemCacheSize` устанавливает максимальный размер оперативной памяти, используемый системным файловым кешем 64-битными Windows XP или Windows Server 2003 с Service Pack 1 или выше. Этот параметр не оказывает никакого эффекта в Unix-подобных операционных системах.

Параметр содержит целое число, представляющее собой количество (в процентах) оперативной памяти, которое может быть использовано под файловый кеш. Значение может быть от 10 до 95%.

Значение считывается при старте сервера и не может быть изменено. Требуется перезагрузка операционной системы для вступления изменений в силу. 

Если задать значение 0, операционная система сама будет определять размер файлового кеша (обычно это 30%). Это и есть значение по умолчанию. 

.Установка параметра `FileSystemCacheSize`
[example]
====
[listing]
----
FileSystemCacheSize = 25
----
====

[NOTE]
====
Windows требует обладания привилегией SeIncreaseQuotaPrivilege для управления настройками файлового кеша. Эта привилегия доступна по умолчанию администраторам и службам, а также выдается учетной записи Firebird при установке из дистрибутива Windows Installer.

Если Firebird запущен как приложение или в режиме Embedded или установлен не из официального дистрибутива, учетная запись может не иметь данной привилегии. Процесс не выдаст ошибку при запуске, а просто запишет соответствующее сообщение в файл `firebird.log` и будет работать с настройками операционной системы.
====

[[fbadmgd-config-param_remotefileopenability]]
=== RemoteFileOpenAbility

.Область действия:
Per-server.

.Тип параметра:
Boolean.

Параметр `RemoteFileOpenAbility` отключает защиту от открытия баз данных на смонтированных томах NFS в Linux/Unix и SMB/CIFS в Windows.

[WARNING]
====
Эта опция удаляет важную функцию безопасности Firebird и может привести к неисправимому повреждению базы данных. Не используйте эту опцию, если вы не понимаете риски и не готовы принять потерю содержимого вашей базы данных.
====

Параметр имеет логический тип. По умолчанию его значение равно 0.

В этом случае Firebird может открыть базу данных, только если она хранится на диске, физически подключенном к локальному компьютеру, на котором установлена эта копия Firebird. Запросы на подключение к базам данных, хранящимся на смонтированных дисках NFS, перенаправляются на сервер Firebird, работающий на компьютере, который "`владеет`" диском.

.Установка параметра RemoteFileOpenAbility
[example]
====
[listing]
----
RemoteFileOpenAbility = 0
----
====

Это ограничение не позволяет двум разным копиям Firebird открывать одну и ту же базу данных без координации их действий. Несогласованный доступ нескольких копий Firebird приведет к повреждению базы данных. В локальной системе блокировка файлов на уровне системы предотвращает несогласованный доступ к файлу базы данных.

NFS не обеспечивает надежный способ обнаружения доступа нескольких пользователей к файлу на смонтированном диске NFS. Если вторая копия Firebird подключится к базе данных на смонтированном диске NFS, она повредит базу данных. В некоторых случаях запуск сервера Firebird на компьютере, который владеет томами, смонтированными в NFS, неудобен или невозможен. Приложения, которые используют embedded вариант Firebird и никогда не разделяющие доступ к базе данных, могут использовать эту опцию, чтобы разрешить прямой доступ к базам данных на смонтированных томах NFS.

Ситуация для SMB / CIFS очень похожа на NFS, поскольку не все конфигурации предоставляют механизмы блокировки файлов, необходимые для безопасной работы. Использование механизма SuperServer с базой данных на файловом сервере NT может считаться относительно безопасным, поскольку блокировка файлов защищает базу данных от использования несколькими механизмами. Сетевой стек по-прежнему может изменять порядок записи, поэтому вы можете получить поврежденную базу данных в случае сетевых ошибок или отключения питания. 

Относительно полезный и безопасный случай -- это работа с общей базой данных, помеченной только для чтения. 

[[fbadmgd-config-param_tempblocksize]]
=== TempBlockSize
(((Параметр конфигурации,TempBlockSize)))

.Область действия:
Per-server.

.Тип параметра:
Integer.

Параметр `TempBlockSize` используется для управления временным пространством. Временное хранилище используется большими сортировками, или для промежуточного хранения набора данных. Параметр `TempBlockSize` определяет размер блока, выделяемого для временного хранилища. Это значение отражает гранулярность выделения пространства.

Параметр имеет целочисленный тип. Единица измерения -- байты. По умолчанию параметр имеет значение 1 Мбайт. Максимально допустимое значение 2 Гбайт. Минимальное значение параметра -- 0.

.Установка параметра `TempBlockSize`
[example]
====
[listing]
----
TempBlockSize = 2M
----
====

Оптимальное значение этого параметра (хотя и трудно определяемое) -- средний размер памяти, отводимой на операцию сортировки.

Предельный размер всей области оперативной памяти, выделяемой для временных файлов, задается параметром `TempCacheLimit`. Блоки, которые ранее выделялись, хранится в нём как линейный список, поиск в котором выполняется методом половинного деления (бисекции). Если `TempCacheLimit` задан слишком большого размера, например, 16 Гб, то даже при его заполненности на 50% (т.е. 8Гб) для поиска блока размером 1 Мб потребуется 13 шагов. В этом случае лучше увеличить размер `TempBlockSize` до 3-4М, что приведет к уменьшению числа шагов бисекции до 6-8. В то же время, рекомендуется ставить `TempBlockSize` в значение, не превышающее 5% от `TempCacheLimit`, а также оно должно быть не меньше 1 Мб.

.Смотри также:
<<fbadmgd-config-param_tempcachelimit,TempCacheLimit>>

[[fbadmgd-config-param_tempcachelimit]]
=== TempCacheLimit

.Область действия:
Per-server.

.Тип параметра:
Int64.

Параметр `TempCacheLimit` определяет максимальный объём оперативной памяти, который используется для кэширования временного пространства.

Параметр имеет целочисленный тип. Единица измерения -- байты. Минимальное значение равно 0, максимальное -- (2^64^ - 1) байт. Значение по умолчанию для классического сервера равно 8 Мбайт, для архитектур SuperClassic и SuperServer -- 64 Мбайт.

[IMPORTANT]
====
Для классического сервера это ограничение распространяется для каждого соединения с базой данных, для SuperServer и SuperClassic -- для каждого запущенного экземпляра сервера Firebird.
====

.Установка параметра `TempCacheLimit`
[example]
====
[source]
----
TempCacheLimit = 256M
----
====

[NOTE]
====
* Firebird 3.0 и выше позволяет указывать значения этого параметра больше, чем 4 Гб.
* Когда какому-то соединению память перестает быть нужной, она возвращается операционной системе. Другими словами, задание `TempCacheLimit = 4096M` не означает, что 4 Гб памяти будут сразу и безвозвратно зарезервированы процессом Firebird.
* Увеличение `TempCacheLimit` даёт лучший эффект чем назначение для временных файлов каталога на tmpfs (см. параметр `TempDirectories`), так как при этом не возникает дополнительных расходов на обмен данными с ядром операционной системы.
* Значение `TempCacheLimit` гарантирует, что данные этого размера будут находиться в оперативной памяти. Когда память, отведенная для временного хранения данных, будет исчерпана, очередной запрос от Firebird на получение блока размером `TempBlockSize` байт приведет к тому, что новая память может быть уже выделена на диске в swap-области.
* В Firebird 3.0 в области `TempCacheLimit` размещаются данные при выполнении hash-соединений.

====

[WARNING]
====
Будьте осторожны с назначением этого параметра при работе СУБД в режиме Classic Server. Общий лимит памяти, которую Firebird будет запрашивать у операционной системы для временных файлов, определяется при этом как результат умножения `TempCacheLimit` на количество подключений.
====

.Смотри также:
<<fbadmgd-config-param_tempblocksize,TempBlockSize>>

[[fbadmgd-config-param_auth]]
=== AuthServer и AuthClient
(((Параметр конфигурации,AuthServer)))

.Область действия:
Per-database.

.Тип параметра:
String.

Параметр `AuthServer` -- набор методов аутентификации, разрешенных на сервере (определяется в файле конфигурации сервера).

Параметр `AuthClient` -- набор методов аутентификации, поддерживаемых клиентом (определяется в файле конфигурации на клиенте).

Включенные методы перечислены в виде строковых символов, разделенных запятыми, точками с запятой или пробелами. Если проверить подлинность с помощью первого метода не удалось, то сервер переходит к следующему и т.д. Если ни один метод не подтвердил подлинность, то пользователь получает сообщение об ошибке.

Firebird поддерживает следующие методы аутентификации:

* Безопасная парольная аутентификация (Srp). Протокол SRP (Secure Remote Password) позволяет пользователю, не передавая своего пароля, подтвердить серверу тот факт, что он знает свой пароль;
* Традиционная (Legacy_Auth) аутентификация, использовалась в качестве основного метода аутентификации в Firebird версии 2.5 и ниже;
* Доверительная (Win_Sspi) аутентификация для ОС Windows.

По умолчанию на стороне сервера используется метод Secure remote passwords (Srp256), представленный соответствующей ОС плагином (_libSrp.so_ | _Srp.dll_ | _Srp.dylib_).

[listing]
----
AuthServer = Srp256
----

[NOTE]
====
Первоначально Firebird 3.0 использовал по умолчанию плагин Srp, который использовал SHA-1 для генерации ключа шифрования, начиная с Firebird 3.0.4 введён усовершенствованный метод аутентификации Srp256, который использует SHA-256.
====

Список AuthServer по умолчанию содержит только один элемент (Srp). Это значит, что к такому серверу возможно подключение только тех приложений, которые используют клиента версии 3 и старше. Если ваш сервер должен принимать подключения от клиентов версий до 2.5 включительно, необходимо добавить в этот список элемент `Legacy_Auth`.

[NOTE]
====
Традиционная (`Legacy_Auth`) не умеет работать с новым менеджером пользователей `Srp`. Поэтому если вы хотите соединяться с Firebird 3.0 клиентами fbclient версией 2.5 и ниже, то необходимо также включить в список плагинов управления пользователями (параметр UserManager) плагин `Legacy_UserManager`.
====

Если вы хотите использовать плагины аутентификации, которые не предоставляют ключа шифрования (`Win_Sspi`, `Legacy_Auth`), то следует отключить обязательное (`Required`) шифрование каналов передачи данных (параметр `WireCrypt`), кроме случаев, когда вы работаете с протоколом XNET, который никогда не использует шифрование.

На клиентской стороне по умолчанию используется следующий список методов аутентификации:

[listing]
----
AuthClient = Srp256, Srp, Win_Sspi, Legacy_Auth  # для Windows клиентов     
AuthClient = Srp256, Srp, Legacy_Auth            # для не Windows клиентов
----

Под клиентом следует понимать как обычное подключение от пользователя, так и запрос от сервера-1, к которому ранее уже было подключение, к серверу-2, через механизм external datasource. В этом случае клиентом выступает сервер-1.

Плагин `Legacy_Auth` присутствует в списке `AuthClient` по умолчанию для того, чтобы клиенты версии 3.0 и выше могли подключаться к серверам более старых версий. 

Чтобы отключить какой-нибудь из методов, раскомментируйте строку и удалите нежелательный метод из списка.

[TIP]
====
Поскольку плагины аутентификации пробуются в порядке их перечисления, то для наилучшей производительности переместите наиболее часто используемый метод аутентификации на первое место.
====

Оба параметра могут быть использованы в `databases.conf`. Они могут использоваться как в DPB, так и в SPB для конкретных настроек соединения.

.Смотри также:
<<fbadmgd-config-param_usermanager,UserManager>>, <<fbadmgd-config-param_wirecrypt,WireCrypt>>.

[[fbadmgd-config-param_usermanager]]
=== UserManager
(((Параметр конфигурации,UserManager)))

.Область действия:
Per-database.

.Тип параметра:
String.

Устанавливает плагин, который будет работать в базе данных безопасности. Это может быть список с пробелами, запятыми или точками с запятой в качестве разделителей. По-умолчанию используется первый подключаемый плагин из списка.

Firebird поддерживает следующие плагины управления пользователями: 

* Srp;
* Legacy_UserManager.

Для поддержки старой базы данных безопасности и управления пользователями в ней, следует установить значение параметра `Legacy_UserManager`.

.Установка параметра UserManager
[example]

[source]
----

UserManager = Srp
----

В SQL операторах управления пользователями можно явно указать какой плагин будет использоваться с помощью ключевого слова `USING`.

[NOTE]
====
Одноименные пользователи, созданные с помощью разных плагинов управления пользователями -- это разные пользователи.
====

Параметр `UserManager` можно использовать в `database.conf` для переопределения в конкретной базе данных.

[[fbadmgd-config-param_traceplugin]]
=== TracePlugin

.Область действия:
Per-server.

.Тип параметра:
String.

Задает плагин, используемый функцией трассировки Firebird для отправки данных трассировки в приложение клиента или данных аудита в лог файл.

.Установка параметра TracePlugin
[example]

[source]
----

TracePlugin = fbtrace
----

[[fbadmgd-config-param_wirecryptplugin]]
=== WireCryptPlugin
(((Параметр конфигурации,WireCryptPlugin)))

.Область действия:
Per-connection.

.Тип параметра:
String.

Плагин поточного шифра используется для шифрования и дешифрования данных, передаваемых по сети. 

По-умолчанию устанавливается значение параметра Arc4, что означает использование плагина потокового шифра Alleged RC4.
Сконфигурированный плагин, который требует ключ, сгенерированный настроенным подключаемым модулем аутентификации, может быть переопределен в API для конкретного соединения через DPB или SPB.

.Установка параметра WireCryptPlugin
[example]

[source]
----

WireCryptPlugin = Arc4
----

.Смотри также:
<<fbadmgd-config-param_wirecrypt,WireCrypt>>.

[[fbadmgd-config-param_keyholderplugin]]
=== KeyHolderPlugin

.Область действия:
Per-server.

.Тип параметра:
String.

Этот параметр представляет собой некоторую форму временного хранилища для ключей шифрования базы данных.

Реализованного плагина по-умолчанию нет, но пример для Linux под названием `libCryptKeyHolder_example.so` можно найти в папке `/plugins/`.

[[fbadmgd-config-param_allowencryptedsecuritydatabase]]
=== AllowEncryptedSecurityDatabase
(((Параметр конфигурации,AllowEncryptedSecurityDatabase)))

.Область действия:
Per-database.

.Тип параметра:
Boolean.

Задает возможность использования зашифрованной базы данных с учетными записями пользователей и паролями.

Передача по зашифрованному сетевому каналу с ключем шифрования, который создается плагином аутентификации (Srp) для передачи далее по сети ключа шифрования БД, может рассматриваться как замкнутый круг. Чтобы послать ключ шифрования БД по сети безопасным способом, передаваемые части ключа уже должны быть зашифрованными. Но это требует наличия ключа шифрования от плагина аутентификации, которому нужно открыть базу безопасности для валидации хеша от пароля, а это, в свою очередь, требует ключа шифрования БД.

К счастью, в большинстве случаев нет необходимости шифровать базу данных безопасности -- она достаточно хорошо защищает себя, если вы используете пароли надлежащего качества. Но в некоторых случаях желательно иметь зашифрованную базу безопасности, например, если нужно, чтобы зашифрованная база с пользовательскими данными, также служила базой безопасности. В этом случае особое внимание следует уделить шифрованию ключа перед передачей его на сервер с помощью обратного вызова.

Убедитесь, что ваши ключи хорошо зашифрованы перед тем, как разрешать шифрование базы безопасности. Примите по внимание, что при `AllowEncryptedSecurityDatabase=True` возможна передача ключа, который не зашифрован протоколом Firebird, даже при не зашифрованной базе безопасности.

Указанное свойство не поддерживается унаследованным (Legacy) плагином проверки пользователей. Если вам нужна безопасность, пожалуйста, никогда не используйте унаследованную аутентификацию.

[WARNING]
====
Убедитесь в том, что понимаете свои действия, прежде чем менять этот параметр на True.
====

[[fbadmgd-config-param_providers]]
=== Providers

.Область действия:
Per-database и per-connection.

.Тип параметра:
String.

Провайдеры -- это практически то, что мы подразумеваем под способами, используемыми для соединения клиента с сервером, т.е. через интернет; на том же компьютере через 'localhost'; или через прямое соединение в локальной сети (старый `libfbembed.so` для POSIX сейчас реализован как библиотека `libEngine12.so`; для Windows -- `engine12.dll`; для MacOSX -- `engine12.dylib`).

В `firebird.conf` доступны по-умолчанию следующие провайдеры:

[listing]
----
Providers = Remote,Engine12,Loopback
----

В `databases.conf` один или несколько провайдеров могут быть заблокированы, если вставить и раскомментировать строку из `firebird.conf` и удалить нежелательные провайдеры.

Архитектура провайдеров (известная как Open Systems Relational Interface, OSRI) очень эффективна для поддержки сочетания старых и новых форматов базы данных (с разными ODS) на одном сервере, имеющих смешанные подключения к локальным и удаленным базам данных.

Провайдеры реализованные в Firebird, позволяют поддерживать все эти режимы (удаленные соединения, базы данных с разными ODS), а также цепочки провайдеров. Цепочка -- это термин для ситуации, когда провайдер использует обратный вызов стандартного API для выполнения операции над базой данных.

Главным элементом архитектуры провайдеров является **y-valve**. На начальном этапе соединения с базой данных или её создания *y-valve* просматривает список известных провайдеров и вызывает их по одному, пока один из них не завершит запрошенную операцию успешно. Для соединения, которое уже установлено, соответствующий провайдер вызывается сразу с почти нулевыми накладными расходами.

Рассмотрим пример работы **y-valve**, когда он выбирает подходящего провайдера при подключении к базе данных. Конфигурация по-умолчанию содержит три провайдера:

* *Remote* (используется для сетевого соединения);
* *Engine12* (ядро для работы с ODS 12);
* *Loopback* (принудительное соединение с локальным сервером, когда задано только имя базы данных без явного указания протокола).

Типичная конфигурация клиента работает таким образом: при подключении к базе данных с именем `RemoteHost:dbname` (синтаксис TCP/IP) или `\\RemoteHost\dbname` (Named pipes) или в URI-подобном синтаксисе с протоколами inet и wnet, провайдер Remote обнаруживает явный синтаксис сетевого протокола и перенаправляет вызов RemoteHost.

Когда `<database name>` не содержит сетевого протокола, а только имя базы данных, провайдер `Remote` отклоняет его, а провайдер `Engine12` выходит на первый план и пытается открыть файл с именованной базой данных. Если это проходит успешно, создается подключение к базе данных.

Но что происходит, если СУБД возвращает ошибку при попытке подключения к базе данных? 

* Если файл базы данных, к которому нужно подключиться, не существует, то это не интересно всем.
* Встроенное соединение может не работать, если пользователь, подключившийся к нему, не имеет достаточных прав для открытия файла базы данных. Это было бы обычной ситуацией, если бы база данных не была создана этим пользователем во встроенном режиме или если ему явно не были предоставлены права ОС на встроенный доступ к базам данных.
+

[NOTE]
====
Это также может происходить, если выбран режим SuperServer и уже существует соединение с базой данных, поскольку SuperServer требует эксклюзивного доступа к файлу базы данных.
====
* После отказа провайдера Engine12 в получении доступа к базе данных, пытается подключиться провайдер Loopback. Он не очень отличается от Remote, за исключением того, что он пытается получить доступ к именованной базе данных `<dbname>` на сервере c сетевым интерфейсом "`внутренней петли`" (loopback) в сетевом протоколе TCP/IP.
+
В Windows XNET пробуется первым, затем TCP/IP loopback (`localhost:<dbname>`), затем Named Pipes (NetBEUI) loopback.
Сервер может быть запущен с отключенным XNET (или любым другим протоколом), поэтому перебираются все варианты.
В POSIX поддерживается только TCP/IP протокол, остальные варианты не доступны.


[NOTE]
====
Если вы хотите добиться поведения, аналогичного Firebird 2.5 и ниже, когда при наличии запущенного сервера и указании в строке соединения только алиаса базы данных или пути до неё, устанавливалось соединение по локальному проколу, то необходимо поменять провайдеры `Engine12` и `Loopback` местами.

Для подключения по локальному протоколу рекомендуем использовать URI-подобную строку подключения с явным указанием префикса протокола `xnet://`.
====

Провайдеры не ограничены тремя вышеперечисленными. Версия 3.0 не поддерживает pre- ODS 12 провайдер. Тем не менее, архитектура провайдеров делает возможным доступ к старым базам данных при переходе на более высокую версию Firebird.

[NOTE]
====
Firebird 4.0 для работы с ODS 13 реализован провайдер Engine13, тем не менее вы можете работать с базой данных ODS 12, через провайдер Engine12 из Firebird 3.0.
====

[[fbadmgd-config-param_deadlocktimeout]]
=== DeadlockTimeout
(((Параметр конфигурации,DeadlockTimeout)))

.Область действия:
Per-database.

.Тип параметра:
Integer.

Параметр `DeadlockTimeout` определяет количество секунд, в течение которых диспетчер блокировок будет ожидать после возникновения конфликта, прежде чем очистить блокировки от мертвых процессов и выполнить дополнительный цикл сканирования взаимоблокировок. Firebird обнаруживает взаимные блокировки мгновенно во всех обычных случаях, поэтому это значение влияет на ситуации, когда что-то идет не так. 

Параметр имеет целочисленный тип. Единица измерения -- секунды. Значение по умолчанию равно 10 секунд.
Минимально допустимое значение параметра равно 0. Максимально допустимое значение равно 2147483647.

.Установка параметра DeadlockTimeout
[example]

[source]
----

DeadlockTimeout = 10
----

[WARNING]
====
Слишком низкое значение может снизить производительность системы.
====

[[fbadmgd-config-param_maxunflushedwrites]]
=== MaxUnflushedWrites

.Область действия:
Per-database.

.Тип параметра:
Integer.

Параметр `MaxUnflushedWrites` определяет, как часто страницы из кэш памяти будут выгружаться на жесткий диск (активен только при значении параметра ForcedWrites=Off).

Значение параметра `MaxUnflushedWrites` определяет максимальное количество накопленных страниц не сброшенных на диск, ожидающих сброса при подтверждения транзакции.

Параметр имеет целочисленный тип и измеряется в страницах. Значение по умолчанию равно 100 страниц. Для не Win32 систем значение по умолчанию является -1(Отключено). Максимально допустимое значение равно 2147483647.

.Установка параметра MaxUnflushedWrites
[example]

[source]
----

MaxUnflushedWrites = 100
----

[WARNING]
====
Чем больше значение параметра, тем выше вероятность потери данных при возникновении аппаратного сбоя в системе.
====

.Смотри также:
<<fbadmgd-config-param_maxunflushedwritetime,MaxUnflushedWriteTime>>

[[fbadmgd-config-param_maxunflushedwritetime]]
=== MaxUnflushedWriteTime
(((Параметр конфигурации,MaxUnflushedWriteTime)))

.Область действия:
Per-database.

.Тип параметра:
Integer.

Параметр `MaxUnflushedWriteTime` определяет, как часто страницы из кэш памяти будут выгружаться на жесткий диск (активен только при значении параметра ForcedWrites=Off).

Значение параметра `MaxUnflushedWriteTime` определяет время, по истечении которого страницы данных, ожидающие сброса на диск при подтверждении транзакции, будут выгружены на диск.

Параметр имеет целочисленный тип и измеряется в секундах. Значение по умолчанию равно 5 секунд. Для не Win32 систем значение по умолчанию является -1(Отключено). Максимально допустимое значение равно 2147483647.

.Установка параметра MaxUnflushedWriteTime
[example]

[source]
----

MaxUnflushedWriteTime = 5
----

[WARNING]
====
Чем больше значение параметра, тем выше вероятность потери данных при возникновении аппаратного сбоя в системе.
====

.Смотри также:
<<fbadmgd-config-param_maxunflushedwrites,MaxUnflushedWrites>>

[[fbadmgd-config-param_bugcheckabort]]
=== BugcheckAbort

.Область действия:
Per-server.

.Тип параметра:
Boolean.

Опция `BugcheckAbort` определяет, прерывать ли работу сервера при возникновении внутренней ошибки или снимать дамп ядра для последующего анализа. Если опция отключена, то ядро пытается минимизировать ущерб и продолжить работу.

Параметр имеет логический тип. Возможные значения 0 и 1. Значение по умолчанию равно 0, в этом случае механизм снятия дампов отключен. Для отладочных сборок (DEV_BUILD) значение по умолчанию равно 1.

.Установка параметра BugcheckAbort
[example]

[source]
----

BugcheckAbort = 0
----

[NOTE]
====
Обратите внимание, что установка этой опции в 1 заставляет движок производить трассируемые дампы, когда внутри UDF происходит что-то неприятное, например SIGSEGV. В Windows включение этой опции заставляет ядро вызывать средства отладки JIT при возникновении ошибок.

В POSIX при `BugCheckBort = 1` сервер Firebird будет устанавливать soft-лимит для размера файлов равным hard-лимиту, и делать запись в каталог, доступный для записи, как правило это `/tmp`.
====

[[fbadmgd-config-param_relaxedaliaschecking]]
=== RelaxedAliasChecking
(((Параметр конфигурации,RelaxedAliasChecking)))

.Область действия:
Per-server.

.Тип параметра:
Boolean.

Параметр `RelaxedAliasChecking` позволяет снять ограничение на обязательное использование псевдонимов имен таблиц в запросах. Если опция включена, то Firebird позволяет выполнять подобные запросы:

[source,sql]
----
SELECT MY_TABLE.X FROM MY_TABLE A
----

Параметр имеет логический тип. Значение по умолчанию равно 0. Если значение параметра равно 1, то ограничение на обязательное использование псевдонимов таблиц в запросах снимается.

.Установка параметра RelaxedAliasChecking
[example]

[source]
----

RelaxedAliasChecking = 0
----

Не рекомендуется включать этот параметр. Его следует рассматривать как временный обходной путь для портирования неаккуратного устаревшего кода до тех пор, пока не удастся пересмотреть такой код.

[CAUTION]
====
Нет никаких гарантий что данная установка будет доступна в следующих версиях Firebird.
====

.Установка параметра RelaxedAliasChecking
[example]

[source]
----

RelaxedAliasChecking = 0
----

[[fbadmgd-config-param_connectiontimeout]]
=== ConnectionTimeout

.Область действия:
Per-connection.

.Тип параметра:
Integer.

С помощью параметра `ConnectionTimeout` устанавливается ограничение на время ожидания соединения. После того как порог, установленный значением параметра, будет превышен, попытка соединения будет признана неудачной.

Параметр `ConnectionTimeout` имеет целочисленный тип и измеряется в секундах. Значение по умолчанию равно 180 секунд.
Минимальное значение равно 0. Максимально допустимое значение равно 2147483647.

.Установка параметра ConnectionTimeout
[example]

[source]
----

ConnectionTimeout = 180
----

[[fbadmgd-config-param_wirecrypt]]
=== WireCrypt
(((Параметр конфигурации,WireCrypt)))

.Область действия:
Per-connection.

.Тип параметра:
String (предопределённые значения).

Параметр устанавливает, следует ли шифровать сетевое соединение. Он может принимать три возможных значения: `Required`, `Enabled`, `Disabled`. По-умолчанию установлено, что шифрование является обязательным (`Required`) для подключений, поступающих на сервер и включенным (`Enabled`) для подключений, исходящих с клиента.

.Установка параметра WireCrypt
[example]

[source]
----

WireCrypt = Enabled # для клиента
----
[source]
----

WireCrypt = Required # для сервера
----

Чтобы получить доступ к серверу с использованием традиционной (`Legacy_Auth`) аутентификации, параметр `WireCrypt` в файле конфигурации сервера должен быть включен (`Enabled`) или выключен (`Disabled`).

Правила очень просты: если на одной стороне стоит значение `WireCrypt = Required`, а на другой установлено значение `Disabled`, то первая сторона отклоняет соединение и оно не устанавливается. Если на одной стороне стоит значение `WireCrypt = Enabled`, то на другой шифрования может и не быть вовсе.

Отсутствующий подключаемый модуль `WireCryptPlugin` или ключ шифрования в случаях, когда канал должен быть зашифрован, также препятствует соединению.

Во всех остальных случаях соединение устанавливается без шифрования, если хотя бы одна сторона имеет `WireCrypt = Disabled`. В других случаях устанавливается шифрованное соединение. 

.Совместимость параметров WireCrypt на клиенте и на сервере
[cols="1,1,1,1", frame="all"]
|===
|
|Disabled
|Enabled
|Required

|Disabled
|Шифрование отключено
|Шифрование отключено
|Ошибка соединения

|Enabled
|Шифрование отключено
|Шифрование включено, если плагин аутентификации предоставляет ключ шифрования. Иначе шифрования нет.
|Шифрование включено, если плагин аутентификации предоставляет ключ шифрования. Иначе ошибка подключения.

|Required
|Ошибка соединения
|Шифрование включено, если плагин аутентификации предоставляет ключ шифрования. Иначе ошибка подключения.
|Шифрование включено, если плагин аутентификации предоставляет ключ шифрования. Иначе ошибка подключения.
|===

.Смотри также:
<<fbadmgd-config-param_auth,AuthServer и AuthClient>>, <<fbadmgd-config-param_wirecryptplugin,WireCryptPlugin>>.

[[fbadmgd-config-param_wirecompression]]
=== WireCompression

.Область действия:
Per-connection.

.Тип параметра:
Boolean.

Параметр может быть задействован и в `firebird.conf` и в `databases.conf`; он включает или отключает сжатие данных, передающихся по сети.

По-умолчанию сжатие отключено.

.Установка параметра WireCompression
[example]

[source]
----

WireCompression = false
----

Для правильной работы параметра требуется корректная настройка как на сервере, так и на клиенте:

* Чтобы включить `WireCompression` на стороне сервера, поставьте параметр в значение `true` в файле `firebird.conf` или `database.conf`.
* Для того чтобы активировать `WireCompression` на стороне клиента, передайте соответствующий тег в вызов DPB и SPB:
+
[source]
----

isc_dbp_config <string-length> "WireCompression=true"
isc_sbp_config <string-length> "WireCompression=true"
----
* Клиент и сервер должны использовать протокол >= 13 (Firebird 3.0 и старше).


[[fbadmgd-config-param_dummypacketinterval]]
=== DummyPacketInterval
(((Параметр конфигурации,DummyPacketInterval)))

.Область действия:
Per-connection.

.Тип параметра:
Integer.

Параметр `DummyPacketInterval` используется для того, чтобы установить число секунд ожидания в "`тихом`" режиме, прежде чем сервер начнет посылать пустые пакеты для подтверждения соединения.

Параметр имеет целочисленный тип и измеряется в секундах. Значение по умолчанию равно 0 секунд. Максимально допустимое значение равно 2147483647 секунд. 

[WARNING]
====
Эта опция может привести к зависанию или сбоям Windows NT4 или Windows 2000 pre SP3 на стороне клиента, как описано в https://support.microsoft.com/ru-ru/help/296265/windows-2000-non-paged-pool-is-exhausted-by-afd-sys[296265], или не может предотвратить возможное отключение неактивного клиента для других ОС.
====

Обычно Firebird использует опцию сокета SO_KEEPALIVE, чтобы следить за активными подключениями по TCP/IP протоколу. Если вас не устраивает заданное по умолчанию 2-часовое время ожидания (keepalive), то следует изменить параметры настройки своей операционной системы соответственно:

* в Unix-подобных ОС необходимо изменить содержимое `/proc/sys/net/ipv4/tcp_keepalive_*`;
* в Windows необходимо вносить изменения в ветку реестра `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\` ключи (`KeepAliveTime`, `KeepAliveInterval`, `TcpMaxDataRetransmissions`).


[[fbadmgd-config-param_remoteserviceport]]
=== RemoteServicePort или RemoteServiceName
(((Параметр конфигурации,RemoteServiceName)))

.Область действия:
Per-connection.

.Тип параметра:
Integer или String.

Параметры `RemoteServiceName` и `RemoteServicePort` используются для установки номера порта или имени сервиса, которые будут использоваться для клиентских соединений с базами данных.

Параметр `RemoteServiceName` имеет строковый тип. Значение по умолчанию равно `gds_db`.

Параметр `RemoteServicePort` имеет целочисленный тип. Значение по умолчанию равно `3050`.

.Установка параметра RemoteServiceName
[example]

[source]
----

RemoteServiceName = gds_db
----

.Установка параметра RemoteServicePort
[example]

[source]
----

RemoteServicePort = 3050
----

[IMPORTANT]
====
Изменять следует только один из этих параметров, не оба сразу. Сервер ищет номер порта для клиентских соединений в следующем порядке -- сначала `RemoteServiceName` (соответствующая значению параметра запись ищется в файле `services`), затем `RemoteServicePort`.
====

[NOTE]
====
Обычно один из этих параметров (чаще всего `RemoteServicePort`) меняют только на стороне севера в `firebird.conf`, поскольку на клиентской стороне имя сервиса или номер порта можно указать в строке подключения.
====

[[fbadmgd-config-param_remoteauxport]]
=== RemoteAuxPort

.Область действия:
Per-connection.

.Тип параметра:
Integer.

Параметр `RemoteAuxPort` определяет номер TCP-порта, который будет использоваться для передачи уведомлений о событиях сервера.

Параметр `RemoteAuxPort` имеет целочисленный тип. Значение по умолчанию равно 0. В этом случае номер порта будет выбираться случайно.

.Установка параметра RemoteAuxPort
[example]

[source]
----

RemoteAuxPort = 0
----

[[fbadmgd-config-param_tcpremotebuffersize]]
=== TcpRemoteBufferSize
(((Параметр конфигурации,TcpRemoteBufferSize)))

.Область действия:
Per-connection.

.Тип параметра:
Integer.

Параметр `TcpRemoteBufferSize` определяет размер TCP/IP буфера для обмена сообщениями между сервером и клиентом. Firebird может делать упреждающее чтение клиентом и может отправлять несколько строк за один сетевой пакет. Чем больше размер пакета, тем больше данных будет передаваться за одну передачу.

Параметр имеет целочисленный тип и измеряется в байтах. Значение по умолчанию равно 8192. Минимально допустимое значение равно 1448. Максимальное значение равно 32767.

.Установка параметра TcpRemoteBufferSize
[example]

[source]
----

TcpRemoteBufferSize = 8192
----

[[fbadmgd-config-param_tcpnonagle]]
=== TcpNoNagle

.Область действия:
Per-connection.

.Тип параметра:
Boolean.

Параметр `TcpNoNagle` включает или отключает использование Nagle алгоритма (опция TCP_NODELAY для сокета) в TCP/IP соединениях.

В Linux по умолчанию библиотека сокетов минимизирует количество физических записей путем буферизации записей перед фактической передачей данных. Для этого используется встроенный алгоритм, известный как Nagle's Algorithm. Он был разработан, для того, чтобы избежать проблем с маленькими пакетами в медленных сетях.

Параметр имеет логический тип. По умолчанию значение параметра равно 1 (истина). В этом случае буферизация не используется. На медленных сетях в Linux это позволяет увеличить скорость передачи.

.Установка параметра TcpNoNagle
[example]

[source]
----

TcpNoNagle = 1
----

[[fbadmgd-config-param_tcploopbackfastpath]]
=== TcpLoopbackFastPath
(((Параметр конфигурации,TcpLoopbackFastPath)))

.Тип параметра:
Boolean.

Параметр `TcpLoopbackFastPath` включает или отключает использование функции "`TCP Loopback Fast Path`" (SIO_LOOPBACK_FAST_PATH).

Применим только в Windows (версия 8/2012 и выше). Параметр доступен начиная с Firebird 3.0.5.

Параметр имеет логический тип. По умолчанию значение параметра равно 1 (истина).

.Установка параметра TcpLoopbackFastPath
[example]

[source]
----

TcpLoopbackFastPath = 1
----

[[fbadmgd-config-param_ipv6v6only]]
=== IPv6V6Only

.Область действия:
Per-server.

.Тип параметра:
Boolean.

Этот параметр можно устанавливать только в `firebird.conf`. Firebird поддерживает *IPv6* подключение на стороне сервера и клиента. Параметр может принимать значения `true`/`false`, `1`/`0` или `Yes`/`No`. Значение по умолчанию равно `false`.

[NOTE]
====
В Windows эта опция поддерживается, начиная с Windows Vista, в более ранних версиях значение параметра всегда равно `true`.
====

.Установка параметра IPv6V6Only
[example]

[source]
----

IPv6V6Only = 0
----

==== Сервер

По-умолчанию, сервер прослушивает пустой *IPv6* адрес (`::`) и принимает все входящие подключения, будь то *IPv4* или *IPv6* (`IPv6V6Only = false`). Если параметр установлен в `true`, сервер, прослушивая явно или неявно пустой IPv6 адрес, принимает только IPv6 подключения.

==== Клиент

Адреса *IPv6* отображаются как восемь четырёхзначных шестнадцатеричных чисел (то есть групп по четыре символа), разделённых двоеточием. В строке подключения необходимо заключать *IPv6* адрес в квадратные скобки, чтобы разрешить неоднозначность с использованием двоеточия в качестве разделителя между IP адресом хоста и путем к базе данных.

К примеру: 
[source]
----
connect '[2014:1234::5]:test';
connect '[2014:1234::5]/3049:/srv/firebird/test.fdb';
----

[[fbadmgd-config-param_remotebindaddress]]
=== RemoteBindAddress
(((Параметр конфигурации,RemoteBindAddress)))

.Область действия:
Per-server.

.Тип параметра:
String.

Параметр `RemoteBindAddress` позволяет привязать входящие соединения к IP адресу определенной сетевой карты. При этом все входящие соединения через другие сетевые интерфейсы будут запрещены. По умолчанию подключения из любого доступного сетевого интерфейса разрешены. Если вы используете классический сервер, этот параметр предназначен только для Windows. В Linux, BSD или Mac OS X с сервером Classic используйте конфигурационный файл xinetd или launchd (параметр `bind`).

Параметр имеет строковый тип. По умолчанию его значение равно пустой строке (разрешены соединения с любого IP адреса).

.Установка параметра RemoteBindAddress
[example]

[source]
----

RemoteBindAddress =
----

[[fbadmgd-config-param_lockmemsize]]
=== LockMemSize

.Область действия:
Per-database.

.Тип параметра:
Integer.

Значение параметра `LockMemSize` определяет объем памяти, которая будет выделена менеджеру блокировок. В архитектуре Classic и SuperClassic данный параметр используется для начального распределения, далее таблица расширяется динамически до предела памяти. В архитектуре Super значение параметра определяет начальное распределение и предел выделяемой памяти.

Параметр имеет целочисленный тип. Единица измерения -- байты. Значение по умолчанию равно 1 Мбайт.
Минимальное значение равно 0. максимальное -- 2 Гбайта.

.Установка параметра LockMemSize
[example]

[source]
----

LockMemSize = 1M
----

На размер таблицы блокировок влияют: 

. В архитектурах Classic и SuperClassic размер страничного кэша (Super сервер для блокировки страниц использует легковесные защёлки). Страница, помещенная в кэш, блокируется, как минимум, один раз, страницы, которые читаются несколькими клиентами, могут блокироваться несколько раз.
. Число одновременных транзакций. Каждая транзакция имеет блокировку. Блокировка используется для синхронизации транзакций.
. События. Механизм оповещения о событиях использует блокировки. Число событий и число клиентов, ожидающих эти события, влияют на размер таблицы блокировок.


[[fbadmgd-config-param_lockacquirespins]]
=== LockAcquireSpins
(((Параметр конфигурации,LockAcquireSpins)))

.Область действия:
Per-database.

.Тип параметра:
Integer.

В архитектуре сервера Classic только одно клиентское соединение может обратиться к таблице блокировки в одно и то же время. Доступ к таблице блокировки управляется с помощью mutex(а). Mutex может быть затребован в условном, либо безусловном режиме. Если mutex затребован в условном режиме, то ожидание является отказом, и запрос должен повториться. В безусловном режиме mutex будет ожидаться до тех пор, пока не будет получен.

Параметр `LockAcquireSpins` имеет целочисленный тип. Его значение устанавливает количество попыток, которые будут сделаны в условном режиме. По умолчанию значение параметра равно 0, в этом случае будет использоваться безусловный режим.

[NOTE]
====
Параметр имеет эффект только на SMP (симметричных мультипроцессорных) системах. 
====

.Установка параметра LockAcquireSpins
[example]
====
[source]
----
LockAcquireSpins = 2
----
====

[NOTE]
====
В заголовке лок-таблицы этот параметр отображается как "`Spin count`" в строке вида:

----
Acquires:   2150, Acquire blocks:     14, Spin count:   0
----
====

[[fbadmgd-config-param_lockhashslots]]
=== LockHashSlots

.Область действия:
Per-database.

.Тип параметра:
Integer.

Параметр `LockHashSlots` используется для настройки числа слотов хэш таблицы блокировок. Чем больше слотов используется, тем короче получаются хэш цепочки, что увеличивает производительность при повышенной нагрузке.

Параметр имеет целочисленный тип. Максимально допустимое значение этого параметра равно 65521 (значения больше этого порога игнорируются и используется всё равно именно этот порог: 65521). 

Значение по умолчанию (8191) можно считать подходящим для работы 100 пользователей и умалчиваемом размере страничного кеша (256).

В качестве значения рекомендуется указывать простое число, чтобы хэш-алгоритм производил хорошее распределение. 

.Установка параметра LockHashSlots
[example]
====
[source]
----
LockHashSlots = 30011
----
====

Увеличение значения данного параметра необходимо только при высокой загрузке (одновременно с ним следует увеличить и параметр `LockMemSize` на тот же процент). Он вычисляется с использованием утилиты Lock Print по следующему принципу.

Запускаем утилиту 

[source]
----
fb_lock_print -d <database> | <alias>
----

В группе заголовка блока (**LOCK_HEADER BLOCK**), которая описывает основную конфигурацию и состояние таблицы блокировок, смотрим значение элемента *Hash lengths* (длина хэш цепочки). Этот элемент сообщает минимальную, среднюю и максимальную длину цепочки слотов. Чем длиннее будут цепочки, тем медленнее будет работать менеджер блокировок. Если среднее значение больше 3 или максимальное больше 10, то это означает, что слотов недостаточно. Поэтому следует увеличить параметр `LockHashSlots` в 2-3 раза (при этом взять простое число).

[NOTE]
====
Для применения параметра необходимо, чтобы сервер пересоздал таблицу блокировок (при этом в системе не должно остаться подключений и старой таблицы блокировок).
====

[[fbadmgd-config-param_eventmemsize]]
=== EventMemSize
(((Параметр конфигурации,EventMemSize)))

.Область действия:
Per-database.

.Тип параметра:
Integer.

Значение параметра `EventMemSize` определяет объем разделяемой памяти, которая будет выделена менеджеру событий.

Параметр `EventMemSize` имеет целочисленный тип. Единица измерения -- байты. Значение по умолчанию равно 64 Кбайта. Минимально допустимое значение равно 0. Максимальное значение равно 2 Гбайта.

.Установка параметра EventMemSize
[example]

[source]
----

EventMemSize = 64K
----

[[fbadmgd-config-engine]]
== Настройки ядра

[[fbadmgd-config-param_cpuaffinitymask]]
=== CpuAffinityMask

.Область действия:
Per-server.

.Тип параметра:
Integer.

Параметр `CpuAffinityMask` позволяет указать, какие процессоры (ядра) будут использоваться сервером (только для ОС Windows в архитектуре Super сервер).

[NOTE]
====
Параметр имеет эффект только в SMP (симметричных мультипроцессорных) системах.
====

Параметр имеет целочисленный тип. Значение параметра соответствует элементам битового массива, в котором каждый бит представляет центральный процессор. Таким образом, чтобы использовать только первый процессор, значение параметра должно быть равно 1. Чтобы использовать и центральный процессор 1, и центральный процессор 2 -- 3. Чтобы использовать центральный процессор 2, и центральный процессор 3 -- 6. Значение по умолчанию равно 0 (могут быть использованы все доступные процессоры).

.Установка параметра CpuAffinityMask
[example]
====
[source]
----
CpuAffinityMask = 64K
----
====

[[fbadmgd-config-param_gcpolicy]]
=== GCPolicy
(((Параметр конфигурации,GCPolicy)))

.Область действия:
Per-database.

.Тип параметра:
String.

Параметр `GCPolicy` используется для управления работой "`сборщика мусора`". Параметр имеет строковый тип.

Возможные значения параметра:

* `background` -- сборщик мусора работает как фоновый, собирая мусор в отдельном потоке;
* `cooperative` -- сборщик мусора работает в оперативном режиме, собирая мусор немедлен- но при чтении "`мусорных`" версий;
* `combined` -- сборщик мусора работает в оперативном режиме, но если мусор собрать не удается, то о "`замусоренных`" страницах сообщается фоновому сборщику мусора.

По умолчанию в архитектуре Super сервера "`сборщик мусора`" работает в комбинированном режиме. В архитектурах Classic и SuperClassic этот параметр игнорируется, а "`сборщик мусора`" всегда работает в оперативном режиме.

.Установка параметра GCPolicy
[example]
====
[source]
----
GCPolicy = combined
----
====

[[fbadmgd-config-param_securitydatabase]]
=== SecurityDatabase

.Область действия:
Per-database.

.Тип параметра:
String (путь к базе данных или алиас).

Определяет имя и расположение базы данных безопасности, в которой хранятся имена пользователей и пароли, используемые сервером для проверки удаленных подключений.

По-умолчанию в `firebird.conf`:

[source]
----
SecurityDatabase = $(dir_secDb)/security3.fdb
----

Параметр может быть переопределен для определенной базы данных в файле `databases.conf`. Любая база данных может быть базой данных безопасности, в том числе и для самой себя.

[[fbadmgd-config-windows]]
== Настройки для Windows систем

[[fbadmgd-config-param_guardianoption]]
=== GuardianOption
(((Параметр конфигурации,GuardianOption)))

.Область действия:
Per-server.

.Тип параметра:
Boolean.

Параметр определяет должен ли сторож (Guardian) запускать сервер после того, как его работа была завершена некорректно.

* 0 -- сервер стартует единожды;
* 1 -- сервер стартует каждый раз после некорректного завершения.

Параметр имеет логический тип. Значение по умолчанию равно 1 (истина).

.Установка параметра GuardianOption
[example]
====
[source]
----
GuardianOption = 1
----
====

[NOTE]
====
В современных версиях Windows службы могут перезапускаться при аварийном завершении, если указаны соответствующие настройки. Это делает сторож (Guardian) не нужным при установке Firebird в качестве службы. Однако он всё ещё может быть полезным, если Firebird стартует в режиме приложения.
====

[[fbadmgd-config-param_processprioritylevel]]
=== ProcessPriorityLevel

.Область действия:
Per-server.

.Тип параметра:
Integer.

Параметр определяет уровень приоритетов процессов сервера Firebird.

Параметр имеет целочисленный тип и может принимать значения:

* 0 -- нормальный приоритет (значение по умолчанию);
* положительное значение -- повышенный приоритет (тоже самое что опция -B в командной строке);
* отрицательное значение -- пониженный приоритет.

[IMPORTANT]
====
Все изменения данного параметра должны быть тщательно проверены, чтобы гарантировать, что сервер продолжает обрабатывать запросы.
====

.Установка параметра ProcessPriorityLevel
[example]
====
[source]
----
ProcessPriorityLevel = 0
----
====

[[fbadmgd-config-param_ipcname]]
=== IpcName
(((Параметр конфигурации,IpcName)))

.Область действия:
Per-connection.

.Тип параметра:
String.

Параметр `IpcName` определяет имя области разделяемой памяти используемой в качестве транспортного канала в локальном протоколе. Параметр имеет строковый тип. Значение по умолчанию равно `FIREBIRD`.

[NOTE]
====
Локальный протокол не совместим с Firebird версия которого меньше 2.0.
====

.Установка параметра IpcName
[example]

[source]
----

IpcName = FIREBIRD
----

[NOTE]
====
* Сервер может регистрировать объекты в пространстве имен Global, только если он выполняется под учетной записью с привилегией SE_CREATE_GLOBAL_NAME. Это означает, что, если вы работаете под ограниченной учетной записью в Vista, XP SP2 или 2000 SP4, возможность использования локального протокола для других сеансов будет недоступна.
* Если на одном сервере установлено несколько экземпляров Firebird, и все они содержат одно и то же значение параметра IpcName (явно заданное или умалчиваемое), то `firebird.log` всех запускаемых экземпляров, начиная со второго, будет при каждом (ре-)старте пополняться сообщением вида:
+

----
XNET error: XNET server initialization failed. Probably another instance 
of server is already running. 
operating system directive CreateMutex failed
Невозможно создать файл, так как он уже существует.
----
+
Для каждого подключения к СУБД может быть назначено индивидуальное значение этого параметра.

====

[[fbadmgd-config-param_remotepipename]]
=== RemotePipeName

.Область действия:
Per-connection.

.Тип параметра:
String.

Параметр `RemotePipeName` определяет название канала (Pipe), используемого как транспортный канал в протоколе NetBEUI. Название канала в протоколе NetBEUI имеет то же самое значение, что и номер порта для протокола TCP/IP.

Параметр имеет строковый тип. Значение по умолчанию равно `interbas` и совместимо с InterBase/Firebird 1.0.

.Установка параметра RemotePipeName
[example]
====
[source]
----
RemotePipeName = interbas
----
====

[[fbadmgd-config-unix]]
== Настройки для Unix/Linux систем

[[fbadmgd-config-param_redirection]]
=== Redirection
(((Параметр конфигурации,Redirection)))

.Область действия:
Per-server.

.Тип параметра:
Boolean.

Параметр `Redirection` используется для отключения защиты от переадресации запросов на другие сервера. Возможность переадресации запросов на другие серверы изначально присутствовала в InterBase. Но она была исключена корпорацией Borland в InterBase 6.0 после доработки добавившей SQL-диалекты. Возможность перенаправления запросов была восстановлена в Firebird 2.0.

[WARNING]
====
На сегодняшний день использование этой возможности (прокси сервер) представляет угрозу безопасности. Например, вы используете защищенный сервер Firebird, доступ к которому осуществляется из глобальной сети. В этом случае, если у сервера есть доступ к локальной сети, то он будет исполнять роль шлюза для входящих запросов типа: 

[source]
----
firebird.your.domain.com:internal_server:/private/database.fdb
----

При этом злоумышленнику достаточно знать имя или IP-адрес хоста вашей локальной сети, потому что для соединения не требуется знать логин и пароль на внешнем сервере. Такой шлюз позволяет обойти систему сетевой защиты, установленную в вашей локальной сети.
====

Параметр имеет логический тип. Значение по умолчанию равно 0 (`false`). В этом случае возможность перенаправления запросов отключена. Для включения этой опции следует значение параметра выставить равным 1 (`true`).

.Установка параметра Redirection
[example]
====
[source]
----
Redirection = 0
----
====

[WARNING]
====
Не включайте эту опцию если вы не уверены, что именно она делает.
====

[[fbadmgd-config-servermode]]
== Настройки архитектуры

[[fbadmgd-config-param_servermode]]
=== ServerMode

.Область действия:
Per-server.

.Тип параметра:
String.

Параметр `ServerMode` определяет архитектуру сервера.

Существует 3 варианта архитектуры: 

* `Super` (или `ThreadedDedicated`) -- база данных открывается эксклюзивно одним серверным процессом, им же обслуживаются все соединения с базой данных. Подключения обрабатываются потоками из общего пула; используется общий страничный кэш на каждую базу данных для всех соединений и общий кэш для временного пространства (сортировок).
* `SuperClassic` (или `ThreadedShared`) -- базы данных открываются одним серверным процессом, но доступ не исключительный -- embedded процессы могут открыть одновременно одну ту же базу. Подключения обрабатываются потоками из общего пула; используется собственный страничный кэш для каждого соединения и общий кэш для временного пространства (сортировок).
* `Classic` (или `MultiProcess`) -- создаётся отдельный процесс на каждое соединение с базой данных. Каждая база данных может быть открыта несколькими процессами (включая локальные для embedded доступа); используется отдельный кеш страниц на каждое соединение и отдельный кэш для временного пространства (сортировок).


