[[fbadmdg-files]]


[[fbadmdg-files-conf]]
== Файлы конфигурации

databases.conf::

В этом текстовом файле можно сопоставить конкретный путь к БД и псевдоним, чтобы затем в прикладных кодах использовать более короткий и удобный псевдоним для обращения к нужной базе данных.
Также здесь указываются индивидуальные настройки для каждой конкретной базы данных.
Если под управлением сервера Firebird находится более 1 базы данных, то рекомендуем все настройки уровня базы данных делать в этом файле.

fbtrace.conf::

Файл с шаблоном настроек `fbtrace.conf` находится в корневом каталоге и содержит список отслеживаемых событий и указывает размещение логов трассировки для каждого события.
Это позволяет достаточно гибко настроить параметры аудита различных событий для любой базы данных, при этом логирование будет осуществляться в отдельные файлы.

firebird.conf::

Файл содержит параметры конфигурации сервера.

plugins.conf::

Файл используется для настройки различных плагинов.
Если в файле не указана конфигурация для плагина, то для него будут действовать настройки по умолчанию.

udr_engine.conf::

Файл используется для настройки плагина UDR Engine -- движок для подключения внешних процедур, функций и триггеров.
Файл располагается в директории `plugins`.

fbintl.conf::

Файл конфигурации для библиотеки интернационализации.
Файл располагается в директории `intl`.

[[fbadmdg-files-exe]]
== Инструменты администрирования и сервисы

В Windows исполняемые файлы имеют расширение `.exe`, в других операционных системах могут использоваться другие расширения или вовсе не использоваться.

fb_lock_print::

Эта утилита формирует статистические данные файла блокировок, который поддерживается в Firebird для управления последовательностью изменений базы данных несколькими транзакциями.
Она может быть полезным инструментом анализа проблем взаимной блокировки.

fbguard::

Исполняемый файл приложения Guardian.
Он контролирует процесс сервера.
Если сервер упал по какой-либо причине, Guardian автоматически перезапускает его.
+
[NOTE]
====
В современных версиях Windows не требуется.
Дело в том, что у служб можно установить свойство автоматического перезапуска в случае падения.
Однако данная утилита может быть полезна, если Firebird запускается в качестве приложения.
====

fbsvcmgr::

Утилита предоставляет интерфейс командной строки для Services API, обеспечивая доступ к любой службе, которая реализуется в СУБД.

fbtracemgr::

Утилита для работы в интерактивном режиме с трассировкой.

firebird::

Исполняемый файл сервера (слушатель).

gbak::

Эта утилита предназначена для резервного копирования и восстановления баз данных.
Она также обнаруживает разрушения базы данных, освобождает дисковое пространство, появившееся в результате удалений, разрешает незавершенные транзакции, позволяет разделять базы данных на несколько файлов.
Она также используется для создания переносимой копии с целью восстановления вашей базы данных на другой аппаратной платформе.

gfix::

Это набор общих вспомогательных утилит для изменения свойств баз данных, устранения небольших повреждений базы данных, выполнения различных задач чистки и т.
д.
Утилита также предоставляет средство администратора для отключения конкретных баз данных до завершения работы сервера.
Она может быть использована вместе с утилитой `gbak` для восстановления некоторых типов нарушений в базе данных.

gpre::

Это препроцессор, который конвертирует исходный код, написанный на некоторых языках и содержащий встроенный псевдокод SQL, в корректный отформатированный вызов функций Firebird API.

gsec::

Этот инструмент поддержки списка пользователей и их паролей является интерфейсом командной строки для базы данных `security3.fdb`; он управляет записями пользователей на сервере.

gsplit::

Это фильтр, который позволяет преодолевать ограничения на максимальный размер файла, существующие в некоторых операционных системах, при создании резервной копии очень большой базы данных.
Эта утилита поставляется только для ОС Windows и, к сожалению, кажется она не работает.
К счастью, `gbak` позволяет разбивать файлы резервной копии на несколько частей, так что `gsplit` не требуется.
В системах ОС Unix существует подходящие утилиты из операционной системы, которые могут быть использованы вместо `gsplit`, если это необходимо.

gstat::

Этот инструмент получения статистики.
Он собирает и отображает статистические сведения по индексам и данным базы данных.

instclient::

Назначение утилиты `instclient` состоит в том, что она:
+
* позволяет установить клиентскую часть Firebird одной командой;
* позволяет установить клиентскую часть как `fbclient.dll`, либо как `gds32.dll`; 
* позволяет проверить наличие установленной библиотеки `fbclient` или `gds32`; 
* позволяет удалить уже установленный в системе `fbclient` или `gds32`. 


instreg::

Эта утилита прописывает необходимую информацию в реестр Windows, указывая умолчательное расположение файлов сервера.

instsvc::

Утилита `instsvc` записывает, удаляет или меняет информацию о запуске сервера в базе сервисов операционной системы Windows.

isql::

Интерактивный инструмент, который позволяет выполнять запросы к базе данных.

nbackup::

Утилита позволяет создавать резервные копии и восстанавливать из резервных копий также, как `gbak`, и дополнительно позволяет создавать инкрементные копии и восстанавливать из них БД.

qli::

Это Query Language Interpreter (интерпретатор языка запросов), интерактивный клиентский инструмент запросов.
Он может обрабатывать операторы DDL и DML из SQL и GDML.
Хотя уже есть `isql` и другие инструменты графического интерфейса сторонних разработчиков, `qli` все еще имеет значение по причине его способности осуществлять некоторые операции, до сих пор не реализованные в SQL Firebird.
В отличие от `isql`, `qli` может одновременно соединяться более чем с одной базой данных и может симулировать обращение к нескольким базам данных в одном запросе.

[[fbadmdg-files-lib]]
== Динамические библиотеки

В Windows динамические библиотеки имеют расширение `.dll`, в Linux -- `.so`, в Mac OS -- `.dylib`.

fbclient::

Клиентская библиотека.
Предоставляет интерфейс прикладного программирования (API) с функциями для подключения к сервисам, работы с базами данных и их созданию.
Библиотека также выполняет роль y-valve для подключения и сопряжения различных плагинов.

В Windows имеет имя `fbclient.dll`, в Unix -- `libfbclient.so`.

ib_util::

Библиотека утилиты памяти.

В Windows имеет имя `ib_util.dll`, в Unix -- `libib_util.so`.

ICU::

ICU -- International Components for Unicode -- библиотеки поддержки юникода.
+
В Windows используется библиотека поставляемая в комплекте Firebird, в Unix -- используется системная библиотека.
В Windows в комплекте с Firebird поставляются следующие файлы: `icudt52l.dat`, `icudt52.dll`, `icuin52.dll`, `icuuc52.dll`.

Microsoft VC++ Runtime::

Microsoft VC++ Runtime 2010 требуется только в Windows.
Поставляется в комплекте с Firebird на случай, если библиотека соответствующей версии не установлена в системе.
В комплекте Firebird под Windows входят файлы: `msvcp100.dll`, `msvcr100.dll`.

zlib1.dll::

Библиотека `zlib1.dll` используется для сжатия сетевого трафика в Windows, в UNIX используется системная библиотека.

fbintl::

Библиотека для поддержки интернационализации, кодировок и порядка сортировок.
Располагается в директории `intl` относительно корневой директории сервера.

В Windows имеет имя `fbintl.dll`, в Unix -- `fbintl`.

[[fbadmdg-files-plugins]]
== Плагины

Модули плагинов размещаются в динамических библиотеках.
В Firebird для модулей плагинов выделена папка `plugins`, которая находится в корневой директории сервера.

Engine12::

Поставщик (ядро) для работы с ODS 12.
+
В Windows имеет имя `engine12.dll`, в Unix -- `libEngine12.so`, в MacOS -- `libEngine12.dylib`.

fbtrace::

Плагин трассировки.
+
В Windows имеет имя `fbtrace.dll`, в Unix -- `libfbtrace.so`, в MacOS -- `libfbtrace.dylib`.

legacy_auth::

Плагин для поддержки традиционной аутентификации (использовалась в Firebird 2.5 и в более ранних версиях).
+
В Windows имеет имя `legacy_auth.dll`, в Unix -- `libLegacy_Auth.so`, в MacOS -- `libLegacy_Auth.dylib`.

legacy_usermanager::

Менеджер пользователей, который используется в традиционной аутентификации.
+
В Windows имеет имя `legacy_usermanager.dll`, в Unix -- `libLegacy_UserManager.so`, в MacOS -- `libLegacy_UserManager.dylib`.

srp::

Плагин аутентификации методом SRP -- Secure remote Password.
+
В Windows имеет имя `srp.dll`, в Unix -- `libSrp.so`, в MacOS -- `libSrp.dylib`.

udr_engine::

Внешний движок для подключения UDR написанных на компилируемых языках C, C++, Pascal.
+
В Windows имеет имя `udr_engine.dll`, в Unix -- `libudr_engine.so`, в MacOS -- `libudr_engine.dylib`.

[[fbadmdg-files-include]]
== Включаемые файлы

В директории `include` расположены заголовочные C файлы с функциями, константами, структурами и интерфейсами API Firebird.

[[fbadmdg-files-examples]]
== Примеры

В директории `examples` расположены примеры работы с Firebird API, написания плагинов, UDF и UDR.

[[fbadmdg-files-doc]]
== Документация

В директории `doc` расположены файлы документации.

[[fbadmdg-files-other]]
== Другие файлы

security3.fdb::

База данных безопасности.
В этой базе хранятся параметры пользователей системы, политики доступа, глобальные роли.

firebird.log::

Лог-файл сервера.

firebird.msg::

Файл с сообщениями сервера (в основном об ошибках).
