[[fbadmdg-files]]


[[fbadmdg-files-conf]]
== Файлы конфигурации

_databases.conf_::

В этом текстовом файле можно сопоставить конкретный путь к БД и псевдоним, чтобы затем в прикладных кодах использовать более короткий и удобный псевдоним для обращения к нужной базе данных.
Также здесь указываются индивидуальные настройки для каждой конкретной базы данных.
Если под управлением сервера Firebird находится более 1 базы данных, то рекомендуем все настройки уровня базы данных делать в этом файле.

_fbtrace.conf_::

Файл с шаблоном настроек [path]_fbtrace.conf_ находится в корневом каталоге и содержит список отслеживаемых событий и указывает размещение логов трассировки для каждого события.
Это позволяет достаточно гибко настроить параметры аудита различных событий для любой базы данных, при этом логирование будет осуществляться в отдельные файлы.

_firebird.conf_::

Файл содержит параметры конфигурации сервера.

_plugins.conf_::

Файл используется для настройки различных плагинов.
Если в файле не указана конфигурация для плагина, то для него будут действовать настройки по умолчанию.

_udr_engine.conf_::

Файл используется для настройки плагина UDR Engine -- движок для подключения внешних процедур, функций и триггеров.
Файл располагается в директории [path]_plugins_.

_fbintl.conf_::

Файл конфигурации для библиотеки интернационализации.
Файл располагается в директории [path]_intl_.

[[fbadmdg-files-exe]]
== Инструменты администрирования и сервисы

В Windows исполняемые файлы имеют расширение [path]_.exe_, в других операционных системах могут использоваться другие расширения или вовсе не использоваться.

_fb_lock_print_::

Эта утилита формирует статистические данные файла блокировок, который поддерживается в Firebird для управления последовательностью изменений базы данных несколькими транзакциями.
Она может быть полезным инструментом анализа проблем взаимной блокировки.

_fbguard_::

Исполняемый файл приложения Guardian.
Он контролирует процесс сервера.
Если сервер упал по какой-либо причине, Guardian автоматически перезапускает его.
+
[NOTE]
====
В современных версиях Windows не требуется.
Дело в том, что у служб можно установить свойство автоматического перезапуска в случае падения.
Однако данная утилита может быть полезна, если Firebird запускается в качестве приложения.
====

_fbsvcmgr_::

Утилита предоставляет интерфейс командной строки для Services API, обеспечивая доступ к любой службе, которая реализуется в СУБД.

_fbtracemgr_::

Утилита для работы в интерактивном режиме с трассировкой.

_firebird_::

Исполняемый файл сервера (слушатель).

_gbak_::

Эта утилита предназначена для резервного копирования и восстановления баз данных.
Она также обнаруживает разрушения базы данных, освобождает дисковое пространство, появившееся в результате удалений, разрешает незавершенные транзакции, позволяет разделять базы данных на несколько файлов.
Она также используется для создания переносимой копии с целью восстановления вашей базы данных на другой аппаратной платформе.

_gfix_::

Это набор общих вспомогательных утилит для изменения свойств баз данных, устранения небольших повреждений базы данных, выполнения различных задач чистки и т.
д.
Утилита также предоставляет средство администратора для отключения конкретных баз данных до завершения работы сервера.
Она может быть использована вместе с утилитой gbak для восстановления некоторых типов нарушений в базе данных.

_gpre_::

Это препроцессор, который конвертирует исходный код, написанный на некоторых языках и содержащий встроенный псевдокод SQL, в корректный отформатированный вызов функций Firebird API.

_gsec_::

Этот инструмент поддержки списка пользователей и их паролей является интерфейсом командной строки для базы данных security3.fdb; он управляет записями пользователей на сервере.

_gsplit_::

Это фильтр, который позволяет преодолевать ограничения на максимальный размер файла, существующие в некоторых операционных системах, при создании резервной копии очень большой базы данных.
Эта утилита поставляется только для ОС Windows и, к сожалению, кажется она не работает.
К счастью, gbak позволяет разбивать файлы резервной копии на несколько частей, так что gsplit не требуется.
В системах ОС Unix существует подходящие утилиты из операционной системы, которые могут быть использованы вместо gsplit, если это необходимо.

_gstat_::

Этот инструмент получения статистики.
Он собирает и отображает статистические сведения по индексам и данным базы данных.

_instclient_::

Назначение утилиты instclient состоит в том, что она:
+
* позволяет установить клиентскую часть Firebird одной командой;
* позволяет установить клиентскую часть как fbclient.dll, либо как gds32.dll; 
* позволяет проверить наличие установленной библиотеки fbclient или gds32; 
* позволяет удалить уже установленный в системе fbclient или gds32. 


_instreg_::

Эта утилита прописывает необходимую информацию в реестр Windows, указывая умолчательное расположение файлов сервера.

_instsvc_::

Утилита instsvc записывает, удаляет или меняет информацию о запуске сервера в базе сервисов операционной системы Windows.

_isql_::

Интерактивный инструмент, который позволяет выполнять запросы к базе данных.

_nbackup_::

Утилита позволяет создавать резервные копии и восстанавливать из резервных копий также, как gbak, и дополнительно позволяет создавать инкрементные копии и восстанавливать из них БД.

_qli_::

Это Query Language Interpreter (интерпретатор языка запросов), интерактивный клиентский инструмент запросов.
Он может обрабатывать операторы DDL и DML из SQL и GDML.
Хотя уже есть isql и другие инструменты графического интерфейса сторонних разработчиков, qli все еще имеет значение по причине его способности осуществлять некоторые операции, до сих пор не реализованные в SQL Firebird.
В отличие от isql, qli может одновременно соединяться более чем с одной базой данных и может симулировать обращение к нескольким базам данных в одном запросе.

[[fbadmdg-files-lib]]
== Динамические библиотеки

В Windows динамические библиотеки имеют расширение [path]_.dll_, в Linux -- [path]_.so_, в Mac OS -- [path]_.dylib_.

fbclient::

Клиентская библиотека.
Предоставляет интерфейс прикладного программирования (API) с функциями для подключения к сервисам, работы с базами данных и их созданию.
Библиотека также выполняет роль y-valve для подключения и сопряжения различных плагинов.

В Windows имеет имя [path]_fbclient.dll_, в Unix -- [path]_libfbclient.so_.

ib_util::

Библиотека утилиты памяти.

В Windows имеет имя [path]_ib_util.dll_, в Unix -- [path]_libib_util.so_.

ICU::

ICU -- International Components for Unicode -- библиотеки поддержки юникода.
+
В Windows используется библиотека поставляемая в комплекте Firebird, в Unix -- используется системная библиотека.
В Windows в комплекте с Firebird поставляются следующие файлы: [path]_icudt52l.dat_, [path]_icudt52.dll_, [path]_icuin52.dll_, [path]_icuuc52.dll_.

Microsoft VC++ Runtime::

Microsoft VC++ Runtime 2010 требуется только в Windows.
Поставляется в комплекте с Firebird на случай, если библиотека соответствующей версии не установлена в системе.
В комплекте Firebird под Windows входят файлы: [path]_msvcp100.dll_, [path]_msvcr100.dll_.

_zlib1.dll_::

Библиотека [path]_zlib1.dll_ используется для сжатия сетевого трафика в Windows, в UNIX используется системная библиотека.

_fbintl_::

Библиотека для поддержки интернационализации, кодировок и порядка сортировок.
Располагается в директории [path]_intl_ относительно корневой директории сервера.

В Windows имеет имя [path]_fbintl.dll_, в Unix -- [path]_fbintl_.

[[fbadmdg-files-plugins]]
== Плагины

Модули плагинов размещаются в динамических библиотеках.
В Firebird для модулей плагинов выделена папка [path]_plugins_, которая находится в корневой директории сервера.

Engine12::

Поставщик (ядро) для работы с ODS 12.
+
В Windows имеет имя [path]_engine12.dll_, в Unix -- [path]_libEngine12.so_, в MacOS -- [path]_libEngine12.dylib_.

fbtrace::

Плагин трассировки.
+
В Windows имеет имя [path]_fbtrace.dll_, в Unix -- [path]_libfbtrace.so_, в MacOS -- [path]_libfbtrace.dylib_.

legacy_auth::

Плагин для поддержки традиционной аутентификации (использовалась в Firebird 2.5 и в более ранних версиях).
+
В Windows имеет имя [path]_legacy_auth.dll_, в Unix -- [path]_libLegacy_Auth.so_, в MacOS -- [path]_libLegacy_Auth.dylib_.

legacy_usermanager::

Менеджер пользователей, который используется в традиционной аутентификации.
+
В Windows имеет имя [path]_legacy_usermanager.dll_, в Unix -- [path]_libLegacy_UserManager.so_, в MacOS -- [path]_libLegacy_UserManager.dylib_.

srp::

Плагин аутентификации методом SRP -- Secure remote Password.
+
В Windows имеет имя [path]_srp.dll_, в Unix -- [path]_libSrp.so_, в MacOS -- [path]_libSrp.dylib_.

udr_engine::

Внешний движок для подключения UDR написанных на компилируемых языках C, C++, Pascal.
+
В Windows имеет имя [path]_udr_engine.dll_, в Unix -- [path]_libudr_engine.so_, в MacOS -- [path]_libudr_engine.dylib_.

[[fbadmdg-files-include]]
== Включаемые файлы

В директории [path]_include_ расположены заголовочные C файлы с функциями, константами, структурами и интерфейсами API Firebird.

[[fbadmdg-files-examples]]
== Примеры

В директории [path]_examples_ расположены примеры работы с Firebird API, написания плагинов, UDF и UDR.

[[fbadmdg-files-doc]]
== Документация

В директории [path]_doc_ расположены файлы документации.

[[fbadmdg-files-other]]
== Другие файлы

_security3.fdb_::

База данных безопасности.
В этой базе хранятся параметры пользователей системы, политики доступа, глобальные роли.

_firebird.log_::

Лог-файл сервера.

_firebird.msg_::

Файл с сообщениями сервера (в основном об ошибках).
